import Mathlib.RepresentationTheory.Irreducible
import Mathlib.Tactic

/-!
# Elementary transport used in the even-field argument

This file checks the group identities that occur in the proof that field
automorphisms fix generic weights.  It deliberately does not formalise
algebraic groups, unipotent characters, Clifford correspondence, Gallagher's
theorem, or character induction.  Those inputs remain external in the type
`C` dependency ledger.
-/

namespace Formalisation.EvenFieldTransport

/-- The two elementary identities in the rational-Levi transport argument. -/
def LangTransportPrinciple : Prop :=
  ∀ {G : Type} [Group G]
    (F sigma : G →* G) (g w x : G),
    (∀ z, F (sigma z) = sigma (F z)) →
    sigma w = w → F g = g * w →
      F (g * (sigma g)⁻¹) = g * (sigma g)⁻¹ ∧
      (g * (sigma g)⁻¹) * sigma (g * x * g⁻¹) *
          (g * (sigma g)⁻¹)⁻¹ = g * sigma x * g⁻¹

/-- The kernel and fixed-point conclusions used to pass from the Weyl-group
quotient to the finite relative normaliser quotient. -/
def RelativeNormalizerPrinciple : Prop :=
  ∀ {N Q : Type} [Group N] [Group Q]
    (F sigma : N →* N) (pi : N →* Q),
    (∀ z, F (sigma z) = sigma (F z)) →
    (∀ y, pi (sigma y) = pi y) →
    (∀ y, F y = y) →
      ∀ y, y⁻¹ * sigma y ∈ pi.ker ∧
        F (y⁻¹ * sigma y) = y⁻¹ * sigma y

/-- Irreducibility on a smaller subgroup implies irreducibility on every
intermediate subgroup. -/
def IntermediateIrreducibilityPrinciple : Prop :=
  ∀ {K k V : Type} [Group K] [Field k]
    [AddCommGroup V] [Module k V] [Nontrivial V]
    (rho : Representation k K V) (H L : Subgroup K),
    H ≤ L →
    Representation.IsIrreducible (rho.comp H.subtype) →
    Representation.IsIrreducible (rho.comp L.subtype)

/-- If `F` and `sigma` commute, `sigma` fixes `w`, and `F g = g * w`, then
the usual Lang cocycle `g * (sigma g)⁻¹` is fixed by `F`. -/
theorem lang_cocycle_fixed
    {G : Type*} [Group G]
    (F sigma : G →* G) (g w : G)
    (hcomm : ∀ x, F (sigma x) = sigma (F x))
    (hw : sigma w = w) (hg : F g = g * w) :
    F (g * (sigma g)⁻¹) = g * (sigma g)⁻¹ := by
  simp [hg, hcomm, hw]

/-- Conjugating a field map by its Lang cocycle transports the action through
conjugation by `g`. -/
theorem lang_cocycle_intertwines
    {G : Type*} [Group G]
    (sigma : G →* G) (g x : G) :
    (g * (sigma g)⁻¹) * sigma (g * x * g⁻¹) *
        (g * (sigma g)⁻¹)⁻¹ =
      g * sigma x * g⁻¹ := by
  simp only [map_mul, map_inv]
  group

/-- Equivariance of a quotient map, when the quotient action is trivial,
places the difference `y⁻¹ sigma(y)` in the kernel. -/
theorem inverse_mul_image_mem_kernel
    {N Q : Type*} [Group N] [Group Q]
    (pi : N →* Q) (sigma : N →* N)
    (hpi : ∀ y, pi (sigma y) = pi y) (y : N) :
    y⁻¹ * sigma y ∈ pi.ker := by
  change pi (y⁻¹ * sigma y) = 1
  simp [hpi]

/-- If `F` and `sigma` commute and `y` is fixed by `F`, then the difference
`y⁻¹ sigma(y)` is also fixed by `F`. -/
theorem inverse_mul_image_fixed
    {G : Type*} [Group G]
    (F sigma : G →* G)
    (hcomm : ∀ x, F (sigma x) = sigma (F x))
    (y : G) (hy : F y = y) :
    F (y⁻¹ * sigma y) = y⁻¹ * sigma y := by
  simp [hy, hcomm]

/-- A representation that is irreducible on a subgroup remains irreducible
on every intermediate subgroup.  This checks the linear-algebra step used
when an extension supplied on a large inertia group is restricted to the
smaller group generated by the local normaliser and a field automorphism. -/
theorem irreducible_on_intermediate_subgroup
    {K k V : Type*} [Group K] [Field k]
    [AddCommGroup V] [Module k V] [Nontrivial V]
    (rho : Representation k K V)
    (H L : Subgroup K) (hHL : H ≤ L)
    (hirr : Representation.IsIrreducible (rho.comp H.subtype)) :
    Representation.IsIrreducible (rho.comp L.subtype) := by
  let Sbot : Subrepresentation (rho.comp L.subtype) := ⊥
  let Stop : Subrepresentation (rho.comp L.subtype) := ⊤
  have hne : Sbot ≠ Stop := by
    intro h
    obtain ⟨v, hv⟩ := exists_ne (0 : V)
    have hvtop : v ∈ Stop := by
      change v ∈ (⊤ : Submodule k V)
      exact Submodule.mem_top
    have hvbot : v ∈ Sbot := by rw [h]; exact hvtop
    change v ∈ (⊥ : Submodule k V) at hvbot
    exact hv (by simpa using hvbot)
  let _ : Nontrivial (Subrepresentation (rho.comp L.subtype)) :=
    ⟨⟨Sbot, Stop, hne⟩⟩
  refine IsSimpleOrder.mk fun S => ?_
  let SH : Subrepresentation (rho.comp H.subtype) :=
    { toSubmodule := S.toSubmodule
      apply_mem_toSubmodule := by
        intro h v hv
        exact S.apply_mem_toSubmodule ⟨h, hHL h.2⟩ hv }
  rcases @IsSimpleOrder.eq_bot_or_eq_top _ _ _ hirr SH with hbot | htop
  · left
    apply Subrepresentation.toSubmodule_injective
    apply le_antisymm
    · intro v hv
      have hvH : v ∈ SH := hv
      rw [hbot] at hvH
      change v ∈ (⊥ : Submodule k V) at hvH ⊢
      exact hvH
    · exact bot_le
  · right
    apply Subrepresentation.toSubmodule_injective
    apply le_antisymm
    · exact le_top
    · intro v _
      have hvH : v ∈ (⊤ : Subrepresentation (rho.comp H.subtype)) := by
        change v ∈ (⊤ : Submodule k V)
        exact Submodule.mem_top
      rw [← htop] at hvH
      change v ∈ S.toSubmodule at hvH ⊢
      exact hvH

/-- Kernel-checked proof of `LangTransportPrinciple`. -/
theorem langTransportPrinciple : LangTransportPrinciple := by
  intro G _ F sigma g w x hcomm hw hg
  exact ⟨lang_cocycle_fixed F sigma g w hcomm hw hg,
    lang_cocycle_intertwines sigma g x⟩

/-- Kernel-checked proof of `RelativeNormalizerPrinciple`. -/
theorem relativeNormalizerPrinciple : RelativeNormalizerPrinciple := by
  intro N Q _ _ F sigma pi hcomm hpi hfixed y
  exact ⟨inverse_mul_image_mem_kernel pi sigma hpi y,
    inverse_mul_image_fixed F sigma hcomm y (hfixed y)⟩

/-- Kernel-checked proof of `IntermediateIrreducibilityPrinciple`. -/
theorem intermediateIrreducibilityPrinciple :
    IntermediateIrreducibilityPrinciple := by
  intro K k V _ _ _ _ _ rho H L hHL hirr
  exact irreducible_on_intermediate_subgroup rho H L hHL hirr

end Formalisation.EvenFieldTransport


/-
This file is part of ModularRep, the Lean companion to
Baoyu Zhang (2026), "On the inductive blockwise Alperin weight condition
for type B and type C".

The formalisation checks selected arguments under explicit external
assumptions. See FORMALISATION_GUIDE.md in the package root.
-/
