import Formalisation.SylowObstruction
import ModularRep.OddQuasiIsolation
import ModularRep.PaperProofs.OddTwoWreathReflection
import ModularRep.StrictQuasiIsolation

/-!
# Source-shaped relative deductions for manuscript Proposition 3.3

This file checks two deductions made in the proof of `prop:odd-two` without
assuming that a block is BAW-good or that an iBAW bijection exists.

For the principal-block correction, Feng--Yu--Zhang, Lemma 2.3, supplies the
necessary condition that `Z(R)` is a Sylow `2`-subgroup of the centraliser of a
principal weight subgroup.  Proposition 3.48(4) identifies the corrected
even-multiplicity family.  The concrete tensor and wreath-product calculation
in the manuscript must identify the candidate-specific group with
`C_G(R)` and supply an involution in it which centralises and lies outside the
embedded `Z(R)`.  Lean constructs the subgroup generated by the Sylow subgroup
and that involution, proves that it is a `2`-group, and obtains the Sylow
contradiction.

For Jordan reduction, Bonnafe, Proposition 4.11(a), supplies `s ^ 2 = 1` for
the relevant quasi-isolated parameter in the odd-characteristic special
orthogonal dual group.  Feng--Li--Zhang, Remark 5.8, supplies the
identity-parameter/principal-block interpretation.  Lean proves the intervening
odd-order argument and combines it with the type `A`/type `C` split of the
connected Dynkin subdiagrams.  Feng--Li--Zhang, Theorem 5.7, and all concrete
character and weight parametrisations remain external inputs; no conclusion
of that theorem is encoded as a premise here.
-/

namespace ModularRep.PaperProofs.OddTwoProposition33Relative

open Formalisation

universe u v

section PrincipalBlockExclusion

variable {G Candidate : Type*} [Group G]

/-- A cyclic subgroup generated by an involution is a `2`-group. -/
theorem zpowers_isPGroup_two_of_sq_eq_one {t : G} (ht : t ^ 2 = 1) :
    IsPGroup 2 (Subgroup.zpowers t) := by
  rw [isPGroup_iff_orderOf_dvd_pow]
  intro x
  refine ⟨1, ?_⟩
  rw [pow_one]
  simpa using (orderOf_dvd_of_mem_zpowers x.property).trans
    (orderOf_dvd_of_pow_eq_one ht)

/-- The group-theoretic core of the manuscript's reflection argument.

The overgroup is not assumed: it is constructed as
`P \sqcup \langle t \rangle`.  Centralisation puts the cyclic factor in the
normaliser of `P`, so the join is a `2`-group. -/
theorem false_of_centralising_involution_outside_sylow
    (P : Sylow 2 G) {t : G}
    (htSq : t ^ 2 = 1)
    (htCentral : t ∈ Subgroup.centralizer (P : Set G))
    (htOutside : t ∉ (P : Subgroup G)) : False := by
  let T : Subgroup G := Subgroup.zpowers t
  have hTTwo : IsPGroup 2 T :=
    zpowers_isPGroup_two_of_sq_eq_one htSq
  have hTNormalizer : T ≤ Subgroup.normalizer (P : Subgroup G) := by
    apply Subgroup.zpowers_le.mpr
    exact Subgroup.centralizer_le_normalizer (P : Set G) htCentral
  let Q : Subgroup G := (P : Subgroup G) ⊔ T
  have hQTwo : IsPGroup 2 Q :=
    P.isPGroup'.to_sup_of_normal_left' hTTwo hTNormalizer
  have hPQ : (P : Subgroup G) ≤ Q := le_sup_left
  have htT : t ∈ T := Subgroup.mem_zpowers t
  have htQ : t ∈ Q := (show T ≤ Q from le_sup_right) htT
  exact SylowObstruction.false_of_element_in_p_overgroup
    P Q hQTwo hPQ htQ htOutside

/-- Source-shaped data for members of the corrected
`R^{0,-}_{d,1,1,c}` family.

Each candidate has its own packed centraliser.  The final field is exactly the
necessary Sylow clause of Feng--Yu--Zhang, Lemma 2.3, after that centraliser
and `Z(R)` have been identified with the preceding fields. -/
structure EvenMultiplicityCandidateData (Candidate : Type v) where
  IsPrincipalWeight : Candidate → Prop
  geometry : Candidate →
    OddTwoWreathReflection.CentralizerReflectionGeometry.{u}
  principalCentreSylow : ∀ c, IsPrincipalWeight c →
    let X := geometry c
    ∃ P : @Sylow 2 X.CentralizerGroup X.group,
      (P : @Subgroup X.CentralizerGroup X.group) = X.centre

/-- A corrected even-multiplicity candidate satisfying the manuscript's
reflection calculation cannot be a principal weight subgroup. -/
theorem omitted_even_multiplicity_not_principal
    (D : EvenMultiplicityCandidateData Candidate)
    (c : Candidate) : ¬ D.IsPrincipalWeight c := by
  intro hPrincipal
  let X := D.geometry c
  let _ : Group X.CentralizerGroup := X.group
  obtain ⟨P, hP⟩ := D.principalCentreSylow c hPrincipal
  have htCentralP :
      X.reflection ∈ Subgroup.centralizer ((P : Subgroup X.CentralizerGroup) :
        Set X.CentralizerGroup) := by
    simpa [hP] using X.reflection_centralises_centre
  have htOutsideP : X.reflection ∉ (P : Subgroup X.CentralizerGroup) := by
    simpa [hP] using X.reflection_outside_centre
  exact false_of_centralising_involution_outside_sylow
    P X.reflection_sq htCentralP htOutsideP

end PrincipalBlockExclusion

section JordanTransition

open scoped Pointwise
open ModularRep.ManuscriptVerification.StrictQuasiIsolation

variable {Parameter Block : Type*} [Group Parameter]

/-- Source-shaped description of the strictly quasi-isolated blocks which
occur in the type `A`/type `C` subdiagram step of the proof.

The split into the two types is a standard root-system input.  In the type
`C` branch, the fields retain the semisimple parameter and all bridges needed
to apply Bonnafe's square theorem and the identity-label block statement. -/
structure StrictSubdiagramData where
  IsStrictBlock : Block → Prop
  IsTypeA : Block → Prop
  IsTypeC : Block → Prop
  IsSemisimpleTwoPrime : Parameter → Prop
  IsAssociated : Block → Parameter → Prop
  IsPrincipalBlock : Block → Prop
  finiteCentralizer : Parameter → Subgroup Parameter
  connectedCentralizer : Parameter → Subgroup Parameter
  IsProperLevi : Set Parameter → Prop
  finiteCentralizer_le : ∀ s,
    finiteCentralizer s ≤ Subgroup.centralizer {s}
  connectedCentralizer_le : ∀ s,
    connectedCentralizer s ≤ Subgroup.centralizer {s}
  split : ∀ b, IsStrictBlock b →
    IsTypeA b ∨
      ∃ s, IsTypeC b ∧ IsSemisimpleTwoPrime s ∧ IsAssociated b s ∧
        NotContainedInProperLevi
          ((finiteCentralizer s : Set Parameter) *
            (connectedCentralizer s : Set Parameter)) IsProperLevi
  bonnafeSquare : ∀ {s : Parameter},
    NotContainedInProperLevi
      (Subgroup.centralizer {s} : Set Parameter) IsProperLevi →
    s ^ 2 = 1
  twoPrimeOrder :
    OddQuasiIsolation.TwoPrimeOrderInterface IsSemisimpleTwoPrime
  identityLabelPrincipal :
    OddQuasiIsolation.PrincipalBlockInterface
      IsAssociated IsPrincipalBlock

/-- Every strictly quasi-isolated block needed by the reduction is either a
type `A` block or a principal type `C` block.

This is the strongest Jordan-transition conclusion proved here.  It does not
assert BAW-goodness, an iBAW bijection, or the conclusion of Feng--Li--Zhang,
Theorem 5.7. -/
theorem strictly_quasi_isolated_typeA_or_principal_typeC
    (D : StrictSubdiagramData (Parameter := Parameter) (Block := Block))
    {b : Block} (hb : D.IsStrictBlock b) :
    D.IsTypeA b ∨ (D.IsTypeC b ∧ D.IsPrincipalBlock b) := by
  rcases D.split b hb with
    hA | ⟨s, hC, hTwoPrime, hAssociated, hStrict⟩
  · exact Or.inl hA
  · refine Or.inr ⟨hC, ?_⟩
    have hQuasi :
        NotContainedInProperLevi
          (Subgroup.centralizer {s} : Set Parameter) D.IsProperLevi :=
      quasiIsolated_of_strictlyQuasiIsolated
        (D.finiteCentralizer_le s) (D.connectedCentralizer_le s) hStrict
    have hs : s = 1 :=
      (D.twoPrimeOrder hTwoPrime).eq_one_of_sq_eq_one
        (D.bonnafeSquare hQuasi)
    exact D.identityLabelPrincipal hAssociated hs

end JordanTransition

end ModularRep.PaperProofs.OddTwoProposition33Relative


/-
This file is part of ModularRep, the Lean companion to
Baoyu Zhang (2026), "On the inductive blockwise Alperin weight condition
for type B and type C".

The formalisation checks selected arguments under explicit external
assumptions. See FORMALISATION_GUIDE.md in the package root.
-/
