import ModularRep.PaperProofs.SporadicFi24ThreeBlockAutomorphismPromotionActual
import ModularRep.PaperProofs.CyclicOuterLemma37Concrete
import ModularRep.SubgroupIntervalTwo

/-!
# The selected Fischer outer involution

The chosen opposite automorphism generates a group of cardinality at most
two.  On the corresponding semidirect product, every stabiliser quotient by
the embedded inner stabiliser therefore has cardinality at most two, so an
intermediate subgroup is either the embedded inner stabiliser or the whole
stabiliser.

These are group-theoretic deductions from the supplied involution equation.
The full automorphism identification is obtained only from the explicit
inner-kernel and centreless hypotheses.  No character extension or block
equality is asserted here.
-/

noncomputable section

namespace ModularRep.PaperProofs.SporadicFi24SelectedOuterC2

open ModularRep.ManuscriptVerification.CyclicOuterBAW
open ModularRep.PaperProofs.CyclicOuterLemma37Concrete
open ModularRep.PaperProofs.SporadicFi24ThreeBlockCancellationActual
open ModularRep.PaperProofs.SporadicFi24ThreeBlockAutomorphismPromotionActual

universe u

variable {k X : Type u}
variable [Field k] [Group X] [Fintype X]

noncomputable local instance mulAutFinite : Finite (MulAut X) :=
  Finite.of_injective (fun alpha : MulAut X ↦ (alpha : X → X))
    DFunLike.coe_injective

/-- The cyclic subgroup generated by the selected opposite automorphism. -/
abbrev SelectedOuterGroup
    (S : Fi24ThreeBlockSource (k := k) (X := X)) :=
  Subgroup.zpowers S.outer

noncomputable local instance selectedOuterGroupFinite
    (S : Fi24ThreeBlockSource (k := k) (X := X)) :
    Finite (SelectedOuterGroup S) :=
  Finite.of_injective
    (fun e : SelectedOuterGroup S ↦ (e.1.unop : X → X))
    (fun a b h ↦ Subtype.ext
      (MulOpposite.unop_injective (DFunLike.coe_injective h)))

/-- The selected opposite subgroup, converted to a homomorphism into the
ordinary automorphism group. -/
def selectedOuterField
    (S : Fi24ThreeBlockSource (k := k) (X := X)) :
    SelectedOuterGroup S →* MulAut X where
  toFun e := e.1.unop⁻¹
  map_one' := by simp
  map_mul' a b := by simp

/-- The right-action homomorphism recovers the literal inclusion of the
selected opposite subgroup. -/
@[simp]
theorem inverseOpHom_selectedOuterField
    (S : Fi24ThreeBlockSource (k := k) (X := X))
    (e : SelectedOuterGroup S) :
    inverseOpHom (selectedOuterField S) e = e.1 := by
  apply MulOpposite.unop_injective
  simp [inverseOpHom, selectedOuterField]

/-- The semidirect carrier generated by the group and the selected outer
involution. -/
abbrev SelectedOuterAmbient
    (S : Fi24ThreeBlockSource (k := k) (X := X)) :=
  X ⋊[selectedOuterField S] SelectedOuterGroup S

/-- The group generated by the selected involution has cardinality at most
two.  Nontriviality of the chosen outer class is not needed for this bound. -/
theorem selectedOuterGroup_card_le_two
    (S : Fi24ThreeBlockSource (k := k) (X := X)) :
    Nat.card (SelectedOuterGroup S) ≤ 2 := by
  rw [Nat.card_zpowers]
  exact orderOf_le_of_pow_eq_one zero_lt_two
    (by simpa [pow_two] using S.outer_square)

variable {K : Type u}
variable [Field K] [CharP k 3] [IsAlgClosed k] [CharZero K]

/-- The remaining structural identification of the kernel of the literal
outer-class map with the inner automorphisms.  This is an external carrier
match, not a consequence of the order-two calculation. -/
structure C2OuterInnerKernelSource
    (iota : PrimeRegularRootEmbedding 3 k K X)
    (S : Fi24ThreeBlockSource (k := k) (X := X))
    (Outer : C2OuterActionSource iota S) : Prop where
  kernel_eq_inner :
    Outer.outerClass.ker =
      (RepresentationWeight.innerInverseOpHom (G := X)).range

/-- The restriction of the outer-class map to the chosen cyclic subgroup. -/
def selectedOuterClassHom
    (iota : PrimeRegularRootEmbedding 3 k K X)
    (S : Fi24ThreeBlockSource (k := k) (X := X))
    (Outer : C2OuterActionSource iota S) :
    SelectedOuterGroup S →* Equiv.Perm (Fin 2) :=
  Outer.outerClass.comp (inverseOpHom (selectedOuterField S))

/-- The chosen outer class forces the selected cyclic subgroup to have
exactly two elements. -/
theorem selectedOuterGroup_card
    (iota : PrimeRegularRootEmbedding 3 k K X)
    (S : Fi24ThreeBlockSource (k := k) (X := X))
    (Outer : C2OuterActionSource iota S) :
    Nat.card (SelectedOuterGroup S) = 2 := by
  rw [Nat.card_zpowers]
  apply orderOf_eq_prime (p := 2)
  · simpa [pow_two] using S.outer_square
  · intro houter
    apply Outer.selectedOuter_nontrivial
    rw [houter, map_one]

/-- The outer-class map is faithful on the selected subgroup. -/
theorem selectedOuterClassHom_injective
    (iota : PrimeRegularRootEmbedding 3 k K X)
    (S : Fi24ThreeBlockSource (k := k) (X := X))
    (Outer : C2OuterActionSource iota S) :
    Function.Injective (selectedOuterClassHom iota S Outer) := by
  letI : Fact (Nat.card (SelectedOuterGroup S)).Prime :=
    ⟨by rw [selectedOuterGroup_card iota S Outer]
        exact Nat.prime_two⟩
  have hkernel :
      (selectedOuterClassHom iota S Outer).ker = ⊥ := by
    rcases (selectedOuterClassHom iota S Outer).ker.eq_bot_or_eq_top_of_prime_card
      with hbot | htop
    · exact hbot
    · exfalso
      let generator : SelectedOuterGroup S :=
        ⟨S.outer, Subgroup.mem_zpowers S.outer⟩
      have hmem : generator ∈ (selectedOuterClassHom iota S Outer).ker := by
        rw [htop]
        exact Subgroup.mem_top generator
      have himage : Outer.outerClass S.outer = 1 := by
        simpa [generator, selectedOuterClassHom, MonoidHom.mem_ker] using hmem
      exact Outer.selectedOuter_nontrivial himage
  exact (MonoidHom.ker_eq_bot_iff (selectedOuterClassHom iota S Outer)).mp
    hkernel

/-- Every opposite automorphism is a product of an inner class and an
element of the selected outer subgroup, once the kernel of the outer-class
map has been identified with the inner classes. -/
theorem exists_inner_mul_selectedOuter
    (iota : PrimeRegularRootEmbedding 3 k K X)
    (S : Fi24ThreeBlockSource (k := k) (X := X))
    (Outer : C2OuterActionSource iota S)
    (Kernel : C2OuterInnerKernelSource iota S Outer)
    (alpha : (MulAut X)ᵐᵒᵖ) :
    ∃ x : X, ∃ e : SelectedOuterGroup S,
      RepresentationWeight.innerInverseOpHom x *
          inverseOpHom (selectedOuterField S) e = alpha := by
  by_cases halpha : Outer.outerClass alpha = 1
  · have hmem : alpha ∈ Outer.outerClass.ker := halpha
    rw [Kernel.kernel_eq_inner] at hmem
    rcases hmem with ⟨x, hx⟩
    refine ⟨x, 1, ?_⟩
    simpa using hx
  · have hclass : Outer.outerClass alpha = Outer.outerClass S.outer := by
      have hcard :
          Fintype.card {r : Equiv.Perm (Fin 2) // r ≠ 1} = 1 := by
        decide
      obtain ⟨r, hr⟩ := Fintype.card_eq_one_iff.mp hcard
      exact congrArg Subtype.val
        ((hr ⟨Outer.outerClass alpha, halpha⟩).trans
          (hr ⟨Outer.outerClass S.outer,
            Outer.selectedOuter_nontrivial⟩).symm)
    let delta : (MulAut X)ᵐᵒᵖ := alpha * S.outer⁻¹
    have hdelta : delta ∈ Outer.outerClass.ker := by
      change Outer.outerClass delta = 1
      simp only [delta, map_mul, map_inv, hclass, mul_inv_cancel]
    rw [Kernel.kernel_eq_inner] at hdelta
    rcases hdelta with ⟨x, hx⟩
    let generator : SelectedOuterGroup S :=
      ⟨S.outer, Subgroup.mem_zpowers S.outer⟩
    refine ⟨x, generator, ?_⟩
    rw [inverseOpHom_selectedOuterField]
    change RepresentationWeight.innerInverseOpHom x * S.outer = alpha
    calc
      RepresentationWeight.innerInverseOpHom x * S.outer =
          delta * S.outer := congrArg (fun beta ↦ beta * S.outer) hx
      _ = alpha := by simp [delta]

/-- The selected semidirect presentation, expressed on the opposite
automorphism carrier used by the right action. -/
def selectedOuterOpCover
    (S : Fi24ThreeBlockSource (k := k) (X := X)) :
    SelectedOuterAmbient S →* (MulAut X)ᵐᵒᵖ :=
  inverseOpHom (semidirectToMulAut (selectedOuterField S))

@[simp]
theorem selectedOuterOpCover_inl
    (S : Fi24ThreeBlockSource (k := k) (X := X)) (x : X) :
    selectedOuterOpCover S (SemidirectProduct.inl x) =
      RepresentationWeight.innerInverseOpHom x := by
  apply MulOpposite.unop_injective
  simp [selectedOuterOpCover, inverseOpHom,
    RepresentationWeight.innerInverseOpHom]

@[simp]
theorem selectedOuterOpCover_inr
    (S : Fi24ThreeBlockSource (k := k) (X := X))
    (e : SelectedOuterGroup S) :
    selectedOuterOpCover S (SemidirectProduct.inr e) = e.1 := by
  apply MulOpposite.unop_injective
  change
    semidirectToMulAut (selectedOuterField S)
        (SemidirectProduct.inr e)⁻¹ = e.1.unop
  rw [map_inv, semidirectToMulAut_inr]
  simp [selectedOuterField]

/-- The opposite cover separates into its inner and selected outer factors. -/
theorem selectedOuterOpCover_apply
    (S : Fi24ThreeBlockSource (k := k) (X := X))
    (g : SelectedOuterAmbient S) :
    selectedOuterOpCover S g =
      RepresentationWeight.innerInverseOpHom g.left * g.right.1 := by
  calc
    selectedOuterOpCover S g =
        selectedOuterOpCover S
          (SemidirectProduct.inl g.left * SemidirectProduct.inr g.right) :=
      congrArg (selectedOuterOpCover S)
        (SemidirectProduct.inl_left_mul_inr_right g).symm
    _ = RepresentationWeight.innerInverseOpHom g.left * g.right.1 := by
      rw [map_mul, selectedOuterOpCover_inl, selectedOuterOpCover_inr]

/-- The inner-kernel identification makes the selected semidirect
presentation surjective on the opposite automorphism carrier. -/
theorem selectedOuterOpCover_surjective
    (iota : PrimeRegularRootEmbedding 3 k K X)
    (S : Fi24ThreeBlockSource (k := k) (X := X))
    (Outer : C2OuterActionSource iota S)
    (Kernel : C2OuterInnerKernelSource iota S Outer) :
    Function.Surjective (selectedOuterOpCover S) := by
  intro alpha
  rcases exists_inner_mul_selectedOuter iota S Outer Kernel alpha with
    ⟨x, e, hfactor⟩
  refine ⟨SemidirectProduct.inl x * SemidirectProduct.inr e, ?_⟩
  rw [map_mul, selectedOuterOpCover_inl, selectedOuterOpCover_inr]
  exact hfactor

/-- The corresponding homomorphism to the ordinary automorphism group is
surjective as well. -/
theorem selectedSemidirectToMulAut_surjective
    (iota : PrimeRegularRootEmbedding 3 k K X)
    (S : Fi24ThreeBlockSource (k := k) (X := X))
    (Outer : C2OuterActionSource iota S)
    (Kernel : C2OuterInnerKernelSource iota S Outer) :
    Function.Surjective
      (semidirectToMulAut (selectedOuterField S)) := by
  intro alpha
  obtain ⟨g, hg⟩ := selectedOuterOpCover_surjective
    iota S Outer Kernel (MulOpposite.op alpha⁻¹)
  refine ⟨g, ?_⟩
  have h := congrArg
    (fun beta : (MulAut X)ᵐᵒᵖ ↦ beta.unop⁻¹) hg
  simpa [selectedOuterOpCover, inverseOpHom] using h

/-- Centrelessness makes the selected semidirect presentation faithful. -/
theorem selectedSemidirectToMulAut_eq_one
    (iota : PrimeRegularRootEmbedding 3 k K X)
    (S : Fi24ThreeBlockSource (k := k) (X := X))
    (Outer : C2OuterActionSource iota S)
    (Kernel : C2OuterInnerKernelSource iota S Outer)
    (hcenter : Subgroup.center X = ⊥)
    (g : SelectedOuterAmbient S)
    (hg : semidirectToMulAut (selectedOuterField S) g = 1) :
    g = 1 := by
  have hcover : selectedOuterOpCover S g = 1 := by
    simp [selectedOuterOpCover, inverseOpHom, hg]
  have hinnerMem :
      RepresentationWeight.innerInverseOpHom g.left ∈
        Outer.outerClass.ker := by
    rw [Kernel.kernel_eq_inner]
    exact ⟨g.left, rfl⟩
  have hinnerClass :
      Outer.outerClass
        (RepresentationWeight.innerInverseOpHom g.left) = 1 :=
    hinnerMem
  have hrightClass :
      selectedOuterClassHom iota S Outer g.right = 1 := by
    have hmap := congrArg Outer.outerClass hcover
    rw [selectedOuterOpCover_apply, map_mul, hinnerClass, one_mul,
      map_one] at hmap
    simpa [selectedOuterClassHom] using hmap
  have hright : g.right = 1 := by
    apply selectedOuterClassHom_injective iota S Outer
    simpa using hrightClass
  have hconj : MulAut.conj g.left = 1 := by
    rw [← SemidirectProduct.inl_left_mul_inr_right g, map_mul,
      semidirectToMulAut_inl, semidirectToMulAut_inr, hright,
      map_one, mul_one] at hg
    exact hg
  have hleftCenter : g.left ∈ Subgroup.center X := by
    rw [Subgroup.mem_center_iff]
    intro y
    have hy := DFunLike.congr_fun hconj y
    change g.left * y * g.left⁻¹ = y at hy
    calc
      y * g.left = (g.left * y * g.left⁻¹) * g.left :=
        congrArg (fun z ↦ z * g.left) hy.symm
      _ = g.left * y := by group
  have hleft : g.left = 1 := by
    rw [hcenter] at hleftCenter
    simpa using hleftCenter
  apply SemidirectProduct.ext
  · exact hleft
  · exact hright

/-- The selected semidirect presentation is injective for a centreless
group. -/
theorem selectedSemidirectToMulAut_injective
    (iota : PrimeRegularRootEmbedding 3 k K X)
    (S : Fi24ThreeBlockSource (k := k) (X := X))
    (Outer : C2OuterActionSource iota S)
    (Kernel : C2OuterInnerKernelSource iota S Outer)
    (hcenter : Subgroup.center X = ⊥) :
    Function.Injective
      (semidirectToMulAut (selectedOuterField S)) := by
  intro a b hab
  apply mul_inv_eq_one.mp
  apply selectedSemidirectToMulAut_eq_one iota S Outer Kernel hcenter
  rw [map_mul, map_inv, hab, mul_inv_cancel]

/-- Under the explicit inner-kernel and centreless hypotheses, the selected
semidirect presentation is exactly the full automorphism group. -/
theorem selectedSemidirectToMulAut_bijective
    (iota : PrimeRegularRootEmbedding 3 k K X)
    (S : Fi24ThreeBlockSource (k := k) (X := X))
    (Outer : C2OuterActionSource iota S)
    (Kernel : C2OuterInnerKernelSource iota S Outer)
    (hcenter : Subgroup.center X = ⊥) :
    Function.Bijective
      (semidirectToMulAut (selectedOuterField S)) :=
  ⟨selectedSemidirectToMulAut_injective iota S Outer Kernel hcenter,
    selectedSemidirectToMulAut_surjective iota S Outer Kernel⟩

variable {Y : Type u}

/-- Every stabiliser quotient by its embedded inner stabiliser has
cardinality at most two for the selected outer action. -/
theorem selectedStabilizerQuotient_card_le_two
    (S : Fi24ThreeBlockSource (k := k) (X := X))
    [MulAction (SelectedOuterAmbient S) Y]
    (y : Y) :
    Nat.card
      (semidirectStabilizer (phi := selectedOuterField S) y ⧸
        embeddedHStabilizer (phi := selectedOuterField S) y) ≤ 2 := by
  calc
    Nat.card
        (semidirectStabilizer (phi := selectedOuterField S) y ⧸
          embeddedHStabilizer (phi := selectedOuterField S) y) ≤
      Nat.card (SelectedOuterGroup S) :=
        Nat.card_le_card_of_injective
          (stabilizerQuotientEmbedding (phi := selectedOuterField S) y)
          (stabilizerQuotientEmbedding_injective
            (phi := selectedOuterField S) y)
    _ ≤ 2 := selectedOuterGroup_card_le_two S

/-- There is no proper subgroup strictly between the embedded inner
stabiliser and the full stabiliser for the selected outer action. -/
theorem intermediate_eq_embedded_or_top
    (S : Fi24ThreeBlockSource (k := k) (X := X))
    [MulAction (SelectedOuterAmbient S) Y]
    (y : Y)
    (J : Subgroup
      (semidirectStabilizer (phi := selectedOuterField S) y))
    (hbase : embeddedHStabilizer
      (phi := selectedOuterField S) y ≤ J) :
    J = embeddedHStabilizer (phi := selectedOuterField S) y ∨ J = ⊤ :=
  subgroup_eq_base_or_top_of_quotient_card_le_two
    (embeddedHStabilizer (phi := selectedOuterField S) y)
    (selectedStabilizerQuotient_card_le_two S y) J hbase

end ModularRep.PaperProofs.SporadicFi24SelectedOuterC2


/-
This file is part of ModularRep, the Lean companion to
Baoyu Zhang (2026), "On the inductive blockwise Alperin weight condition
for type B and type C".

The formalisation checks selected arguments under explicit external
assumptions. See FORMALISATION_GUIDE.md in the package root.
-/
