import Mathlib.Tactic.FinCases
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks00
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks05
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks10
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks15
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks20
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks25
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks30
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks35
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks40
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks45
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks50
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks55
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks60
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks65
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks70
namespace ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulCompleteColumnChecks
open SporadicFi24P3Definition44NamedCarrierFaithfulFullColumnData

theorem columnChecks : ColumnChecks := by
  intro r
  fin_cases r
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks00.column_row_0
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks00.column_row_1
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks00.column_row_2
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks00.column_row_3
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks00.column_row_4
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks05.column_row_5
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks05.column_row_6
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks05.column_row_7
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks05.column_row_8
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks05.column_row_9
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks10.column_row_10
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks10.column_row_11
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks10.column_row_12
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks10.column_row_13
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks10.column_row_14
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks15.column_row_15
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks15.column_row_16
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks15.column_row_17
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks15.column_row_18
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks15.column_row_19
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks20.column_row_20
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks20.column_row_21
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks20.column_row_22
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks20.column_row_23
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks20.column_row_24
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks25.column_row_25
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks25.column_row_26
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks25.column_row_27
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks25.column_row_28
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks25.column_row_29
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks30.column_row_30
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks30.column_row_31
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks30.column_row_32
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks30.column_row_33
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks30.column_row_34
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks35.column_row_35
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks35.column_row_36
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks35.column_row_37
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks35.column_row_38
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks35.column_row_39
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks40.column_row_40
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks40.column_row_41
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks40.column_row_42
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks40.column_row_43
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks40.column_row_44
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks45.column_row_45
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks45.column_row_46
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks45.column_row_47
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks45.column_row_48
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks45.column_row_49
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks50.column_row_50
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks50.column_row_51
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks50.column_row_52
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks50.column_row_53
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks50.column_row_54
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks55.column_row_55
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks55.column_row_56
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks55.column_row_57
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks55.column_row_58
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks55.column_row_59
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks60.column_row_60
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks60.column_row_61
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks60.column_row_62
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks60.column_row_63
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks60.column_row_64
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks65.column_row_65
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks65.column_row_66
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks65.column_row_67
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks65.column_row_68
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks65.column_row_69
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks70.column_row_70
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks70.column_row_71
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks70.column_row_72
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulColumnChecks70.column_row_73
end ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulCompleteColumnChecks


/-
This file is part of ModularRep, the Lean companion to
Baoyu Zhang (2026), "On the inductive blockwise Alperin weight condition
for type B and type C".

The formalisation checks selected arguments under explicit external
assumptions. See FORMALISATION_GUIDE.md in the package root.
-/
