import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulIntegerEvaluation
import Mathlib.Tactic.FinCases
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks00
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks05
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks10
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks15
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks20
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks00
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks05
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks10
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks15
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks20
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks25
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks30
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks35
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks40
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks45
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks50
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks55
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks60
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks65
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks70

namespace ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulCompleteIntegerChecks
open SporadicFi24P3Definition44NamedCarrierFaithfulIntegerEvaluation

theorem inverseChecks : InverseChecks := by
  intro a
  fin_cases a
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks00.inverse_row_0
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks00.inverse_row_1
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks00.inverse_row_2
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks00.inverse_row_3
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks00.inverse_row_4
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks05.inverse_row_5
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks05.inverse_row_6
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks05.inverse_row_7
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks05.inverse_row_8
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks05.inverse_row_9
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks10.inverse_row_10
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks10.inverse_row_11
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks10.inverse_row_12
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks10.inverse_row_13
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks10.inverse_row_14
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks15.inverse_row_15
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks15.inverse_row_16
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks15.inverse_row_17
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks15.inverse_row_18
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks15.inverse_row_19
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks20.inverse_row_20
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks20.inverse_row_21
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks20.inverse_row_22
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks20.inverse_row_23
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks20.inverse_row_24

theorem constantChecks : ConstantChecks := by
  intro a
  fin_cases a
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks00.constant_row_0
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks00.constant_row_1
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks00.constant_row_2
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks00.constant_row_3
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks00.constant_row_4
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks05.constant_row_5
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks05.constant_row_6
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks05.constant_row_7
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks05.constant_row_8
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks05.constant_row_9
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks10.constant_row_10
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks10.constant_row_11
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks10.constant_row_12
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks10.constant_row_13
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks10.constant_row_14
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks15.constant_row_15
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks15.constant_row_16
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks15.constant_row_17
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks15.constant_row_18
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks15.constant_row_19
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks20.constant_row_20
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks20.constant_row_21
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks20.constant_row_22
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks20.constant_row_23
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulInverseChecks20.constant_row_24

theorem reconstructionChecks : ReconstructionChecks := by
  intro a
  fin_cases a
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks00.reconstruction_row_0
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks00.reconstruction_row_1
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks00.reconstruction_row_2
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks00.reconstruction_row_3
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks00.reconstruction_row_4
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks05.reconstruction_row_5
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks05.reconstruction_row_6
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks05.reconstruction_row_7
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks05.reconstruction_row_8
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks05.reconstruction_row_9
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks10.reconstruction_row_10
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks10.reconstruction_row_11
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks10.reconstruction_row_12
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks10.reconstruction_row_13
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks10.reconstruction_row_14
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks15.reconstruction_row_15
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks15.reconstruction_row_16
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks15.reconstruction_row_17
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks15.reconstruction_row_18
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks15.reconstruction_row_19
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks20.reconstruction_row_20
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks20.reconstruction_row_21
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks20.reconstruction_row_22
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks20.reconstruction_row_23
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks20.reconstruction_row_24
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks25.reconstruction_row_25
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks25.reconstruction_row_26
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks25.reconstruction_row_27
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks25.reconstruction_row_28
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks25.reconstruction_row_29
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks30.reconstruction_row_30
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks30.reconstruction_row_31
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks30.reconstruction_row_32
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks30.reconstruction_row_33
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks30.reconstruction_row_34
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks35.reconstruction_row_35
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks35.reconstruction_row_36
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks35.reconstruction_row_37
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks35.reconstruction_row_38
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks35.reconstruction_row_39
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks40.reconstruction_row_40
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks40.reconstruction_row_41
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks40.reconstruction_row_42
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks40.reconstruction_row_43
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks40.reconstruction_row_44
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks45.reconstruction_row_45
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks45.reconstruction_row_46
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks45.reconstruction_row_47
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks45.reconstruction_row_48
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks45.reconstruction_row_49
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks50.reconstruction_row_50
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks50.reconstruction_row_51
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks50.reconstruction_row_52
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks50.reconstruction_row_53
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks50.reconstruction_row_54
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks55.reconstruction_row_55
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks55.reconstruction_row_56
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks55.reconstruction_row_57
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks55.reconstruction_row_58
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks55.reconstruction_row_59
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks60.reconstruction_row_60
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks60.reconstruction_row_61
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks60.reconstruction_row_62
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks60.reconstruction_row_63
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks60.reconstruction_row_64
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks65.reconstruction_row_65
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks65.reconstruction_row_66
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks65.reconstruction_row_67
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks65.reconstruction_row_68
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks65.reconstruction_row_69
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks70.reconstruction_row_70
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks70.reconstruction_row_71
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks70.reconstruction_row_72
  · exact SporadicFi24P3Definition44NamedCarrierFaithfulReconstructionChecks70.reconstruction_row_73

end ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierFaithfulCompleteIntegerChecks


/-
This file is part of ModularRep, the Lean companion to
Baoyu Zhang (2026), "On the inductive blockwise Alperin weight condition
for type B and type C".

The formalisation checks selected arguments under explicit external
assumptions. See FORMALISATION_GUIDE.md in the package root.
-/
