import ModularRep.CyclicOuterBrauerExtension

/-!
# The selected square-one outer automorphism carrier

Only the chosen opposite automorphism and its square relation are retained
here.  The identity is allowed.  Nontriviality of its outer class, literal
block data, and the presentation of the full automorphism group are separate
inputs in higher modules.
-/

noncomputable section

namespace ModularRep.PaperProofs.SporadicFi24SelectedOuterInvolutionCarrier

open ModularRep.ManuscriptVerification.CyclicOuterBAW
open ModularRep.PaperProofs.CyclicOuterLemma37Concrete

universe u

/-- A selected opposite automorphism whose square is the identity. -/
structure SelectedOuterInvolutionCarrier
    (X : Type u) [Group X] where
  outer : (MulAut X)ᵐᵒᵖ
  outer_square : outer * outer = 1

variable {X : Type u} [Group X] [Finite X]

noncomputable local instance mulAutFinite : Finite (MulAut X) :=
  Finite.of_injective (fun alpha : MulAut X ↦ (alpha : X → X))
    DFunLike.coe_injective

/-- The cyclic subgroup generated by the selected opposite automorphism. -/
abbrev SelectedOuterGroup (S : SelectedOuterInvolutionCarrier X) :=
  Subgroup.zpowers S.outer

noncomputable local instance selectedOuterGroupFinite
    (S : SelectedOuterInvolutionCarrier X) :
    Finite (SelectedOuterGroup S) :=
  Finite.of_injective
    (fun e : SelectedOuterGroup S ↦ (e.1.unop : X → X))
    (fun _a _b h ↦ Subtype.ext
      (MulOpposite.unop_injective (DFunLike.coe_injective h)))

/-- Convert the selected opposite subgroup to automorphisms of `X`. -/
def selectedOuterField (S : SelectedOuterInvolutionCarrier X) :
    SelectedOuterGroup S →* MulAut X where
  toFun e := e.1.unop⁻¹
  map_one' := by simp
  map_mul' a b := by simp

@[simp]
theorem inverseOpHom_selectedOuterField
    (S : SelectedOuterInvolutionCarrier X)
    (e : SelectedOuterGroup S) :
    inverseOpHom (selectedOuterField S) e = e.1 := by
  apply MulOpposite.unop_injective
  simp [inverseOpHom, selectedOuterField]

/-- The semidirect carrier generated by `X` and the selected outer action. -/
abbrev SelectedOuterAmbient (S : SelectedOuterInvolutionCarrier X) :=
  X ⋊[selectedOuterField S] SelectedOuterGroup S

/-- The selected cyclic subgroup has cardinality at most two. -/
theorem selectedOuterGroup_card_le_two
    (S : SelectedOuterInvolutionCarrier X) :
    Nat.card (SelectedOuterGroup S) ≤ 2 := by
  rw [Nat.card_zpowers]
  exact orderOf_le_of_pow_eq_one zero_lt_two
    (by simpa [pow_two] using S.outer_square)

end ModularRep.PaperProofs.SporadicFi24SelectedOuterInvolutionCarrier


/-
This file is part of ModularRep, the Lean companion to
Baoyu Zhang (2026), "On the inductive blockwise Alperin weight condition
for type B and type C".

The formalisation checks selected arguments under explicit external
assumptions. See FORMALISATION_GUIDE.md in the package root.
-/
