import ModularRep.PaperProofs.TypeBComponentCycleNormalization
import ModularRep.PaperProofs.TypeBReturnCoordinateAction

/-!
# The actual return subgroup after monomial cycle normalization

The normalization uses the inverse generator, because the manuscript's
character action is a right pullback action. Consequently the computed
wrap is the restriction of the NEGATIVE full return. The actual subgroup
below is generated by the positive full power: its generator acts by the
inverse of the computed wrap, and its inverse acts by the wrap itself.

All coordinate equations are deduced from the original monomial action.
The homomorphism on the literal `zpowers` subgroup is the unique coordinate
restriction of the transported ambient action. No normalized generator
equation, local normalizing equation, character fixedness, or root of the
return is an external input.
-/

noncomputable section

namespace ModularRep.PaperProofs.TypeBComponentReturnRestriction

open ModularRep.PaperProofs.TypeBComponentCycleNormalization
open ModularRep.PaperProofs.TypeBReturnCoordinateAction
open ModularRep.PaperProofs.TypeBRegularLeviCharacterActionAdapter

universe u v w

section ReturnGroup

variable {C : Type u} (m : C → ℕ) {E : Type w} [Group E] (tau : E)

/-- The actual positive full-return subgroup of the same ambient group. -/
abbrev ReturnGroup (c : C) := Subgroup.zpowers (tau ^ (m c + 1))

/-- Its literal positive full-return generator. -/
def returnElement (c : C) : ReturnGroup m tau c :=
  ⟨tau ^ (m c + 1), Subgroup.mem_zpowers _⟩

end ReturnGroup

section Restriction

variable {C : Type u} (m : C → ℕ)
variable (H : Index m → Type v) [∀ i, Group (H i)]
variable (S : CycleCoordinates m H)
variable {E : Type w} [Group E]
variable (outer : E →* MulAut (Original m H)) (tau : E)
variable (h : MonomialAction m H S (outer tau⁻¹))

include h in
/-- The computed wrap is the negative actual full return. -/
theorem inverse_generator_coordinate (c : C) (g : Normalized m H) :
    normalizedAction m H S outer ((tau ^ (m c + 1))⁻¹) g (first m c) =
      fullReturn m H S c (g (first m c)) := by
  have hp := normalized_full_power m H S h c g
  have heq : normalizedAut m H S (outer tau⁻¹) ^ (m c + 1) =
      normalizedAction m H S outer ((tau ^ (m c + 1))⁻¹) := by
    change (normalizedAction m H S outer tau⁻¹) ^ (m c + 1) = _
    simp only [map_inv, map_pow, inv_pow]
  rw [heq] at hp
  exact hp

include h in
/-- The positive actual full return restricts to the inverse of the wrap. -/
theorem positive_generator_coordinate (c : C) (g : Normalized m H) :
    normalizedAction m H S outer (tau ^ (m c + 1)) g (first m c) =
      (fullReturn m H S c)⁻¹ (g (first m c)) := by
  have hp := inverse_generator_coordinate m H S outer tau h c
    (normalizedAction m H S outer (tau ^ (m c + 1)) g)
  have hc : g (first m c) = fullReturn m H S c
      (normalizedAction m H S outer (tau ^ (m c + 1)) g (first m c)) := by
    simpa only [map_inv, MulAut.inv_apply_self] using hp
  have hi := congrArg (fullReturn m H S c).symm hc
  simpa only [MulEquiv.symm_apply_apply, MulAut.inv_apply] using hi.symm

/-- Restriction of the actual transported action to the actual positive
return subgroup. The generator equation has already been proved. -/
def returnAction (c : C) : ReturnGroup m tau c →* MulAut (Base m H c) :=
  returnHom (fun i : Index m => Base m H i.1)
    (normalizedAction m H S outer) (tau ^ (m c + 1)) (first m c)
    (fullReturn m H S c)⁻¹ (positive_generator_coordinate m H S outer tau h c)

/-- The constructed action agrees with the ambient action on every return
element, not only on the generator. -/
theorem return_coordinate (c : C) (r : ReturnGroup m tau c)
    (g : Normalized m H) :
    normalizedAction m H S outer r.1 g (first m c) =
      returnAction m H S outer tau h c r (g (first m c)) :=
  returnHom_value (fun i : Index m => Base m H i.1)
    (normalizedAction m H S outer) (tau ^ (m c + 1)) (first m c)
    (fullReturn m H S c)⁻¹ (positive_generator_coordinate m H S outer tau h c) r g

/-- The positive generator is the inverse wrap, with the sign forced by
the manuscript's right-action convention. -/
theorem returnAction_generator (c : C) :
    returnAction m H S outer tau h c (returnElement m tau c) =
      (fullReturn m H S c)⁻¹ :=
  returnHom_generator_eq (fun i : Index m => Base m H i.1)
    (normalizedAction m H S outer) (tau ^ (m c + 1)) (first m c)
    (fullReturn m H S c)⁻¹ (positive_generator_coordinate m H S outer tau h c)

/-- The inverse of the literal positive generator is the computed wrap. -/
theorem returnAction_inverse_generator (c : C) :
    returnAction m H S outer tau h c (returnElement m tau c)⁻¹ =
      fullReturn m H S c := by
  rw [map_inv, returnAction_generator, inv_inv]

/-- The return action also has an exact formula on the ORIGINAL product:
the constructed coordinate transport is the identity at the base. -/
theorem original_return_coordinate (c : C) (r : ReturnGroup m tau c)
    (g : Original m H) :
    outer r.1 g (first m c) =
      returnAction m H S outer tau h c r (g (first m c)) := by
  have hv := return_coordinate m H S outer tau h c r (productEquiv m H S g)
  change productEquiv m H S
      (outer r.1 ((productEquiv m H S).symm (productEquiv m H S g)))
      (first m c) = _ at hv
  rw [MulEquiv.symm_apply_apply] at hv
  exact hv

include h in
/-- This is the source endpoint's successor equation, now a deduction
from the original varying-factor monomial coordinates. -/
theorem generator_succ (g : Normalized m H) (c : C) (j : Fin (m c)) :
    normalizedAction m H S outer tau⁻¹ g ⟨c, j.castSucc⟩ = g ⟨c, j.succ⟩ :=
  normalized_successor m H S h g c j

/-- This is the source endpoint's wrap equation, using the inverse of the
actual positive return generator rather than a postulated root. -/
theorem generator_first (g : Normalized m H) (c : C) :
    normalizedAction m H S outer tau⁻¹ g (last m c) =
      returnAction m H S outer tau h c (returnElement m tau c)⁻¹
        (g (first m c)) := by
  rw [returnAction_inverse_generator]
  exact normalized_wrap m H S h g c

end Restriction

section Compatibility

variable {C E : Type} (m : C → ℕ)
variable (H D : Index m → Type)
variable [∀ i, Group (H i)] [∀ i, Group (D i)] [Group E]
variable (SH : CycleCoordinates m H) (SD : CycleCoordinates m D)

/-- The two actual return restrictions preserve the original diagonal
action. The local normalization law follows from the original global law
and the proved coordinate restrictions, without an additional source. -/
theorem return_actions_compatible
    (diagonal : ∀ i, D i →* MulAut (H i))
    (outer : E →* MulAut (Original m H))
    (phi : E →* MulAut (Original m D)) (tau : E)
    (hH : MonomialAction m H SH (outer tau⁻¹))
    (hD : MonomialAction m D SD (phi tau⁻¹))
    (normalises : AutomorphismSemidirectCompatible
      (coordinateMulAut H D diagonal) outer phi) (c : C) :
    AutomorphismSemidirectCompatible (diagonal (first m c))
      (returnAction m H SH outer tau hH c)
      (returnAction m D SD phi tau hD c) := by
  exact coordinateRestrictions_semidirectCompatible H D diagonal
    (outer.comp (Subgroup.zpowers (tau ^ (m c + 1))).subtype)
    (phi.comp (Subgroup.zpowers (tau ^ (m c + 1))).subtype)
    (first m c) (returnAction m H SH outer tau hH c)
    (returnAction m D SD phi tau hD c)
    (fun r d => normalises r.1 d)
    (fun r g => original_return_coordinate m H SH outer tau hH c r g)
    (fun r d => original_return_coordinate m D SD phi tau hD c r d)

end Compatibility

end ModularRep.PaperProofs.TypeBComponentReturnRestriction


/-
This file is part of ModularRep, the Lean companion to
Baoyu Zhang (2026), "On the inductive blockwise Alperin weight condition
for type B and type C".

The formalisation checks selected arguments under explicit external
assumptions. See FORMALISATION_GUIDE.md in the package root.
-/
