import ModularRep.PaperProofs.TypeBOddPrimesProposition44Actual
import ModularRep.PaperProofs.EvenFieldFLZSourceConditions
import ModularRep.NavarroCoveringBrauerExtension
import ModularRep.PrimitiveBlockAutomorphism
import ModularRep.BrauerCharacterExtensionBridge
import ModularRep.PaperProofs.TypeBWeightCoveringSource
import ModularRep.PaperProofs.TypeBFixedRootDefinitionFamily
import Mathlib.GroupTheory.Commutator.Basic

/-!
# The all-blocks domain of the Brough--Spaeth criterion

This file defines hypotheses only, on arbitrary finite groups `G <= M`
and the actual semidirect product `M semidirect E`. The primary statement
is Brough--Spaeth, Theorem 4.5, local source label `NewIndBAWCond`, not
the earlier non-blockwise criterion. FLZ Theorem 2.1, pp. 536--537, uses
the cyclic specialization. We retain the original ordinary and Brauer
extension clauses rather than silently omit them.

The selected family is every primitive block of `G`. Thus all blocks of
`M` occur upstairs and the automorphism group is the full actual group.
We specialize the permitted acting group to the abelian alternative and
require the whole outer automorphism group to be abelian. Both are stronger
than the relevant alternatives of the published theorem. Its last displayed
`J_G` clause is typed on the upstairs Brauer domain, as required by its
formula and proof (the local TeX prints the downstairs family there).

No source theorem, output relation, matching downstairs, character-triple
witness, numbered-proposition predicate or iBAW assertion is introduced.
-/

noncomputable section

open scoped MonoidAlgebra Pointwise

namespace ModularRep.PaperProofs.TypeBCriterionHypotheses

open ModularRep FDRepSimpleClassKZero OrdinaryIrreducibleCharacter
open CyclicOuterLemma37Concrete EvenFieldFLZSourceConditions
open TypeCWeightTensorFieldAction
open TypeBSpecialCliffordActionAdapter

section NaturalAmbient

variable {M E : Type} [Group M] [Group E]
variable (G : Subgroup M) [G.Normal] (field : E →* MulAut M)

/-- The actual ambient group, before any structural source is applied. -/
abbrev Ambient := M ⋊[field] E

/-- A presentation of the natural action with its complete value formula.
There is no freedom to substitute a different action on `G`. -/
structure NaturalAction where
  hom : Ambient field →* MulAut G
  value : ∀ (a : Ambient field) (g : G),
    (hom a g : M) = a.left * field a.right g.1 * a.left⁻¹

/-- The fixed inclusion of the actual normal subgroup. -/
def baseEmbedding : G →* Ambient field :=
  SemidirectProduct.inl.comp G.subtype

def embeddedM : Subgroup (Ambient field) :=
  (SemidirectProduct.inl : M →* Ambient field).range

def embeddedE : Subgroup (Ambient field) :=
  (SemidirectProduct.inr : E →* Ambient field).range

def embeddedG : Subgroup (Ambient field) := (baseEmbedding G field).range

/-- `G E` is the actual subgroup generated by the two fixed inclusions. -/
def baseFieldGroup : Subgroup (Ambient field) :=
  embeddedG G field ⊔ embeddedE field

def embeddedCenter : Subgroup (Ambient field) :=
  (Subgroup.center M).map (SemidirectProduct.inl : M →* Ambient field)

/-- Actual inner automorphisms, not a separately named quotient carrier. -/
def innerAutomorphisms : Subgroup (MulAut G) :=
  (MulAut.conj : G →* MulAut G).range

instance innerAutomorphisms_normal : (innerAutomorphisms G).Normal where
  conj_mem _ ha β := by
    obtain ⟨g, rfl⟩ := ha
    refine ⟨β g, ?_⟩
    apply MulEquiv.ext
    intro x
    change β g * x * (β g)⁻¹ = β (g * β⁻¹ x * g⁻¹)
    simp only [map_mul, map_inv, MulAut.apply_inv_self]

abbrev OuterAutomorphism := MulAut G ⧸ innerAutomorphisms G

/-- The structural part of the all-blocks cyclic specialization. The
kernel and surjectivity refer to the SAME natural homomorphism. -/
structure Structural (action : NaturalAction G field) : Prop where
  derived : commutator M = G
  acting_abelian : IsMulCommutative E
  quotient_cyclic : IsCyclic (M ⧸ G)
  centralizer : Subgroup.centralizer (embeddedG G field : Set (Ambient field)) =
    embeddedCenter field
  natural_kernel : action.hom.ker = embeddedCenter field
  natural_surjective : Function.Surjective action.hom
  outer_abelian : IsMulCommutative (OuterAutomorphism G)

end NaturalAmbient

section LiteralCharacters

variable {ell : ℕ} {k K H T : Type}
variable [Field k] [Field K] [CharP k ell] [IsAlgClosed k] [CharZero K]
variable [Group H] [Finite H] [Group T]

/-- Extension of the actual representation affording the prescribed
Brauer character. The restriction equivalence is literal and fixes the
base root; no unrelated upstairs character convention is required. -/
def BrauerExtendsAlong (j : H →* T)
    (iota : PrimeRegularRootEmbedding ell k K H) (phi : IBr iota) : Prop :=
  ∃ V : FDRep k H, Representation.IsIrreducible V.ρ ∧
    phi.1 = Representation.brauerCharacterOfRootEmbedding V.ρ iota ∧
    ∃ rho : Representation k T V.V,
      Nonempty (Representation.Equiv (Representation.pullback rho j) V.ρ)

/-- Convert the existing cyclic-extension endpoint on a canonically
embedded base to the criterion's original base carrier. Both the root
and the representation are transported through the displayed equivalence;
this requires no extra extension or root-compatibility source. -/
theorem brauerExtendsAlong_of_embeddedRealisation [Finite T]
    (N : Subgroup T) [N.Normal] (e : H ≃* N)
    (iota : PrimeRegularRootEmbedding ell k K H) (phi : IBr iota)
    (V : FDRep k N) (hV : Representation.IsIrreducible V.ρ)
    (hcharacter : (IrreducibleBrauerCharacter.alongMulEquiv iota e phi).1 =
      Representation.brauerCharacterOfRootEmbedding V.ρ (iota.alongMulEquiv e))
    (extension : Representation.Extension N V.ρ) :
    BrauerExtendsAlong (N.subtype.comp e.toMonoidHom) iota phi := by
  refine ⟨FDRep.of (Representation.pullback V.ρ e.toMonoidHom),
    hV.pullback e.toMonoidHom e.surjective, ?_, extension.representation, ?_⟩
  · apply PrimeRegularClassFunction.ext
    intro x
    have h := congrArg
      (fun chi : PrimeRegularClassFunction K N ell =>
        chi (PrimeRegularElement.map e.toMonoidHom x)) hcharacter
    have hx : PrimeRegularElement.map e.symm.toMonoidHom
        (PrimeRegularElement.map e.toMonoidHom x) = x := by
      apply Subtype.ext
      exact e.symm_apply_apply x.1
    have hlift : (iota.alongMulEquiv e).lift = iota.lift :=
      funext (iota.alongMulEquiv_lift e)
    change phi.1 (PrimeRegularElement.map e.symm.toMonoidHom
      (PrimeRegularElement.map e.toMonoidHom x)) =
        ((V.ρ (e x.1)).charpoly.roots.map (iota.alongMulEquiv e).lift).sum at h
    rw [hx, hlift] at h
    exact h
  · exact ⟨extension.restrictionEquiv.pullback e.toMonoidHom⟩

end LiteralCharacters

section ActualStabilizers

variable {ell : ℕ} {k K M E : Type}
variable [Field k] [Field K] [CharP k ell] [IsAlgClosed k] [CharZero K]
variable [IsAlgClosed K]
variable [Group M] [Finite M] [Group E] [Finite E]
variable (G : Subgroup M) [G.Normal] (field : E →* MulAut M)
variable (action : NaturalAction G field)
variable (iotaG : PrimeRegularRootEmbedding ell k K G)

def brauerInertia (phi : IBr iotaG) : Subgroup (Ambient field) :=
  (MulAction.stabilizer (MulAut G)ᵐᵒᵖ phi).comap
    (CyclicOuterLemma37Concrete.inverseOpHom action.hom)

def weightClassInertia
    (W : CharacterWeight.ConjugacyClass (p := ell) (K := K) (G := G)) :
    Subgroup (Ambient field) :=
  (MulAction.stabilizer (MulAut G)ᵐᵒᵖ W).comap
    (CyclicOuterLemma37Concrete.inverseOpHom action.hom)

def rawInertia (W : CharacterWeight ell K G) : Subgroup (Ambient field) :=
  (MulAction.stabilizer (MulAut G)ᵐᵒᵖ
    (Quotient.mk'' W : CharacterWeight.IsoClass (p := ell) (K := K) (G := G))).comap
      (CyclicOuterLemma37Concrete.inverseOpHom action.hom)

def embeddedRadical (W : CharacterWeight ell K G) : Subgroup (Ambient field) :=
  W.subgroup.map (baseEmbedding G field)

/-- Retain the actual radical normalizer in the raw-pair inertia. -/
def rawNormalizerInertia (W : CharacterWeight ell K G) : Subgroup (Ambient field) :=
  rawInertia G field action W ⊓
    Subgroup.normalizer (embeddedRadical G field W : Set (Ambient field))

/-- Restrict an actual ambient inertia to one of the fixed ambient factors. -/
def factorInertia (I J : Subgroup (Ambient field)) : Subgroup (Ambient field) := I ⊓ J

def brauerMInertia (phi : IBr iotaG) : Subgroup M :=
  (brauerInertia G field action iotaG phi).comap SemidirectProduct.inl

def weightMInertia
    (W : CharacterWeight.ConjugacyClass (p := ell) (K := K) (G := G)) : Subgroup M :=
  (weightClassInertia G field action W).comap SemidirectProduct.inl

/-- The exact product in the constituent clause. -/
def BrauerFactorization (phi : IBr iotaG) : Prop :=
  (brauerInertia G field action iotaG phi : Set (Ambient field)) =
    (factorInertia field (brauerInertia G field action iotaG phi)
      (embeddedM field) : Set (Ambient field)) *
    (factorInertia field (brauerInertia G field action iotaG phi)
      (embeddedE field) : Set (Ambient field))

/-- The stronger raw-normalizer product used in FLZ Theorem 2.1(4).
The second factor is in the literal subgroup `G E`. -/
def RawNormalizerFactorization (W : CharacterWeight ell K G) : Prop :=
  (rawNormalizerInertia G field action W : Set (Ambient field)) =
    (factorInertia field (rawNormalizerInertia G field action W)
      (embeddedM field) : Set (Ambient field)) *
    (factorInertia field (rawNormalizerInertia G field action W)
      (baseFieldGroup G field) : Set (Ambient field))

/-- The original Brough--Spaeth class-inertia clause on this SAME raw
representative. It is retained separately from FLZ's raw-normalizer
formula, so no unchecked raw-to-class implication closes the domain. -/
def WeightClassFactorization (W : CharacterWeight ell K G) : Prop :=
  let c : CharacterWeight.ConjugacyClass (p := ell) (K := K) (G := G) :=
    Quotient.mk'' (Quotient.mk'' W : CharacterWeight.IsoClass (p := ell) (K := K) (G := G))
  (weightClassInertia G field action c : Set (Ambient field)) =
    (factorInertia field (weightClassInertia G field action c)
      (embeddedM field) : Set (Ambient field)) *
    (factorInertia field (weightClassInertia G field action c)
      (embeddedE field) : Set (Ambient field))

/-- The embedding in an extension is constrained pointwise to the actual
base inclusion. The target is a previously fixed literal inertia subgroup. -/
structure BrauerExtensionIn (phi : IBr iotaG) (I : Subgroup (Ambient field)) where
  inclusion : G →* I
  inclusion_value : ∀ g, (inclusion g : Ambient field) = baseEmbedding G field g
  witness : BrauerExtendsAlong inclusion iotaG phi

/-- An ordinary extension lives on the ACTUAL raw inertia quotient by R.
Its value on the ACTUAL base normalizer is the inflation of the given
quotient character. The inclusion and normality facts are geometry, not
an unspecified local extension carrier. -/
structure LocalOrdinaryExtension (W : CharacterWeight ell K G)
    (I : Subgroup (Ambient field)) where
  radical_le : embeddedRadical G field W ≤ I
  radical_normal : ((embeddedRadical G field W).subgroupOf I).Normal
  normalizerInclusion : Subgroup.normalizer (W.subgroup : Set G) →* I
  normalizerInclusion_value : ∀ x,
    (normalizerInclusion x : Ambient field) = baseEmbedding G field x.1
  character : letI := radical_normal
    Irr K (I ⧸ (embeddedRadical G field W).subgroupOf I)
  restriction : letI := radical_normal
    ∀ x : Subgroup.normalizer (W.subgroup : Set G),
      character (QuotientGroup.mk' ((embeddedRadical G field W).subgroupOf I)
        (normalizerInclusion x)) =
      W.localCharacter (QuotientGroup.mk'
        (W.subgroup.subgroupOf (Subgroup.normalizer (W.subgroup : Set G))) x)

/-- All-character extension is a convenient strengthening: it includes
every M-conjugate required by Theorem 4.5(iii), not only one constituent. -/
structure ExtensionClauses where
  brauer_M : ∀ phi : IBr iotaG,
    Nonempty (BrauerExtensionIn G field iotaG phi
      (brauerInertia G field action iotaG phi ⊓ embeddedM field))
  brauer_GE : ∀ phi : IBr iotaG,
    Nonempty (BrauerExtensionIn G field iotaG phi
      (brauerInertia G field action iotaG phi ⊓ baseFieldGroup G field))
  ordinary_M : ∀ W : CharacterWeight ell K G,
    Nonempty (LocalOrdinaryExtension G field W
      (rawNormalizerInertia G field action W ⊓ embeddedM field))
  ordinary_GE : ∀ W : CharacterWeight ell K G,
    Nonempty (LocalOrdinaryExtension G field W
      (rawNormalizerInertia G field action W ⊓ baseFieldGroup G field))

end ActualStabilizers

section HallAndBlocks

variable {ell : ℕ} {k K M : Type}
variable [Field k] [Field K] [CharP k ell] [IsAlgClosed k] [CharZero K]
variable [Group M] [Finite M]
variable (G : Subgroup M) [G.Normal]

local instance : Fintype M := Fintype.ofFinite _
local instance : Fintype G := Fintype.ofFinite _

/-- The Hall subgroup is in the literal quotient M/G. -/
structure HallData (ell : ℕ) where
  hall : Subgroup (M ⧸ G)
  order_primeTo : ell.Coprime (Nat.card hall)
  exponent : ℕ
  index : hall.index = ell ^ exponent

def HallData.preimage (hall : HallData G ell) : Subgroup M :=
  hall.hall.comap (QuotientGroup.mk' G)

variable [Fintype (LiteralPrimitiveBlock k M)]
variable [Fintype (LiteralPrimitiveBlock k G)]

/-- Both complete primitive block decompositions and the specified ambient
catalogues used by the two weight-block assignments. -/
structure BlockData where
  downstairs : BlockIdempotentDecomposition
    (fun b : LiteralPrimitiveBlock k G => b.1)
  upstairs : BlockIdempotentDecomposition
    (fun b : LiteralPrimitiveBlock k M => b.1)
  weightDownstairs : CharacterWeight.LocalBlockInductionSource
    (p := ell) (k := k) (K := K) (G := G) (Block := LiteralPrimitiveBlock k G)
  weightUpstairs : CharacterWeight.LocalBlockInductionSource
    (p := ell) (k := k) (K := K) (G := M) (Block := LiteralPrimitiveBlock k M)
  downstairs_idempotent : ∀ b : LiteralPrimitiveBlock k G,
    weightDownstairs.operations.ambientBlockData.blockIdempotent b = b.1
  upstairs_idempotent : ∀ b : LiteralPrimitiveBlock k M,
    weightUpstairs.operations.ambientBlockData.blockIdempotent b = b.1

end HallAndBlocks

section GlobalClauses

variable {ell : ℕ} {k K M E : Type}
variable [Field k] [Field K] [CharP k ell] [IsAlgClosed k] [CharZero K]
variable [IsAlgClosed K]
variable [Group M] [Finite M] [Group E] [Finite E]
variable (G : Subgroup M) [G.Normal] (field : E →* MulAut M)
variable (action : NaturalAction G field)
variable (iotaM : PrimeRegularRootEmbedding ell k K M)
variable (iotaG : PrimeRegularRootEmbedding ell k K G)

local instance : Fintype M := Fintype.ofFinite _
local instance : Fintype G := Fintype.ofFinite _

/-- The two fixed Brauer conventions agree on the actual subgroup's
roots. This is not implied by naming both carriers `IBr`. -/
def RootAgreement : Prop :=
  ∀ zeta : rootsOfUnity (primeRegularExponent ell G) k,
    iotaG.lift (((zeta : kˣ) : k)) = iotaM.lift (((zeta : kˣ) : k))

/-- Actual constituents, with actual ambient inertia factorization. No
arbitrary lies-over predicate or preselected constituent is an input. -/
def ConstituentClause : Prop :=
  ∀ Phi : IBr iotaM, ∃ phi : IBr iotaG,
    NavarroCoveringBrauerExtension.BrauerOccursInRestriction G iotaM iotaG Phi phi ∧
      BrauerFactorization G field action iotaG phi

/-- FLZ's normalizer-conjugate formulation, stronger than choosing one
representative per M-orbit in Theorem 4.5(iv). Its conjugating element and
twisted raw weight are computed in the actual ambient action. -/
def RawNormalizerClause : Prop :=
  ∀ W : CharacterWeight ell K G,
    ∃ m : M, m ∈ Subgroup.normalizer (W.subgroup.map G.subtype : Set M) ∧
      RawNormalizerFactorization G field action
        (W.rightTwist (action.hom (SemidirectProduct.inl m))⁻¹) ∧
      WeightClassFactorization G field action
        (W.rightTwist (action.hom (SemidirectProduct.inl m))⁻¹)

variable [Fintype (LiteralPrimitiveBlock k M)]
variable [Fintype (LiteralPrimitiveBlock k G)]
variable (blocks : BlockData (ell := ell) (k := k) (K := K) G)
variable (hinjM : IrreducibleBrauerCharacterInjectivity iotaM)
variable (hinvariant : TypeCConformalActionAdapter.FieldInvariantSubgroup.IsInvariant G field)
variable (D : TypeCConformalActionAdapter.OrdinaryReductionEquiv
  (k := k) (K := K) G field hinvariant)
variable (productFormula : BrauerLinearTensorProductFormula iotaM)
variable (radicalKernel : RadicalKernelLiftInput (p := ell) G field hinvariant D)

/-- Clause (ii)'s actual global correspondence. This is a genuine
hypothesis of the universally quantified published criterion; in Type B
it is supplied by the already checked Proposition-4.4 construction from orbit representatives.
There is no DOWNSTAIRS matching or full block-condition input. -/
structure GlobalCorrespondence where
  omega : IBr iotaM ≃ CharacterWeight.ConjugacyClass (p := ell) (K := K) (G := M)
  equivariant :
    let _ : MulAction (TypeBSpecialCliffordActionAdapter.ActingGroup
        (k := k) G field hinvariant) (IBr iotaM) :=
      brauerCharacterAction G field hinvariant iotaM productFormula
    let _ : MulAction (TypeBSpecialCliffordActionAdapter.ActingGroup
        (k := k) G field hinvariant)
        (CharacterWeight.ConjugacyClass (p := ell) (K := K) (G := M)) :=
      TypeBOddPrimesProposition44Actual.weightAction G field hinvariant D radicalKernel
    ∀ (a : TypeBSpecialCliffordActionAdapter.ActingGroup
        (k := k) G field hinvariant) (Phi : IBr iotaM),
      omega (a • Phi) = a • omega Phi
  block : ∀ Phi : IBr iotaM,
    blocks.weightUpstairs.weightBlock (omega Phi) =
      irreducibleBrauerCharacterBlock iotaM hinjM blocks.upstairs Phi

end GlobalClauses

section CompleteDomain

variable {ell : ℕ} {k K M E : Type}
variable [Field k] [Field K] [CharP k ell] [IsAlgClosed k] [CharZero K]
variable [IsAlgClosed K] [Group M] [Finite M] [Group E] [Finite E]
variable (G : Subgroup M) [G.Normal] (field : E →* MulAut M)
variable (action : NaturalAction G field)
variable (iotaM : PrimeRegularRootEmbedding ell k K M)
variable (iotaG : PrimeRegularRootEmbedding ell k K G)

local instance : Fintype M := Fintype.ofFinite _
local instance : Fintype G := Fintype.ofFinite _

variable [Fintype (LiteralPrimitiveBlock k M)]
variable [Fintype (LiteralPrimitiveBlock k G)]
variable (blocks : BlockData (ell := ell) (k := k) (K := K) G)

/-- The local reductions used to interpret the final block condition have
the SAME root convention on their actual normalizer quotients. This E1/U
realization datum does not assert an extension or any matched-pair relation. -/
structure LocalReductionData where
  blockCompatibility : TypeBFixedRootDefinitionFamily.GuardedBlockCompatibility
    iotaG blocks.weightDownstairs.operations
  reduction : ∀ (b : LiteralPrimitiveBlock k G)
      (w : CyclicOuterLemma37LiteralLocalExtension.LiteralWeightFibre
        blocks.weightDownstairs b),
    CyclicOuterLemma37LiteralLocalExtension.SelectedLocalReductionSource
      blocks.weightDownstairs b w
  rootAgreement : ∀ (b : LiteralPrimitiveBlock k G)
      (w : CyclicOuterLemma37LiteralLocalExtension.LiteralWeightFibre
        blocks.weightDownstairs b)
      (zeta : rootsOfUnity (primeRegularExponent ell
        (NormalizerQuotient
          (CyclicOuterLemma37LiteralLocalExtension.SelectedRadical
            blocks.weightDownstairs b w))) k),
    (reduction b w).iota.lift (((zeta : kˣ) : k)) =
      iotaG.lift (((zeta : kˣ) : k))

/-- The generic source family receives exactly the same specified block
catalogue and guarded reductions as this criterion domain. -/
def LocalReductionData.toPrimitiveLocalSource
    (data : LocalReductionData G iotaG blocks) :
    TypeBFixedRootDefinitionFamily.PrimitiveLocalSource iotaG where
  splitting := inferInstance
  blockSource := blocks.weightDownstairs
  idempotent := blocks.downstairs_idempotent
  blockCompatibility := data.blockCompatibility
  reduction := data.reduction
  reduction_roots := data.rootAgreement

/-- The downstairs problem family is constructed from the domain data;
no independently supplied family can rename its blocks or replace its
root convention, local source, or full automorphism stabilizers. -/
def downstairsFamily (hEll : Nat.Prime ell)
    (hinjG : IrreducibleBrauerCharacterInjectivity iotaG)
    (data : LocalReductionData G iotaG blocks) :
    EvenFieldFLZDefinition35Family.Definition35Family ell :=
  TypeBFixedRootDefinitionFamily.primitiveFamily iotaG hinjG blocks.downstairs hEll
    (LocalReductionData.toPrimitiveLocalSource G iotaG blocks data)

/-- The two published `J_G` definitions, without a caller-chosen `J_G`
function: inertia times the SAME actual Hall preimage. Requiring equality
for every actual constituent and covered weight avoids dependence on any
choice; the published Clifford-theoretic independence makes this the
standard sufficient reading. Nonempty cover/constituent clauses are separate.
-/
def JGCompatible
    (hall : HallData G ell)
    (dgn : TypeBWeightCoveringSource.DGNSource (ell := ell) (k := k) (K := K) G)
    (omega : IBr iotaM ≃ CharacterWeight.ConjugacyClass (p := ell) (K := K) (G := M)) :
    Prop :=
  ∀ (Phi : IBr iotaM) (phi : IBr iotaG)
    (W : CharacterWeight.ConjugacyClass (p := ell) (K := K) (G := G)),
    NavarroCoveringBrauerExtension.BrauerOccursInRestriction G iotaM iotaG Phi phi →
    TypeBWeightCoveringSource.CoversClass G dgn (omega Phi) W →
      (brauerMInertia G field action iotaG phi : Set M) *
          (hall.preimage : Set M) =
        (weightMInertia G field action W : Set M) * (hall.preimage : Set M)

/-- A source-independent sufficient `J_G` hypothesis: EVERY actual
downstairs Brauer inertia and EVERY actual downstairs weight-class inertia
have equal products with the same literal Hall preimage. The published
definitions in Brough--Spaeth Lemmas 2.14--2.15 (`lem216`/`lem29`, local
TeX lines 444--487) under Hypothesis 2.13 then apply to whichever
constituent and authentic covered weight occur. No DGN implementation or
covering predicate is supplied to the final criterion domain. The abelian
quotient and the two M-extension clauses of Hypothesis 2.13 are retained
in `Structural` and `ExtensionClauses`. -/
def AllPairsJG (hall : HallData G ell) : Prop :=
  ∀ (phi : IBr iotaG)
    (W : CharacterWeight.ConjugacyClass (p := ell) (K := K) (G := G)),
    (brauerMInertia G field action iotaG phi : Set M) * (hall.preimage : Set M) =
      (weightMInertia G field action W : Set M) * (hall.preimage : Set M)

variable (hinjM : IrreducibleBrauerCharacterInjectivity iotaM)
variable (hinvariant : TypeCConformalActionAdapter.FieldInvariantSubgroup.IsInvariant G field)
variable (D : TypeCConformalActionAdapter.OrdinaryReductionEquiv
  (k := k) (K := K) G field hinvariant)
variable (productFormula : BrauerLinearTensorProductFormula iotaM)
variable (radicalKernel : RadicalKernelLiftInput (p := ell) G field hinvariant D)

/-- The complete INPUT domain for the universally quantified all-blocks
criterion. It retains its cover and prime scope, structural clause, all
four character extensions, actual upstairs correspondence, literal `J_G`
compatibility, constituent clause and raw-normalizer clause.

All-phi and all-weight extension are deliberate sufficient strengthenings;
they include every conjugate and the representative required in the original
Theorem 4.5. No property of a downstairs matching or full condition is a
field. The all-pairs inertia/Hall condition implies the authentic published
`J_G` equality without parameterizing the criterion by a DGN realization.
The earlier conditional covering definitions remain separate audit material.
The three lift laws identify the displayed LinBr action with the actual
root-compatible, prime-to-ell ordinary lifts, not an arbitrary isomorphism
of linear character groups. -/
structure AllBlocksHypotheses where
  prime : Nat.Prime ell
  coefficient : SpathCoefficientField ell k prime
  cover : EllPrimeCoverSource ell G
  divides_simple_order : ell ∣ Nat.card cover.S
  structural : Structural G field action
  rootAgreement : RootAgreement G iotaM iotaG
  brauer_injective_downstairs : IrreducibleBrauerCharacterInjectivity iotaG
  localReduction : LocalReductionData G iotaG blocks
  liftCompatible : TypeBSpecialCliffordActionAdapter.OrdinaryLiftReductionCompatible
    G field hinvariant D iotaM
  lift_primeTo : ∀ lambda : TensorCharacters (k := k) G,
    ell.Coprime (orderOf (TypeCConformalActionAdapter.OrdinaryReductionEquiv.lift
      (G0 := G) (field := field) (hinvariant := hinvariant) D lambda))
  lift_trivial : ∀ lambda : TensorCharacters (k := k) G,
    TypeCConformalActionAdapter.OrdinaryReductionEquiv.lift
        (G0 := G) (field := field) (hinvariant := hinvariant) D lambda ∈
      linearCharactersTrivialOn (k := K) G
  extensions : ExtensionClauses G field action iotaG
  correspondence : GlobalCorrespondence G field iotaM blocks hinjM
    hinvariant D productFormula radicalKernel
  hall : HallData G ell
  JG : AllPairsJG G field action iotaG hall
  constituent : ConstituentClause G field action iotaM iotaG
  rawNormalizer : RawNormalizerClause (ell := ell) (K := K) G field action

end CompleteDomain

end ModularRep.PaperProofs.TypeBCriterionHypotheses


/-
This file is part of ModularRep, the Lean companion to
Baoyu Zhang (2026), "On the inductive blockwise Alperin weight condition
for type B and type C".

The formalisation checks selected arguments under explicit external
assumptions. See FORMALISATION_GUIDE.md in the package root.
-/
