import ModularRep.PaperProofs.TypeBAllRankGGGREntriesRestriction
import ModularRep.PaperProofs.TypeBAllRankGGGRFibres

/-!
# Specified nonabelian GGGR entries on the actual regular embedding

The Taylor source is confined to one represented geometric class and one
upper family.  Its upper nonnegative sum-one and coverage are the exact
Geck--Hezard/Taylor inputs.  Frobenius reciprocity uses the literal induction
formula on the norm-kernel inclusion.  The lower permutation matrix is
constructed from these inputs, actual Clifford transitivity, and the derived
component-class geometry.
-/

noncomputable section
set_option autoImplicit false

namespace ModularRep.PaperProofs.TypeBAllRankGGGREntries

open ModularRep OrdinaryIrreducibleCharacter TypeBCliffordCarriers
open TypeBSpinOrdinaryRestriction TypeBSpinPrincipalProjectiveBinding
open TypeBSpinRationalUnipotentClassBinding TypeBAllRankGGGRFibres
open TypeBGGGRRankProposition412Relative
open scoped BigOperators
attribute [local instance] Classical.propDecidable

local instance finiteTypeFintypeEntries (X : Type) [Finite X] : Fintype X :=
  Fintype.ofFinite X

private theorem nat_sum_one_support {X : Type} [Fintype X] (a : X → ℕ)
    (hsum : ∑ x, a x = 1) : ∃ x, ∀ y, a y = if y = x then 1 else 0 := by
  classical
  have hex : ∃ x, a x ≠ 0 := by
    by_contra h
    push_neg at h
    simp [h] at hsum
  obtain ⟨x, hx⟩ := hex
  have hle : a x ≤ 1 := by
    simpa [hsum] using
      (Finset.single_le_sum (fun y (_ : y ∈ Finset.univ) => Nat.zero_le (a y))
        (Finset.mem_univ x))
  have hax : a x = 1 := by omega
  refine ⟨x, ?_⟩
  intro y
  by_cases hy : y = x
  · simpa [hy] using hax
  · have hpair : a x + a y ≤ 1 := by
      have h := Finset.sum_le_sum_of_subset (f := a)
        (show ({x, y} : Finset X) ⊆ Finset.univ by simp)
      simpa [hy, Ne.symm hy, hsum] using h
    simp only [if_neg hy]
    omega

/-- Finite summation is independent of the chosen enumeration instance. -/
private theorem sum_univ_fintype_eq {X M : Type*} [AddCommMonoid M]
    (s t : Fintype X) (a : X → M) :
    @Finset.sum X M _ (@Finset.univ X s) a =
      @Finset.sum X M _ (@Finset.univ X t) a := by
  cases Subsingleton.elim s t
  rfl

variable {n r f : ℕ} {F K : Type} [Field F] [Finite F] [CharP F r]
  [Field K] [CharZero K] {N : NormSource n F} [Finite (Spin n F N)]
  [Finite (SpecialClifford n F)] [Finite (Irr K (Spin n F N))]

local instance upperUnipotent_finite :
    Finite (UpperUnipotentClass (n := n) (F := F) (r := r)) := by
  letI : Finite (ConjClasses (SpecialClifford n F)) :=
    Finite.of_surjective ConjClasses.mk ConjClasses.mk_surjective
  unfold UpperUnipotentClass
  infer_instance

/-- The normalized scalar product on the actual special Clifford overgroup. -/
def upperScalarProduct (x y : SpecialClifford n F → K) : K :=
  (Nat.card (SpecialClifford n F) : K)⁻¹ * ∑ g, x g⁻¹ * y g

/-- Ordinary induction along the literal norm-kernel inclusion, on functions. -/
def induceSpinFunction (x : Spin n F N → K) : SpecialClifford n F → K := by
  classical
  exact fun g => (Nat.card (Spin n F N) : K)⁻¹ *
    ∑ t : SpecialClifford n F,
      if h : t⁻¹ * g * t ∈ SpinSubgroup n F N then x ⟨t⁻¹ * g * t, h⟩ else 0

/-- Standard E1 Frobenius reciprocity for these literal finite group formulas.
The equation is before decomposition into any restriction constituents. -/
structure FrobeniusReciprocitySource : Prop where
  reciprocity : ∀ (Phi : Irr K (SpecialClifford n F)) (x : Spin n F N → K),
    scalarProductRight (restrictionClassFunction N Phi) x =
      upperScalarProduct Phi.val (induceSpinFunction x)

variable {GeometricClass : Type}
  (geometricClass : UnipotentClass (r := r) (N := N) → GeometricClass)
  (upperGeometricClass : UpperUnipotentClass (n := n) (F := F) (r := r) → GeometricClass)
  (geometric_square : ∀ c, upperGeometricClass (upperClassMap c) = geometricClass c)
  (C : GeometricClass)

/-- The published Taylor/GH inputs, for exactly one upper family above one
represented geometric class. Sum one uses P1/P3 and the weighted GH formula;
coverage uses Taylor's separate discussion of the nonabelian Spin case.
The abelian finite group attached to the Lusztig family and the abelian
upper component group are distinct source guards, not identified here.
The actual centre map must be injective with image generated by theta,
so its image group Z_G(u) is the full image of Z(G). Connected centre of
the algebraic regular overgroup, acceptable odd defining prime, the same
finite-point realization, and finite cyclotomic interpretation in K remain
E2/U authentication obligations. These comments supply no realizations. -/
structure TaylorFamilySource
    (parameters : OddFieldParameters F r f) (rank : 4 ≤ n)
    [HasEnoughRootsOfUnity K (Nat.card (SpecialClifford n F))]
    [HasEnoughRootsOfUnity K (Nat.card (Spin n F N))]
    (gamma : UnipotentClass (r := r) (N := N) → Spin n F N → K)
    (upperGamma : UpperRationalFibre upperGeometricClass C → SpecialClifford n F → K)
    (family : Set (Irr K (SpecialClifford n F)))
    (upperDual : Irr K (SpecialClifford n F) → Irr K (SpecialClifford n F))
    (lowerDual : Irr K (Spin n F N) → Irr K (Spin n F N)) where
  restriction : RestrictionSource (N := N) family upperDual lowerDual
  /-- Ordinary nonnegativity on the SAME upper family and GGGR values. -/
  upperNonnegative : ∀ Phi ∈ family, ∀ u,
    ∃ a : ℕ, upperScalarProduct (upperDual Phi).val (upperGamma u) = (a : K)
  /-- Taylor P1/P3 and GH Proposition 4.3's weighted formula (TeX 565–581),
  with the finite Lusztig-family group abelian. All component indices are
  one because Frobenius acts trivially on the abelian upper component V.
  Abelianness of the family group is a separate E2/U source guard. -/
  upperSumOne : ∀ Phi ∈ family,
    ∑ u, upperScalarProduct (upperDual Phi).val (upperGamma u) = 1
  /-- Taylor 2013 Section 5, remark at TeX 402, with the SAME upper-family
  pairing of 352–354. Its guards are abelian upper component and the actual
  centre-image identification Z_G(u)=Z(G), here the injection with image
  generated by theta in the type-B description at 147–157. This is not an
  application of a family-wide two-constituent assertion or a lower match. -/
  coverage : ∀ u, ∃ Phi ∈ family,
    upperScalarProduct (upperDual Phi).val (upperGamma u) ≠ 0
  distinguished : ∃ Phi ∈ family, Fintype.card (Constituent (N := N) Phi) = 2
  gggrInduction : ∀ c : RationalFibre geometricClass C,
    upperGamma (rationalClassMap geometricClass upperGeometricClass geometric_square C c) =
      induceSpinFunction (gamma c.val)
  gggrConjugation : ∀ (g : SpecialClifford n F) (c : RationalFibre geometricClass C),
    gamma (ambientClassEquiv geometricClass upperGeometricClass geometric_square C g c).val =
      fun x => gamma c.val (MulAut.conjNormal (H := SpinSubgroup n F N) g⁻¹ x)

variable {geometricClass upperGeometricClass geometric_square C}
  {parameters : OddFieldParameters F r f} {rank : 4 ≤ n}
  [HasEnoughRootsOfUnity K (Nat.card (SpecialClifford n F))]
  [HasEnoughRootsOfUnity K (Nat.card (Spin n F N))]
  {gamma : UnipotentClass (r := r) (N := N) → Spin n F N → K}
  {upperGamma : UpperRationalFibre upperGeometricClass C → SpecialClifford n F → K}
  {family : Set (Irr K (SpecialClifford n F))}
  {upperDual : Irr K (SpecialClifford n F) → Irr K (SpecialClifford n F)}
  {lowerDual : Irr K (Spin n F N) → Irr K (Spin n F N)}
  (source : TaylorFamilySource geometricClass upperGeometricClass geometric_square C
    parameters rank gamma upperGamma family upperDual lowerDual)
  (reciprocity : FrobeniusReciprocitySource (N := N) (K := K))
  (nonnegative : ∀ (theta : Irr K (Spin n F N)) (c : UnipotentClass (r := r) (N := N)),
    ∃ a : ℕ, scalarProductRight theta.val (gamma c) = (a : K))

def upperMultiplicity (Phi : family) (u : UpperRationalFibre upperGeometricClass C) : ℕ :=
  Classical.choose (source.upperNonnegative Phi.val Phi.property u)

theorem upperMultiplicity_cast (Phi : family) (u : UpperRationalFibre upperGeometricClass C) :
    (upperMultiplicity source Phi u : K) =
      upperScalarProduct (upperDual Phi.val).val (upperGamma u) :=
  (Classical.choose_spec (source.upperNonnegative Phi.val Phi.property u)).symm

theorem upperMultiplicity_sum (Phi : family) : ∑ u, upperMultiplicity source Phi u = 1 := by
  apply Nat.cast_injective (R := K)
  push_cast
  simp only [upperMultiplicity_cast]
  exact source.upperSumOne Phi.val Phi.property

def upperSupport (Phi : family) : UpperRationalFibre upperGeometricClass C :=
  Classical.choose (nat_sum_one_support (upperMultiplicity source Phi)
    (upperMultiplicity_sum source Phi))

theorem upperMultiplicity_eq (Phi : family) (u : UpperRationalFibre upperGeometricClass C) :
    upperMultiplicity source Phi u = if u = upperSupport source Phi then 1 else 0 := by
  have h := Classical.choose_spec (nat_sum_one_support (upperMultiplicity source Phi)
    (upperMultiplicity_sum source Phi)) u
  by_cases hu : u = upperSupport source Phi
  · rw [if_pos hu]
    simp only [upperSupport] at hu
    simpa only [if_pos hu] using h
  · rw [if_neg hu]
    simp only [upperSupport] at hu
    simpa only [if_neg hu] using h

theorem upperSupport_coverage (u : UpperRationalFibre upperGeometricClass C) :
    ∃ Phi : family, upperSupport source Phi = u := by
  obtain ⟨Phi, hPhi, hnonzero⟩ := source.coverage u
  refine ⟨⟨Phi, hPhi⟩, ?_⟩
  by_contra h
  have hzero := upperMultiplicity_eq source ⟨Phi, hPhi⟩ u
  rw [if_neg (Ne.symm h)] at hzero
  apply hnonzero
  rw [← upperMultiplicity_cast source ⟨Phi, hPhi⟩ u, hzero, Nat.cast_zero]

include reciprocity in
theorem restriction_pairing (Phi : family) (c : RationalFibre geometricClass C) :
    scalarProductRight (restrictionClassFunction N (upperDual Phi.val)) (gamma c.val) =
      (upperMultiplicity source Phi
        (rationalClassMap geometricClass upperGeometricClass geometric_square C c) : K) := by
  rw [reciprocity.reciprocity, ← source.gggrInduction c, upperMultiplicity_cast]

include reciprocity in
theorem lower_column_sum (Phi : family) (c : RationalFibre geometricClass C) :
    (∑ theta : Constituent (N := N) Phi.val,
      multiplicity gamma nonnegative (lowerDual theta.val) c.val) =
      upperMultiplicity source Phi
        (rationalClassMap geometricClass upperGeometricClass geometric_square C c) := by
  apply Nat.cast_injective (R := K)
  have hsum := sum_univ_fintype_eq
    (inferInstance : Fintype (Constituent (N := N) Phi.val))
    (finiteTypeFintype (Constituent (N := N) Phi.val))
    (fun theta => multiplicity gamma nonnegative (lowerDual theta.val) c.val)
  exact (congrArg (fun a : ℕ => (a : K)) hsum).trans
    ((lower_column_sum_cast (gamma := gamma) (nonnegative := nonnegative)
      source.restriction Phi.val Phi.property c.val).trans
        (restriction_pairing source reciprocity Phi c))

include source in
theorem entry_conjugation (Phi : family) (theta : Constituent (N := N) Phi.val)
    (g : SpecialClifford n F) (c : RationalFibre geometricClass C) :
    multiplicity gamma nonnegative
        (lowerDual (twist K (Spin n F N) theta.val
          (MulAut.conjNormal (H := SpinSubgroup n F N) g⁻¹)))
        (ambientClassEquiv geometricClass upperGeometricClass geometric_square C g c).val =
      multiplicity gamma nonnegative (lowerDual theta.val) c.val := by
  apply Nat.cast_injective (R := K)
  rw [multiplicity_cast, multiplicity_cast,
    source.restriction.dualityConjugation Phi.val Phi.property theta g,
    source.gggrConjugation g c]
  exact scalarProductRight_pullback N
    (MulAut.conjNormal (H := SpinSubgroup n F N) g⁻¹) _ _

variable {A V : Type} [Group A] [CommGroup V]
  {presentation : ComponentPresentation A V}
  (components : CompatibleComponentParametrisation geometricClass upperGeometricClass
    geometric_square parameters rank C A V presentation)

local notation "π" => rationalClassMap geometricClass upperGeometricClass geometric_square C
local notation "act" => ambientClassEquiv geometricClass upperGeometricClass geometric_square C

include reciprocity in
/-- Transitivity fixes the sole rational class in a nonexceptional fibre.
The equal-entry sum-one argument then forces actual restriction irreducibility. -/
theorem singleton_irreducible (Phi : family)
    (hne : upperSupport source Phi ≠ components.exceptional) :
    Fintype.card (Constituent (N := N) Phi.val) = 1 ∧
      ∀ (theta : Constituent (N := N) Phi.val) (c : RationalFibre geometricClass C),
        π c = upperSupport source Phi →
          multiplicity gamma nonnegative (lowerDual theta.val) c.val = 1 := by
  letI := source.restriction.nonempty Phi.val Phi.property
  obtain ⟨c, hc⟩ := components.map_surjective (upperSupport source Phi)
  have hequal : ∀ theta psi : Constituent (N := N) Phi.val,
      multiplicity gamma nonnegative (lowerDual theta.val) c.val =
        multiplicity gamma nonnegative (lowerDual psi.val) c.val := by
    intro theta psi
    obtain ⟨g, hg⟩ := source.restriction.cliffordTransitive Phi.val Phi.property theta psi
    have hfix : act g c = c :=
      components.nonexceptional_fibre_unique (upperSupport source Phi) hne _ _
        ((map_ambientClassEquiv geometricClass upperGeometricClass geometric_square C g c).trans hc)
        hc
    have h := entry_conjugation source nonnegative Phi theta g c
    rw [hg, hfix] at h
    exact h.symm
  have hsum : (∑ theta : Constituent (N := N) Phi.val,
      multiplicity gamma nonnegative (lowerDual theta.val) c.val) = 1 := by
    rw [lower_column_sum source reciprocity nonnegative, hc, upperMultiplicity_eq,
      if_pos rfl]
  obtain ⟨hcard, hentry⟩ := singleton_fibre_forces_irreducible
    (fun theta : Constituent (N := N) Phi.val =>
      multiplicity gamma nonnegative (lowerDual theta.val) c.val) hequal hsum
  refine ⟨hcard, ?_⟩
  intro theta d hd
  have hdc := components.nonexceptional_fibre_unique (upperSupport source Phi) hne d c hd hc
  simpa only [hdc] using hentry theta

include reciprocity in
/-- Every zero upper entry kills each actual lower constituent entry. -/
theorem cross_fibre_zero (Phi : family) (theta : Constituent (N := N) Phi.val)
    (c : RationalFibre geometricClass C) (h : π c ≠ upperSupport source Phi) :
    multiplicity gamma nonnegative (lowerDual theta.val) c.val = 0 := by
  apply lower_entry_zero_of_restriction_zero source.restriction Phi.val Phi.property c.val
  rw [restriction_pairing source reciprocity, upperMultiplicity_eq, if_neg h, Nat.cast_zero]

def distinguishedParent : family :=
  ⟨Classical.choose source.distinguished,
    (Classical.choose_spec source.distinguished).1⟩

theorem distinguishedParent_card :
    Fintype.card (Constituent (N := N) (distinguishedParent source).val) = 2 :=
  (Classical.choose_spec source.distinguished).2

include reciprocity nonnegative in
theorem distinguishedParent_support :
    upperSupport source (distinguishedParent source) = components.exceptional := by
  by_contra h
  have hone := (singleton_irreducible source reciprocity nonnegative components
    (distinguishedParent source) h).1
  have htwo := distinguishedParent_card source
  omega

def twoConstituentEquiv : Constituent (N := N) (distinguishedParent source).val ≃ Fin 2 :=
  Fintype.equivFinOfCardEq (distinguishedParent_card source)

def twoConstituent (i : Fin 2) : Constituent (N := N) (distinguishedParent source).val :=
  (twoConstituentEquiv source).symm i

def twoClass (i : Fin 2) : RationalFibre geometricClass C :=
  (components.exceptionalFibreEquiv.symm i).val

theorem twoClass_eq_relabel (i : Fin 2) :
    twoClass components i = components.relabel.symm (Sum.inr i) := rfl

def twoEntry (i j : Fin 2) : ℕ :=
  multiplicity gamma nonnegative (lowerDual (twoConstituent source i).val)
    (twoClass components j).val

include reciprocity in
theorem twoEntry_column_sum (j : Fin 2) :
    twoEntry source nonnegative components 0 j + twoEntry source nonnegative components 1 j = 1 := by
  calc
    _ = ∑ i : Fin 2, twoEntry source nonnegative components i j :=
      (Fin.sum_univ_two _).symm
    _ = ∑ theta : Constituent (N := N) (distinguishedParent source).val,
        multiplicity gamma nonnegative (lowerDual theta.val) (twoClass components j).val := by
      simpa only [twoEntry, twoConstituent] using
        (twoConstituentEquiv source).symm.sum_comp
          (fun theta => multiplicity gamma nonnegative (lowerDual theta.val)
            (twoClass components j).val)
    _ = upperMultiplicity source (distinguishedParent source) (π (twoClass components j)) :=
      lower_column_sum source reciprocity nonnegative _ _
    _ = 1 := by
      rw [show π (twoClass components j) = components.exceptional from
        (components.exceptionalFibreEquiv.symm j).property,
        upperMultiplicity_eq, distinguishedParent_support source reciprocity nonnegative components,
        if_pos rfl]

/-- The actual ambient action on the actual occurrence subtype. -/
def constituentAction (Phi : family) (g : SpecialClifford n F) :
    Equiv.Perm (Constituent (N := N) Phi.val) where
  toFun theta := ⟨twist K (Spin n F N) theta.val
    (MulAut.conjNormal (H := SpinSubgroup n F N) g⁻¹),
      (occurs_diagonal N Phi.val theta.val g).2 theta.property⟩
  invFun theta := ⟨twist K (Spin n F N) theta.val
    (MulAut.conjNormal (H := SpinSubgroup n F N) (g⁻¹)⁻¹),
      (occurs_diagonal N Phi.val theta.val g⁻¹).2 theta.property⟩
  left_inv theta := by
    apply Subtype.ext
    apply OrdinaryIrreducibleCharacter.ext
    intro x
    change theta.val ((MulAut.conjNormal (H := SpinSubgroup n F N) g⁻¹)
      ((MulAut.conjNormal (H := SpinSubgroup n F N) (g⁻¹)⁻¹) x)) = theta.val x
    simp
  right_inv theta := by
    apply Subtype.ext
    apply OrdinaryIrreducibleCharacter.ext
    intro x
    change theta.val ((MulAut.conjNormal (H := SpinSubgroup n F N) (g⁻¹)⁻¹)
      ((MulAut.conjNormal (H := SpinSubgroup n F N) g⁻¹) x)) = theta.val x
    simp

def swappingActor : SpecialClifford n F :=
  Classical.choose (source.restriction.cliffordTransitive
    (distinguishedParent source).val (distinguishedParent source).property
    (twoConstituent source 0) (twoConstituent source 1))

theorem swappingActor_first :
    constituentAction (distinguishedParent source) (swappingActor source)
      (twoConstituent source 0) = twoConstituent source 1 :=
  Subtype.ext (Classical.choose_spec (source.restriction.cliffordTransitive
    (distinguishedParent source).val (distinguishedParent source).property
    (twoConstituent source 0) (twoConstituent source 1)))

theorem swappingActor_rows (i : Fin 2) :
    constituentAction (distinguishedParent source) (swappingActor source)
      (twoConstituent source i) = twoConstituent source (swapTwo i) := by
  fin_cases i
  · simpa using swappingActor_first source
  · have hne : constituentAction (distinguishedParent source) (swappingActor source)
        (twoConstituent source 1) ≠ twoConstituent source 1 := by
      intro h
      have h01 := (constituentAction (distinguishedParent source)
        (swappingActor source)).injective ((swappingActor_first source).trans h.symm)
      have h01' := (twoConstituentEquiv source).symm.injective h01
      exact Fin.zero_ne_one h01'
    have hi : twoConstituentEquiv source
        (constituentAction (distinguishedParent source) (swappingActor source)
          (twoConstituent source 1)) = 0 := by
      have hn : twoConstituentEquiv source
          (constituentAction (distinguishedParent source) (swappingActor source)
            (twoConstituent source 1)) ≠ 1 := by
        intro h
        apply hne
        exact (twoConstituentEquiv source).injective (by simpa [twoConstituent] using h)
      apply Fin.ext
      have hlt := (twoConstituentEquiv source
        (constituentAction (distinguishedParent source) (swappingActor source)
          (twoConstituent source 1))).isLt
      have hnval : (twoConstituentEquiv source
          (constituentAction (distinguishedParent source) (swappingActor source)
            (twoConstituent source 1))).val ≠ 1 := by
        intro hval
        exact hn (Fin.ext hval)
      change _ = 0
      omega
    simpa [twoConstituent] using congrArg (twoConstituentEquiv source).symm hi

/-- Restriction of literal ambient class conjugation to the exceptional fibre. -/
def exceptionalAmbientAction (g : SpecialClifford n F) :
    Equiv.Perm {c : RationalFibre geometricClass C // π c = components.exceptional} where
  toFun c := ⟨act g c.val,
    (map_ambientClassEquiv geometricClass upperGeometricClass geometric_square C g c.val).trans
      c.property⟩
  invFun c := ⟨(act g).symm c.val, by
    have h := map_ambientClassEquiv geometricClass upperGeometricClass geometric_square C g
      ((act g).symm c.val)
    rw [(act g).apply_symm_apply] at h
    exact h.symm.trans c.property⟩
  left_inv c := Subtype.ext ((act g).symm_apply_apply c.val)
  right_inv c := Subtype.ext ((act g).apply_symm_apply c.val)

def exceptionalClassAction : Equiv.Perm (Fin 2) :=
  components.exceptionalFibreEquiv.symm.trans
    ((exceptionalAmbientAction components (swappingActor source)).trans
      components.exceptionalFibreEquiv)

theorem twoClass_action (j : Fin 2) :
    twoClass components (exceptionalClassAction source components j) =
      act (swappingActor source) (twoClass components j) := by
  change (components.exceptionalFibreEquiv.symm
    (components.exceptionalFibreEquiv
      (exceptionalAmbientAction components (swappingActor source)
        (components.exceptionalFibreEquiv.symm j)))).val = _
  rw [components.exceptionalFibreEquiv.symm_apply_apply]
  rfl

theorem twoEntry_equivariant (i j : Fin 2) :
    twoEntry source nonnegative components (swapTwo i)
        (exceptionalClassAction source components j) =
      twoEntry source nonnegative components i j := by
  have h := entry_conjugation source nonnegative (distinguishedParent source)
    (twoConstituent source i) (swappingActor source) (twoClass components j)
  have hr := congrArg Subtype.val (swappingActor_rows source i)
  change twist K (Spin n F N) (twoConstituent source i).val
    (MulAut.conjNormal (H := SpinSubgroup n F N) (swappingActor source)⁻¹) =
      (twoConstituent source (swapTwo i)).val at hr
  rw [hr, ← twoClass_action source components j] at h
  exact h

include reciprocity nonnegative in
/-- The swapping Clifford actor must transpose the actual two class labels:
a fixed class would give two equal nonnegative entries with sum one. -/
theorem exceptionalClassAction_eq_swap :
    exceptionalClassAction source components = swapTwo := by
  have h0 : exceptionalClassAction source components 0 ≠ 0 := by
    intro hfix
    have h := twoEntry_equivariant source nonnegative components 0 0
    rw [swapTwo_zero, hfix] at h
    have hs := twoEntry_column_sum source reciprocity nonnegative components 0
    omega
  have hz : exceptionalClassAction source components 0 = 1 :=
    Fin.eq_one_of_ne_zero _ h0
  apply Equiv.ext
  intro j
  fin_cases j
  · simpa using hz
  · have hn : exceptionalClassAction source components 1 ≠ 1 := by
      intro h
      exact Fin.zero_ne_one ((exceptionalClassAction source components).injective (hz.trans h.symm))
    change exceptionalClassAction source components (1 : Fin 2) = swapTwo (1 : Fin 2)
    rw [swapTwo_one]
    apply Fin.ext
    have hlt := (exceptionalClassAction source components 1).isLt
    have hnval : (exceptionalClassAction source components 1).val ≠ 1 := by
      intro hval
      exact hn (Fin.ext hval)
    change _ = 0
    omega

def singletonParent
    (u : {u : UpperRationalFibre upperGeometricClass C // u ≠ components.exceptional}) : family :=
  Classical.choose (upperSupport_coverage source u.val)

theorem singletonParent_support
    (u : {u : UpperRationalFibre upperGeometricClass C // u ≠ components.exceptional}) :
    upperSupport source (singletonParent source components u) = u.val :=
  Classical.choose_spec (upperSupport_coverage source u.val)

def singletonConstituent
    (u : {u : UpperRationalFibre upperGeometricClass C // u ≠ components.exceptional}) :
    Constituent (N := N) (singletonParent source components u).val :=
  Classical.choice (source.restriction.nonempty
    (singletonParent source components u).val (singletonParent source components u).property)

def rowBefore :
    Sum {u : UpperRationalFibre upperGeometricClass C // u ≠ components.exceptional} (Fin 2) →
      Irr K (Spin n F N)
  | Sum.inl u => (singletonConstituent source components u).val
  | Sum.inr i => (twoConstituent source i).val

def rowParent :
    Sum {u : UpperRationalFibre upperGeometricClass C // u ≠ components.exceptional} (Fin 2) → family
  | Sum.inl u => singletonParent source components u
  | Sum.inr _ => distinguishedParent source

theorem row_occurs
    (x : Sum {u : UpperRationalFibre upperGeometricClass C // u ≠ components.exceptional} (Fin 2)) :
    occurs N (rowParent source components x).val (rowBefore source components x) := by
  rcases x with u | i
  · exact (singletonConstituent source components u).property
  · exact (twoConstituent source i).property

include reciprocity in
/-- All four portions of the combined block are derived from the SAME
upper family.  In particular the off-fibre zeros are not fields of a model. -/
theorem entry_relabel_derived
    (x y : Sum {u : UpperRationalFibre upperGeometricClass C // u ≠ components.exceptional} (Fin 2)) :
    multiplicity gamma nonnegative (lowerDual (rowBefore source components x))
        (components.relabel.symm y).val =
      assembledFibreMatrix (twoEntry source nonnegative components) x y := by
  classical
  rcases x with u | i <;> rcases y with v | j
  · change multiplicity gamma nonnegative
      (lowerDual (singletonConstituent source components u).val)
        (components.relabel.symm (Sum.inl v)).val = if u = v then 1 else 0
    have hs := singletonParent_support source components u
    by_cases huv : u = v
    · rw [if_pos huv]
      apply (singleton_irreducible source reciprocity nonnegative components
        (singletonParent source components u) (by rw [hs]; exact u.property)).2
      rw [components.map_relabel_symm_inl, hs, huv]
    · rw [if_neg huv]
      apply cross_fibre_zero source reciprocity nonnegative
        (singletonParent source components u) (singletonConstituent source components u)
      rw [components.map_relabel_symm_inl, hs]
      intro h
      exact huv (Subtype.ext h.symm)
  · change multiplicity gamma nonnegative
      (lowerDual (singletonConstituent source components u).val)
        (components.relabel.symm (Sum.inr j)).val = 0
    apply cross_fibre_zero source reciprocity nonnegative
      (singletonParent source components u) (singletonConstituent source components u)
    rw [components.map_relabel_symm_inr, singletonParent_support]
    exact Ne.symm u.property
  · change multiplicity gamma nonnegative
      (lowerDual (twoConstituent source i).val)
        (components.relabel.symm (Sum.inl v)).val = 0
    apply cross_fibre_zero source reciprocity nonnegative
      (distinguishedParent source) (twoConstituent source i)
    rw [components.map_relabel_symm_inl,
      distinguishedParent_support source reciprocity nonnegative components]
    exact v.property
  · rfl

/-- Output carrier for the global specified basis construction.  Both the
before-duality character and its parent in the SAME upper family remain
available to the independent quasi-isolated-label/support source. -/
structure SelectedFamily where
  beforeDual : RationalFibre geometricClass C → Irr K (Spin n F N)
  parent : RationalFibre geometricClass C → family
  occurrence : ∀ c, occurs N (parent c).val (beforeDual c)
  nonabelianModel : NonabelianFibreModel
    (fun c d : RationalFibre geometricClass C =>
      multiplicity gamma nonnegative (lowerDual (beforeDual c)) d.val)

/-- Internal construction of the formerly missing specified fibre model.
No entry-relabel equation, singleton irreducibility, or exceptional swap is
accepted as a source: all three are established above. -/
def selectedFamily : SelectedFamily (geometricClass := geometricClass) (C := C)
    (family := family) (gamma := gamma) nonnegative (lowerDual := lowerDual) := by
  classical
  refine
    { beforeDual := fun c => rowBefore source components (components.relabel c)
      parent := fun c => rowParent source components (components.relabel c)
      occurrence := fun c => row_occurs source components (components.relabel c)
      nonabelianModel :=
        { Singleton := {u : UpperRationalFibre upperGeometricClass C // u ≠ components.exceptional}
          singletonDecidableEq := inferInstance
          relabel := components.relabel
          twoEntry := twoEntry source nonnegative components
          entry_relabel := ?_
          classAction := exceptionalClassAction source components
          equivariant := twoEntry_equivariant source nonnegative components
          column_sum_one := twoEntry_column_sum source reciprocity nonnegative components } }
  intro c d
  have h := entry_relabel_derived source reciprocity nonnegative components
    (components.relabel c) (components.relabel d)
  simpa only [components.relabel.symm_apply_apply] using h

/-- The resulting specified entries are a permutation block. -/
theorem selectedFamily_permutation :
    ∃ p : Equiv.Perm (RationalFibre geometricClass C),
      ∀ c d : RationalFibre geometricClass C,
        multiplicity gamma nonnegative
            (lowerDual ((selectedFamily source reciprocity nonnegative components).beforeDual c))
            d.val = if c = p d then 1 else 0 := by
  classical
  exact diagonal_block_from_component_cases _
    (Sum.inr (selectedFamily source reciprocity nonnegative components).nonabelianModel)

end ModularRep.PaperProofs.TypeBAllRankGGGREntries


/-
This file is part of ModularRep, the Lean companion to
Baoyu Zhang (2026), "On the inductive blockwise Alperin weight condition
for type B and type C".

The formalisation checks selected arguments under explicit external
assumptions. See FORMALISATION_GUIDE.md in the package root.
-/
