import ModularRep.PaperProofs.TypeBSpinEffectiveSourceBinding

/-!
# The literal Spin outer block stabilizer in the revised Conlon lemma

Manuscript inference: `lem:type-b-conlon-block`, canonical source SHA256
57FA776468238FA29414ADE3B0232F504A69BE3C176A0D24B514908892C203DC,
lines 77--78, 85--102 and 124--126.  The actor is
`Aut(Spin)_B / Inn(Spin)`, with the natural inverse-pullback actions.

The only additional E1 input is the generator-compatible outer-group
description in FLZ, Section 3.5, p. 546, on the SAME norm-kernel Spin,
Clifford conjugation and field maps.  It is stated on the literal quotient,
with the standing odd-field parameters and rank at least three.  No
faithfulness of a character, block, or lattice action is assumed.

K: inner automorphisms are killed independently on ordinary characters,
Brauer characters, primitive blocks and exact K0; these maps descend through
the literal inner subgroup.  The supplied structural coordinates identify
the resulting actions with the previously constructed product actions.
Restriction and the first isomorphism theorem identify the literal block
stabilizer quotient with the product block stabilizer.  Its field kernel
embeds in C2, giving the manuscript's 2-hypoelementary conclusion.

The existing block lattice and Conlon bijection are to be consumed on the
same fibres through `blockQuotientEquiv`; no new basic set, lattice map or
bijection is an external input of this module.
-/

noncomputable section
set_option autoImplicit false

namespace ModularRep.PaperProofs.TypeBOddPrimeSpinOuterQuotient

open ModularRep ExactGrothendieckGroup TypeBCliffordCarriers
open TypeBSpinStabilizer TypeBAutomorphismSource
open TypeBSpinDiagonalFieldQuotient TypeBSpinEffectiveClassActions
open TypeBSpinInnerClassActions TypeBSpinQuotientClassActions
open TypeBSpinFieldClassActions

variable {n p f : ℕ} {F : Type} [Field F] [Finite F] [CharP F p]
  (N : NormSource n F) (D : DiagonalSource N)
  {parameters : OddFieldParameters F p f}
  (fs : FieldActionSource n F p f parameters N)

/-- The natural projection onto the actual outer automorphism quotient. -/
def outerProjection : MulAut (Spin n F N) →* OuterAutomorphism N :=
  QuotientGroup.mk' (innerAutomorphisms N)

/-- Precisely the E1 outer-group description, including its two generators.
The coordinates concern group automorphisms, independently of every action
on representations or blocks. -/
structure OuterCoordinates (rank : 3 ≤ n) where
  equiv : OuterAutomorphism N ≃* OuterGroup f
  diagonal : ∀ g : SpecialClifford n F,
    equiv (outerProjection N (MulAut.conjNormal (H := SpinSubgroup n F N) g)) =
      (D.diagonal g, 1)
  field : ∀ e : FieldGroup f,
    equiv (outerProjection N (spinFieldAction n F fs e)) = (1, e)

/-- Inverse pullback is a homomorphism to the opposite automorphism group. -/
def inverseAutomorphism :
    MulAut (Spin n F N) →* (MulAut (Spin n F N))ᵐᵒᵖ where
  toFun a := MulOpposite.op a⁻¹
  map_one' := by simp
  map_mul' a b := by simp

/-- Canonical quotient descent needs only containment of the inner subgroup
in the kernel; equality with the action kernel is neither asserted nor used. -/
def descend {M : Type*} [Monoid M]
    (rho : MulAut (Spin n F N) →* M)
    (inner : innerAutomorphisms N ≤ rho.ker) : OuterAutomorphism N →* M :=
  QuotientGroup.lift (innerAutomorphisms N) rho inner

@[simp] theorem descend_projection {M : Type*} [Monoid M]
    (rho : MulAut (Spin n F N) →* M)
    (inner : innerAutomorphisms N ≤ rho.ker) (a : MulAut (Spin n F N)) :
    descend N rho inner (outerProjection N a) = rho a := rfl

variable {rank : 3 ≤ n} (coordinates : OuterCoordinates N D fs rank)

include D coordinates in
/-- Every outer coset is generated by one actual diagonal and one field
coset.  This uses surjectivity of the literal diagonal map, not faithfulness. -/
theorem outer_factorization (q : OuterAutomorphism N) :
    ∃ (g : SpecialClifford n F) (e : FieldGroup f),
      q = outerProjection N (MulAut.conjNormal (H := SpinSubgroup n F N) g) *
        outerProjection N (spinFieldAction n F fs e) := by
  obtain ⟨g, hg⟩ := D.surjective (coordinates.equiv q).1
  refine ⟨g, (coordinates.equiv q).2, ?_⟩
  apply coordinates.equiv.injective
  rw [map_mul, coordinates.diagonal, coordinates.field]
  apply Prod.ext
  · simpa using hg.symm
  · simp

/-- Agreement on the two actual generators proves agreement on the literal
quotient.  All uses below supply checked formulas for separate carriers. -/
theorem descend_eq_product {M : Type*} [Monoid M]
    (rho : MulAut (Spin n F N) →* M)
    (inner : innerAutomorphisms N ≤ rho.ker)
    (product : OuterGroup f →* M)
    (diagonal : ∀ g : SpecialClifford n F,
      rho (MulAut.conjNormal (H := SpinSubgroup n F N) g) = product (D.diagonal g, 1))
    (field : ∀ e : FieldGroup f,
      rho (spinFieldAction n F fs e) = product (1, e))
    (q : OuterAutomorphism N) :
    descend N rho inner q = product (coordinates.equiv q) := by
  obtain ⟨g, e, rfl⟩ := outer_factorization N D fs coordinates q
  rw [map_mul, descend_projection, descend_projection, diagonal, field,
    map_mul, coordinates.diagonal, coordinates.field, map_mul]

section Block

variable {k : Type} [Field k]

/-- The full automorphism action on literal primitive block idempotents. -/
def automorphismBlockHom :
    MulAut (Spin n F N) →* Equiv.Perm (LiteralPrimitiveBlock k (Spin n F N)) :=
  (MulAction.toPermHom (MulAut (Spin n F N))ᵐᵒᵖ
    (LiteralPrimitiveBlock k (Spin n F N))).comp (inverseAutomorphism N)

@[simp] theorem automorphismBlockHom_apply (a : MulAut (Spin n F N))
    (b : LiteralPrimitiveBlock k (Spin n F N)) :
    automorphismBlockHom (k := k) N a b = LiteralPrimitiveBlock.rightTwistBlock b a⁻¹ := rfl

theorem block_inner : innerAutomorphisms N ≤ (automorphismBlockHom (k := k) N).ker := by
  rintro a ⟨g, rfl⟩
  change automorphismBlockHom (k := k) N (MulAut.conj g) = 1
  apply Equiv.ext
  intro b
  change MulOpposite.op ((MulAut.conj g)⁻¹) • b = b
  simpa only [map_inv] using LiteralPrimitiveBlock.inner_smul g b

/-- Natural action on the actual outer quotient, defined before coordinates. -/
def outerBlockHom : OuterAutomorphism N →* Equiv.Perm (LiteralPrimitiveBlock k (Spin n F N)) :=
  descend N (automorphismBlockHom (k := k) N) (block_inner N)

theorem outerBlockHom_coordinates (q : OuterAutomorphism N) :
    outerBlockHom (k := k) N q = effectiveBlockHom (k := k) N D fs (coordinates.equiv q) := by
  apply descend_eq_product N D fs coordinates
  · intro g
    rw [effectiveBlockHom_diagonal]
    apply Equiv.ext
    intro b
    change LiteralPrimitiveBlock.rightTwistBlock b
        ((MulAut.conjNormal (H := SpinSubgroup n F N) g)⁻¹) = _
    rw [← map_inv]
    rfl
  · intro e
    rw [effectiveBlockHom_field]
    apply Equiv.ext
    intro b
    change LiteralPrimitiveBlock.rightTwistBlock b ((spinFieldAction n F fs e)⁻¹) = _
    rw [← map_inv]
    rfl

end Block

section Ordinary

variable {K : Type} [Field K] [CharZero K]

/-- The literal full automorphism permutation of function-valued Irr. -/
def automorphismOrdinaryHom :
    MulAut (Spin n F N) →* Equiv.Perm (OrdinaryIrreducibleCharacter.Irr K (Spin n F N)) := by
  letI := OddGFactorizationLemma312Relative.OrdinaryAction.oppositeAutomorphismAction
    (K := K) (G := Spin n F N)
  exact (MulAction.toPermHom (MulAut (Spin n F N))ᵐᵒᵖ
    (OrdinaryIrreducibleCharacter.Irr K (Spin n F N))).comp (inverseAutomorphism N)

@[simp] theorem automorphismOrdinaryHom_apply (a : MulAut (Spin n F N))
    (chi : OrdinaryIrreducibleCharacter.Irr K (Spin n F N)) :
    automorphismOrdinaryHom (K := K) N a chi =
      OrdinaryIrreducibleCharacter.twist K (Spin n F N) chi a⁻¹ := rfl

theorem ordinary_inner : innerAutomorphisms N ≤ (automorphismOrdinaryHom (K := K) N).ker := by
  rintro a ⟨g, rfl⟩
  change automorphismOrdinaryHom (K := K) N (MulAut.conj g) = 1
  apply Equiv.ext
  intro chi
  rw [automorphismOrdinaryHom_apply, ← map_inv]
  exact ordinaryTwist_inner chi g⁻¹

def outerOrdinaryHom :
    OuterAutomorphism N →* Equiv.Perm (OrdinaryIrreducibleCharacter.Irr K (Spin n F N)) :=
  descend N (automorphismOrdinaryHom (K := K) N) (ordinary_inner N)

theorem outerOrdinaryHom_coordinates (q : OuterAutomorphism N) :
    outerOrdinaryHom (K := K) N q = effectiveOrdinaryHom (k := K) N D fs (coordinates.equiv q) := by
  apply descend_eq_product N D fs coordinates
  · intro g
    rw [effectiveOrdinaryHom_diagonal]
    apply Equiv.ext
    intro chi
    rw [automorphismOrdinaryHom_apply, ← map_inv]
    rfl
  · intro e
    rw [effectiveOrdinaryHom_field]
    apply Equiv.ext
    intro chi
    rw [automorphismOrdinaryHom_apply, ← map_inv]
    rfl

end Ordinary

section Brauer

variable {ell : ℕ} {k K : Type} [Field k] [Field K] [CharZero K]
  [CharP k ell] [IsAlgClosed k] [Finite (Spin n F N)]
  (iota : PrimeRegularRootEmbedding ell k K (Spin n F N))

def automorphismBrauerHom : MulAut (Spin n F N) →* Equiv.Perm (IBr iota) :=
  (MulAction.toPermHom (MulAut (Spin n F N))ᵐᵒᵖ (IBr iota)).comp (inverseAutomorphism N)

@[simp] theorem automorphismBrauerHom_apply (a : MulAut (Spin n F N)) (phi : IBr iota) :
    automorphismBrauerHom N iota a phi = IrreducibleBrauerCharacter.twist iota phi a⁻¹ := rfl

theorem brauer_inner : innerAutomorphisms N ≤ (automorphismBrauerHom N iota).ker := by
  rintro a ⟨g, rfl⟩
  change automorphismBrauerHom N iota (MulAut.conj g) = 1
  apply Equiv.ext
  intro phi
  rw [automorphismBrauerHom_apply, ← map_inv]
  exact IrreducibleBrauerCharacter.twist_eq_self_of_underlying iota phi
    (MulAut.conj g⁻¹) (PrimeRegularClassFunction.twist_conj phi.val g⁻¹)

def outerBrauerHom : OuterAutomorphism N →* Equiv.Perm (IBr iota) :=
  descend N (automorphismBrauerHom N iota) (brauer_inner N iota)

theorem outerBrauerHom_coordinates (q : OuterAutomorphism N) :
    outerBrauerHom N iota q = effectiveBrauerHom N D fs iota (coordinates.equiv q) := by
  apply descend_eq_product N D fs coordinates
  · intro g
    rw [effectiveBrauerHom_diagonal]
    apply Equiv.ext
    intro phi
    rw [automorphismBrauerHom_apply, ← map_inv]
    rfl
  · intro e
    rw [effectiveBrauerHom_field]
    apply Equiv.ext
    intro phi
    rw [automorphismBrauerHom_apply, ← map_inv]
    rfl

end Brauer

section KZero

variable {k : Type} [Field k]

def automorphismKZeroAction :
    Representation ℤ (MulAut (Spin n F N)) (FDRepKZero k (Spin n F N)) :=
  (twistKZeroRepresentation (k := k) (G := Spin n F N)).comp (inverseAutomorphism N)

@[simp] theorem automorphismKZeroAction_apply (a : MulAut (Spin n F N))
    (x : FDRepKZero k (Spin n F N)) :
    automorphismKZeroAction (k := k) N a x = twistKZero (k := k) a⁻¹ x := rfl

theorem kzero_inner : innerAutomorphisms N ≤ (automorphismKZeroAction (k := k) N).ker := by
  rintro a ⟨g, rfl⟩
  change automorphismKZeroAction (k := k) N (MulAut.conj g) = 1
  apply LinearMap.ext
  intro x
  rw [automorphismKZeroAction_apply, ← map_inv]
  exact twistKZero_inner_apply g⁻¹ x

def outerKZeroAction : Representation ℤ (OuterAutomorphism N) (FDRepKZero k (Spin n F N)) :=
  descend N (automorphismKZeroAction (k := k) N) (kzero_inner N)

theorem automorphismKZeroAction_diagonal (g : SpecialClifford n F) :
    automorphismKZeroAction (k := k) N
        (MulAut.conjNormal (H := SpinSubgroup n F N) g) =
      effectiveKZeroAction (k := k) N D fs (D.diagonal g, 1) := by
  apply LinearMap.ext
  intro x
  rw [automorphismKZeroAction_apply, ← map_inv]
  exact (effectiveKZeroAction_diagonal_apply (k := k) N D fs g x).symm

theorem automorphismKZeroAction_field (e : FieldGroup f) :
    automorphismKZeroAction (k := k) N (spinFieldAction n F fs e) =
      effectiveKZeroAction (k := k) N D fs (1, e) := by
  apply LinearMap.ext
  intro x
  rw [automorphismKZeroAction_apply, ← map_inv]
  exact (effectiveKZeroAction_field_apply (k := k) N D fs e x).symm

theorem outerKZeroAction_coordinates (q : OuterAutomorphism N) :
    outerKZeroAction (k := k) N q = effectiveKZeroAction (k := k) N D fs (coordinates.equiv q) :=
  descend_eq_product N D fs coordinates
    (automorphismKZeroAction (k := k) N) (kzero_inner N)
    (effectiveKZeroAction (k := k) N D fs)
    (automorphismKZeroAction_diagonal N D fs)
    (automorphismKZeroAction_field N D fs) q

end KZero

section Stabilizer

variable {k : Type} [Field k] [Finite (Spin n F N)]
  (b : LiteralPrimitiveBlock k (Spin n F N))

/-- The natural inverse-pullback action of the full group Aut(Spin). -/
@[instance_reducible] def automorphismBlockAction :
    MulAction (MulAut (Spin n F N)) (LiteralPrimitiveBlock k (Spin n F N)) :=
  MulAction.compHom _ (automorphismBlockHom (k := k) N)

/-- The literal full automorphism stabilizer, before quotienting. -/
def blockStabilizer : Subgroup (MulAut (Spin n F N)) :=
  @MulAction.stabilizer _ _ _ (automorphismBlockAction (k := k) N) b

theorem inner_le_blockStabilizer : innerAutomorphisms N ≤ blockStabilizer N b := by
  intro a ha
  change automorphismBlockHom (k := k) N a b = b
  have h := block_inner (k := k) N ha
  change automorphismBlockHom (k := k) N a = 1 at h
  rw [h]
  rfl

/-- Inn(Spin) as a subgroup of Aut(Spin)_B, by its literal inclusion. -/
def blockInner : Subgroup (blockStabilizer N b) :=
  (innerAutomorphisms N).comap (blockStabilizer N b).subtype

instance blockInner_normal : (blockInner N b).Normal := inferInstanceAs
  ((innerAutomorphisms N).comap (blockStabilizer N b).subtype).Normal

/-- Exactly the group J_B in the current manuscript, with no effective
action quotient substituted for its denominator. -/
abbrev BlockQuotient := blockStabilizer N b ⧸ blockInner N b

/-- The product stabilizer used by the sealed Spin Conlon endpoint. -/
def productBlockStabilizer : Subgroup (OuterGroup f) :=
  @MulAction.stabilizer _ _ _
    (TypeBSpinEffectiveSourceBinding.blockAction (k := k) N D fs) b

def stabilizerCoordinates : blockStabilizer N b →* productBlockStabilizer N D fs b where
  toFun a := ⟨coordinates.equiv (outerProjection N a.val), by
    change effectiveBlockHom (k := k) N D fs (coordinates.equiv (outerProjection N a.val)) b = b
    rw [← outerBlockHom_coordinates N D fs coordinates]
    exact a.property⟩
  map_one' := by apply Subtype.ext; simp
  map_mul' a c := by apply Subtype.ext; simp

theorem stabilizerCoordinates_surjective :
    Function.Surjective (stabilizerCoordinates N D fs coordinates b) := by
  intro c
  obtain ⟨a, ha⟩ := QuotientGroup.mk'_surjective (innerAutomorphisms N)
    (coordinates.equiv.symm c.val)
  have hc : coordinates.equiv (outerProjection N a) = c.val := by
    change coordinates.equiv (QuotientGroup.mk' (innerAutomorphisms N) a) = c.val
    rw [ha, MulEquiv.apply_symm_apply]
  have hfix : a ∈ blockStabilizer N b := by
    change automorphismBlockHom (k := k) N a b = b
    change outerBlockHom (k := k) N (outerProjection N a) b = b
    rw [outerBlockHom_coordinates N D fs coordinates, hc]
    exact c.property
  exact ⟨⟨a, hfix⟩, Subtype.ext hc⟩

theorem stabilizerCoordinates_kernel :
    (stabilizerCoordinates N D fs coordinates b).ker = blockInner N b := by
  ext a
  change (⟨coordinates.equiv (outerProjection N a.val), _⟩ : productBlockStabilizer N D fs b) = 1 ↔
    a.val ∈ innerAutomorphisms N
  constructor
  · intro h
    have hq : outerProjection N a.val = 1 := coordinates.equiv.injective (by
      simpa using congrArg Subtype.val h)
    exact (QuotientGroup.eq_one_iff a.val).mp hq
  · intro h
    apply Subtype.ext
    have hq : outerProjection N a.val = 1 := (QuotientGroup.eq_one_iff a.val).mpr h
    simp only [hq, map_one, OneMemClass.coe_one]

/-- The first isomorphism theorem on the full block stabilizer supplies the
literal quotient identification needed by the revised lemma. -/
def blockQuotientEquiv : BlockQuotient N b ≃* productBlockStabilizer N D fs b :=
  QuotientGroup.liftEquiv (blockInner N b)
    (stabilizerCoordinates_surjective N D fs coordinates b)
    (stabilizerCoordinates_kernel N D fs coordinates b).symm

@[simp] theorem blockQuotientEquiv_mk (a : blockStabilizer N b) :
    blockQuotientEquiv N D fs coordinates b (QuotientGroup.mk' (blockInner N b) a) =
      stabilizerCoordinates N D fs coordinates b a := rfl

/-- All natural quotient actions use this same outer coset. -/
def blockQuotientToOuter : BlockQuotient N b →* OuterAutomorphism N :=
  QuotientGroup.lift (blockInner N b)
    ((outerProjection N).comp (blockStabilizer N b).subtype) (by
      intro a ha
      exact (QuotientGroup.eq_one_iff a.val).mpr ha)

theorem blockQuotient_coordinates (a : BlockQuotient N b) :
    coordinates.equiv (blockQuotientToOuter N b a) =
      (blockQuotientEquiv N D fs coordinates b a).val := by
  refine QuotientGroup.induction_on a fun g => ?_
  rfl

/-- The exact field projection on Aut(Spin)_B/Inn(Spin). -/
def blockQuotientField : BlockQuotient N b →* FieldGroup f :=
  (MonoidHom.snd _ _).comp
    ((productBlockStabilizer N D fs b).subtype.comp
      (blockQuotientEquiv N D fs coordinates b).toMonoidHom)

def blockQuotientKernelDiagonal :
    (blockQuotientField N D fs coordinates b).ker →* DiagonalGroup :=
  (MonoidHom.fst _ _).comp
    (((productBlockStabilizer N D fs b).subtype.comp
      (blockQuotientEquiv N D fs coordinates b).toMonoidHom).comp
        (blockQuotientField N D fs coordinates b).ker.subtype)

theorem blockQuotientKernelDiagonal_injective :
    Function.Injective (blockQuotientKernelDiagonal N D fs coordinates b) := by
  intro x y h
  apply Subtype.ext
  apply (blockQuotientEquiv N D fs coordinates b).injective
  apply Subtype.ext
  apply Prod.ext
  · exact h
  · exact x.property.trans y.property.symm

variable [NeZero f]

include coordinates in
/-- The manuscript conclusion for the actual group Aut(Spin)_B/Inn(Spin).
No action is required to be faithful, and its kernel is never identified
with Inn(Spin). -/
theorem blockQuotient_twoHypoelementary :
    IntegralBasicSetBridge.IsPHypoelementary 2 (BlockQuotient N b) := by
  let h := blockQuotientField N D fs coordinates b
  have small : Nat.card h.ker ≤ 2 := by
    have hc := Nat.card_le_card_of_injective
      (blockQuotientKernelDiagonal N D fs coordinates b)
      (blockQuotientKernelDiagonal_injective N D fs coordinates b)
    simpa only [Nat.card_eq_fintype_card, Fintype.card_multiplicative, ZMod.card] using hc
  let emb : BlockQuotient N b ⧸ h.ker →* FieldGroup f :=
    h.range.subtype.comp (QuotientGroup.quotientKerEquivRange h).toMonoidHom
  exact ManuscriptVerification.ConlonStabilizerBridge.isTwoHypoelementary_of_small_normal_quotient_embedding
    h.ker small emb
    (h.range.subtype_injective.comp (QuotientGroup.quotientKerEquivRange h).injective)

end Stabilizer

end ModularRep.PaperProofs.TypeBOddPrimeSpinOuterQuotient


/-
This file is part of ModularRep, the Lean companion to
Baoyu Zhang (2026), "On the inductive blockwise Alperin weight condition
for type B and type C".

The formalisation checks selected arguments under explicit external
assumptions. See FORMALISATION_GUIDE.md in the package root.
-/
