import ModularRep.PaperProofs.TypeBConformalDualCarriers
import ModularRep.PaperProofs.TypeBRegularLeviCliffordBinding
import ModularRep.PaperProofs.TypeBRankThreeFactorsDiagram
import Mathlib.Data.Fintype.Powerset

/-!
# Paired root charts on the original rank-three algebraic points

The primal group is the literal special Clifford group, with its specified
Spin subgroup. The dual group is the literal PCSp quotient. Positive and
negative root maps, coroot maps, their torus conjugation equations and their
generated subgroups bind the two charts to these carriers. The dual Cartan
matrix is the transpose of the primal B3 matrix. The selected dual generated
subgroup is exactly the retained Levi, and full charts generate the original
groups. Properness is deduced from these equations and selected-root support.

E1/U boundary: the current point-group library does not define algebraic
pinnings or their root datum. The maps below must be the actual paired
pinnings, with the displayed torus and root-generation identifications.
Their algebraic authentication is the standard paired-Levi/root-datum input,
not a consequence of the displayed group equations alone. The geometric
component product is the standard product of the simply connected derived
Levi components. Its coordinates, single-coordinate inclusions, and original
Frobenius transport are retained explicitly. Component labels are computed
connected root sets, not an independently chosen factor carrier.

The original component permutation is an input; its identification with the
root action is checked in the same source. Diagram invariance then proves
that permutation is the identity. The one-step component Frobenius maps and
their diagonal coordinate equations are constructed afterwards. No rational
product, six-case inventory, component nonpermutation, character data or
block conclusion is a source field. Finite descent uses only the existing
CliffordFixedPointSource, with no central decomposition or intersection data.
-/

noncomputable section
set_option autoImplicit false

namespace ModularRep.PaperProofs.TypeBRankThreeFactorsPointSource

open TypeBConformalDualCarriers TypeBRegularLeviRationalCarriers
open TypeBCliffordCarriers TypeBRankThreeFactorsDiagram

variable (A G : Type) [Field A] [Group G]

/-- Actual simple root maps and coroots, in root-row/coroot-column convention. -/
structure RootChart (matrix : Node → Node → ℤ) where
  torus : Subgroup G
  positive : Node → Multiplicative A →* G
  negative : Node → Multiplicative A →* G
  positive_injective : ∀ i, Function.Injective (positive i)
  negative_injective : ∀ i, Function.Injective (negative i)
  coroot : Node → Aˣ →* G
  coroot_in_torus : ∀ i, (coroot i).range ≤ torus
  positive_pairing : ∀ i j (t : Aˣ) (u : A),
    coroot i t * positive j (Multiplicative.ofAdd u) * (coroot i t)⁻¹ =
      positive j (Multiplicative.ofAdd ((↑(t ^ matrix j i) : A) * u))
  negative_pairing : ∀ i j (t : Aˣ) (u : A),
    coroot i t * negative j (Multiplicative.ofAdd u) * (coroot i t)⁻¹ =
      negative j (Multiplicative.ofAdd ((↑(t ^ (-matrix j i)) : A) * u))

namespace RootChart

variable {A G} {matrix : Node → Node → ℤ} (chart : RootChart A G matrix)

def rootGroup (i : Node) : Subgroup G :=
  (chart.positive i).range ⊔ (chart.negative i).range

/-- Generated by the actual torus and both signs of the selected simple roots. -/
def levi (J : Finset Node) : Subgroup G :=
  chart.torus ⊔ ⨆ i ∈ J, chart.rootGroup i

theorem levi_mono {J K : Finset Node} (h : J ⊆ K) : chart.levi J ≤ chart.levi K := by
  apply sup_le_sup le_rfl
  refine iSup_le fun i => iSup_le fun hi => ?_
  exact le_iSup_of_le i (le_iSup_of_le (h hi) le_rfl)

theorem positive_le_levi {J : Finset Node} {i : Node} (hi : i ∈ J) :
    (chart.positive i).range ≤ chart.levi J := by
  have root_le : chart.rootGroup i ≤ ⨆ j ∈ J, chart.rootGroup j :=
    le_iSup_of_le i (le_iSup_of_le hi le_rfl)
  exact (le_sup_left.trans root_le).trans le_sup_right

/-- Semisimple root generation, without the Levi torus. -/
def rootGenerated (S : Set Node) : Subgroup G := ⨆ i ∈ S, chart.rootGroup i

end RootChart

variable {A} (Nbar : NormSource 3 A) (Lstar : Subgroup (PCSp A 3))

/-- A common based chart, on actual primal and dual point groups.
The one-way support field is root recognition inside the selected generated
Levi; it does not state that the selected Levi is proper. -/
structure PairedChart where
  selected : Finset Node
  primal : RootChart A (SpecialClifford 3 A) cartan
  dual : RootChart A (PCSp A 3) (fun i j => cartan j i)
  dual_selected : dual.levi selected = Lstar
  dual_full : dual.levi Finset.univ = ⊤
  primal_full : primal.levi Finset.univ = SpinSubgroup 3 A Nbar
  primal_support : ∀ i, (primal.positive i).range ≤ primal.levi selected → i ∈ selected

namespace PairedChart

variable {Nbar Lstar} (chart : PairedChart Nbar Lstar)

abbrev primalLevi : Subgroup (SpecialClifford 3 A) := chart.primal.levi chart.selected

theorem selected_proper (proper : Lstar ≠ ⊤) : chart.selected ≠ Finset.univ := by
  intro h
  apply proper
  rw [← chart.dual_selected, h, chart.dual_full]

theorem primalLevi_le_spin : chart.primalLevi ≤ SpinSubgroup 3 A Nbar := by
  rw [← chart.primal_full]
  exact chart.primal.levi_mono (Finset.subset_univ _)

theorem primalLevi_ne_spin (proper : Lstar ≠ ⊤) :
    chart.primalLevi ≠ SpinSubgroup 3 A Nbar := by
  intro h
  apply chart.selected_proper proper
  apply Finset.eq_univ_of_forall
  intro i
  apply chart.primal_support i
  rw [show chart.primal.levi chart.selected = SpinSubgroup 3 A Nbar from h,
    ← chart.primal_full]
  exact chart.primal.positive_le_levi (Finset.mem_univ i)

theorem primalLevi_lt_spin (proper : Lstar ≠ ⊤) :
    chart.primalLevi < SpinSubgroup 3 A Nbar :=
  lt_of_le_of_ne chart.primalLevi_le_spin (chart.primalLevi_ne_spin proper)

end PairedChart

/-- Literal nonempty connected root sets of the selected diagram. -/
def ComponentIndex (J : Finset Node) : Type :=
  {S : Set Node // ∃ i, i ∈ J ∧ S = component J i}

instance componentIndexFinite (J : Finset Node) : Finite (ComponentIndex J) :=
  inferInstanceAs (Finite {S : Set Node // ∃ i, i ∈ J ∧ S = component J i})

local instance componentIndexDecidableEq (J : Finset Node) : DecidableEq (ComponentIndex J) :=
  Classical.decEq _

/-- Restrict the same point automorphism to a setwise invariant subgroup. -/
def restrictAutomorphism {H : Type} [Group H] (Frob : MulAut H) (U : Subgroup H)
    (stable : U.map Frob.toMonoidHom = U) : MulAut U where
  toFun x := ⟨Frob x, by
    have hx : Frob (x : H) ∈ U.map Frob.toMonoidHom :=
      Subgroup.mem_map_of_mem Frob.toMonoidHom x.property
    rw [stable] at hx
    exact hx⟩
  invFun x := ⟨Frob.symm x, by
    have hx : (x : H) ∈ U.map Frob.toMonoidHom := by
      rw [stable]
      exact x.property
    obtain ⟨y, hy, hxy⟩ := hx
    have heq : Frob.symm (x : H) = y := by
      apply Frob.injective
      exact (Frob.apply_symm_apply (x : H)).trans hxy.symm
    rw [heq]
    exact hy⟩
  left_inv x := Subtype.ext (Frob.symm_apply_apply x)
  right_inv x := Subtype.ext (Frob.apply_symm_apply x)
  map_mul' x y := Subtype.ext (Frob.map_mul x y)

@[simp] theorem restrictAutomorphism_value {H : Type} [Group H]
    (Frob : MulAut H) (U : Subgroup H) (stable : U.map Frob.toMonoidHom = U) (x : U) :
    (restrictAutomorphism Frob U stable x : H) = Frob x := rfl

variable {Nbar Lstar} (chart : PairedChart Nbar Lstar)
variable (Frob : MulAut (SpecialClifford 3 A))
variable (stable : chart.primalLevi.map Frob.toMonoidHom = chart.primalLevi)

/-- The original Frobenius on the actual geometric derived subgroup. -/
def derivedFrobenius : MulAut (derivedLevi chart.primalLevi) :=
  restrictAutomorphism Frob (derivedLevi chart.primalLevi)
    (derivedLevi_map chart.primalLevi Frob stable)

/-- The component subgroup is computed from its actual connected root set. -/
def geometricComponent (c : ComponentIndex chart.selected) :
    Subgroup (derivedLevi chart.primalLevi) :=
  (chart.primal.rootGenerated c.val).subgroupOf (derivedLevi chart.primalLevi)

/-- Raw geometric product and Frobenius data, before component invariance.
The coordinate transport contains the original component permutation. -/
structure ComponentSource where
  action : SelectedAction chart.selected
  positive_transport : ∀ i, i ∈ chart.selected →
    ((chart.primal.positive i).range).map Frob.toMonoidHom =
      (chart.primal.positive (action.permutation i)).range
  negative_transport : ∀ i, i ∈ chart.selected →
    ((chart.primal.negative i).range).map Frob.toMonoidHom =
      (chart.primal.negative (action.permutation i)).range
  permutation : Equiv.Perm (ComponentIndex chart.selected)
  roots_transport : ∀ c, (permutation c).val = action.permutation '' c.val
  component_le : ∀ c : ComponentIndex chart.selected,
    chart.primal.rootGenerated c.val ≤ derivedLevi chart.primalLevi
  coordinates : derivedLevi chart.primalLevi ≃*
    ((c : ComponentIndex chart.selected) → geometricComponent chart c)
  inclusion : ∀ c (x : geometricComponent chart c),
    coordinates.symm (Function.update 1 c x) = (x : derivedLevi chart.primalLevi)
  coordinate_transport : ∀ h c,
    (coordinates (derivedFrobenius chart Frob stable h) (permutation c) :
      derivedLevi chart.primalLevi) =
      derivedFrobenius chart Frob stable (coordinates h c : derivedLevi chart.primalLevi)

namespace ComponentSource

variable {chart Frob stable} (source : ComponentSource chart Frob stable)

include source in
/-- No part of a root-generated component is lost by its subtype carrier. -/
theorem geometricComponent_map (c : ComponentIndex chart.selected) :
    (geometricComponent chart c).map (derivedLevi chart.primalLevi).subtype =
      chart.primal.rootGenerated c.val :=
  Subgroup.map_subgroupOf_eq_of_le (source.component_le c)

theorem permutation_fixed (c : ComponentIndex chart.selected) : source.permutation c = c := by
  apply Subtype.ext
  rw [source.roots_transport]
  obtain ⟨i, hi, hroot⟩ := c.property
  rw [hroot]
  exact source.action.component_image i

theorem permutation_eq_one : source.permutation = 1 := by
  ext c
  exact source.permutation_fixed c

theorem coordinate_transport_fixed (h : derivedLevi chart.primalLevi)
    (c : ComponentIndex chart.selected) :
    (source.coordinates (derivedFrobenius chart Frob stable h) c :
      derivedLevi chart.primalLevi) =
      derivedFrobenius chart Frob stable (source.coordinates h c : derivedLevi chart.primalLevi) := by
  have changeIndex :
      (source.coordinates (derivedFrobenius chart Frob stable h) (source.permutation c) :
        derivedLevi chart.primalLevi) =
      (source.coordinates (derivedFrobenius chart Frob stable h) c :
        derivedLevi chart.primalLevi) :=
    congrArg (fun d : ComponentIndex chart.selected =>
      (source.coordinates (derivedFrobenius chart Frob stable h) d :
        derivedLevi chart.primalLevi)) (source.permutation_fixed c)
  exact changeIndex.symm.trans (source.coordinate_transport h c)

theorem inclusion_coordinate (c : ComponentIndex chart.selected) (x : geometricComponent chart c) :
    source.coordinates (x : derivedLevi chart.primalLevi) c = x := by
  classical
  rw [← source.inclusion c x, MulEquiv.apply_symm_apply, Function.update_self]

/-- The same original point map, now proved to preserve this actual component. -/
def componentHom (c : ComponentIndex chart.selected) :
    geometricComponent chart c →* geometricComponent chart c where
  toFun x := ⟨derivedFrobenius chart Frob stable (x : derivedLevi chart.primalLevi), by
    have hx := source.coordinate_transport_fixed (x : derivedLevi chart.primalLevi) c
    rw [source.inclusion_coordinate c x] at hx
    exact hx ▸ (source.coordinates (derivedFrobenius chart Frob stable x) c).property⟩
  map_one' := Subtype.ext (map_one (derivedFrobenius chart Frob stable))
  map_mul' x y := Subtype.ext ((derivedFrobenius chart Frob stable).map_mul x y)

theorem componentHom_bijective (c : ComponentIndex chart.selected) :
    Function.Bijective (source.componentHom c) := by
  constructor
  · intro x y h
    apply Subtype.ext
    apply (derivedFrobenius chart Frob stable).injective
    exact congrArg Subtype.val h
  · intro x
    let h := (derivedFrobenius chart Frob stable).symm (x : derivedLevi chart.primalLevi)
    refine ⟨source.coordinates h c, ?_⟩
    apply Subtype.ext
    change derivedFrobenius chart Frob stable
      (source.coordinates h c : derivedLevi chart.primalLevi) = (x : derivedLevi chart.primalLevi)
    calc
      _ = (source.coordinates (derivedFrobenius chart Frob stable h) c :
          derivedLevi chart.primalLevi) := (source.coordinate_transport_fixed h c).symm
      _ = (source.coordinates (x : derivedLevi chart.primalLevi) c :
          derivedLevi chart.primalLevi) := by rw [show derivedFrobenius chart Frob stable h = x from
            (derivedFrobenius chart Frob stable).apply_symm_apply x]
      _ = x := congrArg Subtype.val (source.inclusion_coordinate c x)

def componentFrobenius (c : ComponentIndex chart.selected) : MulAut (geometricComponent chart c) :=
  MulEquiv.ofBijective (source.componentHom c) (source.componentHom_bijective c)

@[simp] theorem componentFrobenius_value (c : ComponentIndex chart.selected)
    (x : geometricComponent chart c) :
    (source.componentFrobenius c x : derivedLevi chart.primalLevi) =
      derivedFrobenius chart Frob stable x := rfl

/-- The diagonal law is derived after root-set nonpermutation. -/
theorem coordinateEquation (h : derivedLevi chart.primalLevi) (c : ComponentIndex chart.selected) :
    source.coordinates (derivedFrobenius chart Frob stable h) c =
      source.componentFrobenius c (source.coordinates h c) := by
  apply Subtype.ext
  exact source.coordinate_transport_fixed h c

end ComponentSource

/-- The actual derived fixed points, with no change of their ambient values. -/
def fixedDerivedEquivL0 : fixedPoints (derivedFrobenius chart Frob stable).toMonoidHom ≃*
    L0 Frob.toMonoidHom chart.primalLevi :=
  fixedPointsRestrictionEquiv Frob.toMonoidHom (derivedLevi chart.primalLevi) (by
    intro x hx
    have h := Subgroup.mem_map_of_mem Frob.toMonoidHom hx
    rw [derivedLevi_map chart.primalLevi Frob stable] at h
    exact h)

@[simp] theorem fixedDerivedEquivL0_value
    (x : fixedPoints (derivedFrobenius chart Frob stable).toMonoidHom) :
    (fixedDerivedEquivL0 chart Frob stable x).val.val = x.val.val := rfl

section FiniteDescent

variable {F : Type} [Field F] [Finite F] (p f : ℕ) [CharP F p] [Algebra F A]
variable (N : NormSource 3 F)
variable (points : CliffordFixedPointSource 3 p f F A N Nbar Frob)

/-- The original finite subgroup, obtained by the fixed base-change inclusion. -/
abbrev finiteDerived :=
  TypeBRegularLeviCliffordBinding.finiteSubgroup 3 p f F A N Nbar Frob points
    (derivedLevi chart.primalLevi)

/-- The existing same-point descent applies to the computed derived Levi. -/
def finiteDerivedEquivL0 : finiteDerived chart Frob p f N points ≃*
    L0 Frob.toMonoidHom chart.primalLevi :=
  TypeBRegularLeviCliffordBinding.finiteSubgroupEquiv 3 p f F A N Nbar Frob points
    (derivedLevi chart.primalLevi)

@[simp] theorem finiteDerivedEquivL0_value (x : finiteDerived chart Frob p f N points) :
    (finiteDerivedEquivL0 chart Frob p f N points x).val.val = points.inclusion x.val := rfl

end FiniteDescent

/-- On the selected rank-three diagrams the graph action is its own inverse.
This is a finite deduction, not a convention identifying arbitrary Weyl actions. -/
theorem selectedAction_inverse_eq {J : Finset Node} (action : SelectedAction J) :
    action.permutation.symm = action.permutation := by
  rcases action.permutation_eq_one_or_swap with h | h
  · rw [h]
    rfl
  · rw [h]
    exact Equiv.symm_swap 0 1

/-- Rational pairing on the same selected semisimple root data.

Both maps are the original point Frobenius maps. The consumer supplies the
exact dual coordinate Frobenius from the retained dual-Levi construction.
The parameter is Nat.card F, with p^f equality from the SAME Clifford point
source. Each signed root parameter may have its displayed nonzero pinning
scale. Coroot parameters have the actual q-power square without a scale.

The dual index is explicitly the inverse of the primal index. This retains
the opposite Weyl correspondence of Digne--Michel 11.1.12 and the paragraph
after 11.4.1; selectedAction_inverse_eq subsequently identifies these graph
indices in this rank. It is not an identification of arbitrary Weyl actions.
The specified paired pinning and full central-torus lattice authentication
remain U. In particular these selected semisimple equations do not compute
the rational type of the Levi centre. There is no pointwise group duality
map between the primal and dual groups, and no finite factor form is given.
-/
structure RationalPairingSource (p f : ℕ) {F : Type} [Field F] [Finite F]
    [CharP F p] [Algebra F A] (N : NormSource 3 F)
    (points : CliffordFixedPointSource 3 p f F A N Nbar Frob)
    (components : ComponentSource chart Frob stable)
    (dualFrob : MulAut (PCSp A 3)) where
  primalPositiveScale : Node → Aˣ
  primalNegativeScale : Node → Aˣ
  dualPositiveScale : Node → Aˣ
  dualNegativeScale : Node → Aˣ
  primal_positive : ∀ i, i ∈ chart.selected → ∀ u : A,
    Frob (chart.primal.positive i (Multiplicative.ofAdd u)) =
      chart.primal.positive (components.action.permutation i)
        (Multiplicative.ofAdd ((primalPositiveScale i : A) * u ^ Nat.card F))
  primal_negative : ∀ i, i ∈ chart.selected → ∀ u : A,
    Frob (chart.primal.negative i (Multiplicative.ofAdd u)) =
      chart.primal.negative (components.action.permutation i)
        (Multiplicative.ofAdd ((primalNegativeScale i : A) * u ^ Nat.card F))
  primal_coroot : ∀ i, i ∈ chart.selected → ∀ t : Aˣ,
    Frob (chart.primal.coroot i t) =
      chart.primal.coroot (components.action.permutation i) (t ^ Nat.card F)
  dual_positive : ∀ i, i ∈ chart.selected → ∀ u : A,
    dualFrob (chart.dual.positive i (Multiplicative.ofAdd u)) =
      chart.dual.positive (components.action.permutation.symm i)
        (Multiplicative.ofAdd ((dualPositiveScale i : A) * u ^ Nat.card F))
  dual_negative : ∀ i, i ∈ chart.selected → ∀ u : A,
    dualFrob (chart.dual.negative i (Multiplicative.ofAdd u)) =
      chart.dual.negative (components.action.permutation.symm i)
        (Multiplicative.ofAdd ((dualNegativeScale i : A) * u ^ Nat.card F))
  dual_coroot : ∀ i, i ∈ chart.selected → ∀ t : Aˣ,
    dualFrob (chart.dual.coroot i t) =
      chart.dual.coroot (components.action.permutation.symm i) (t ^ Nat.card F)

namespace RationalPairingSource

variable {p f : ℕ} {F : Type} [Field F] [Finite F] [CharP F p] [Algebra F A]
variable {N : NormSource 3 F}
variable {points : CliffordFixedPointSource 3 p f F A N Nbar Frob}
variable {components : ComponentSource chart Frob stable} {dualFrob : MulAut (PCSp A 3)}
variable (pairing : RationalPairingSource chart Frob stable p f N points components dualFrob)

include pairing in
theorem parameter_eq : Nat.card F = p ^ f := points.parameters.cardinality

/-- The same root index after the proved rank-three inverse identification. -/
theorem dual_positive_same_action (i : Node) (hi : i ∈ chart.selected) (u : A) :
    dualFrob (chart.dual.positive i (Multiplicative.ofAdd u)) =
      chart.dual.positive (components.action.permutation i)
        (Multiplicative.ofAdd ((pairing.dualPositiveScale i : A) * u ^ Nat.card F)) := by
  simpa only [selectedAction_inverse_eq components.action] using pairing.dual_positive i hi u

theorem dual_negative_same_action (i : Node) (hi : i ∈ chart.selected) (u : A) :
    dualFrob (chart.dual.negative i (Multiplicative.ofAdd u)) =
      chart.dual.negative (components.action.permutation i)
        (Multiplicative.ofAdd ((pairing.dualNegativeScale i : A) * u ^ Nat.card F)) := by
  simpa only [selectedAction_inverse_eq components.action] using pairing.dual_negative i hi u

include pairing in
theorem dual_coroot_same_action (i : Node) (hi : i ∈ chart.selected) (t : Aˣ) :
    dualFrob (chart.dual.coroot i t) =
      chart.dual.coroot (components.action.permutation i) (t ^ Nat.card F) := by
  simpa only [selectedAction_inverse_eq components.action] using pairing.dual_coroot i hi t

end RationalPairingSource

end ModularRep.PaperProofs.TypeBRankThreeFactorsPointSource


/-
This file is part of ModularRep, the Lean companion to
Baoyu Zhang (2026), "On the inductive blockwise Alperin weight condition
for type B and type C".

The formalisation checks selected arguments under explicit external
assumptions. See FORMALISATION_GUIDE.md in the package root.
-/
