import ModularRep.PaperProofs.TypeBIndexTwoAmbientCommutator

/-!
# Every conjugate extends on the original two inertia groups

For a normal base of index two, the checked natural-action calculation
identifies the full inertia of every left-factor conjugate with the original
inertia. The cyclic extension theorem then applies on two fixed subgroups:
the original left-factor inertia and the subgroup generated by the base
and the original field inertia.

The character uses inverse conjugation, as required by the existing right
action. Only the character varies with the conjugating element. Both target
groups and the prescribed base root remain fixed. No extension, matching,
field fixation or block-triple witness is a new source input.
-/

noncomputable section
set_option autoImplicit false

namespace ModularRep.PaperProofs.TypeBCommonConjugateGlobalExtensions

open ModularRep TypeBCriterionHypotheses
open TypeBGlobalExtensionBinding TypeBLocalOrdinaryGeometry

variable {ell : ℕ} {k K M E : Type}
  [Field k] [Field K] [CharP k ell] [IsAlgClosed k] [CharZero K]
  [Group M] [Finite M] [Group E] [Finite E]
  (G : Subgroup M) [G.Normal] (field : E →* MulAut M)
  (action : NaturalAction G field) (indexTwo : G.index = 2)
  (iota : PrimeRegularRootEmbedding ell k K G)

/-- The actual left-factor action on the prescribed base character. -/
def conjugateCharacter (phi : IBr iota) (m : M) : IBr iota :=
  IrreducibleBrauerCharacter.twist iota phi (MulAut.conjNormal (H := G) m⁻¹)

/-- This subgroup is computed from the original character, before conjugation. -/
abbrev originalMInertia (phi : IBr iota) : Subgroup (Ambient field) :=
  brauerInertia G field action iota phi ⊓ embeddedM field

/-- The original base together with the original field inertia, inside A. -/
abbrev originalFieldInertia (phi : IBr iota) : Subgroup (Ambient field) :=
  embeddedG G field ⊔
    (brauerInertia G field action iota phi ⊓ embeddedE field)

include indexTwo in
/-- All inverse-conjugate characters extend on the same original M-inertia. -/
theorem allMConjugates_extend_originalM
    (principle : Representation.BrauerCyclicExtensionPrinciple.{0, 0, 0} ell k)
    (phi : IBr iota) :
    ∀ m : M, Nonempty (BrauerExtensionIn G field iota
      (conjugateCharacter G iota phi m) (originalMInertia G field action iota phi)) := by
  intro m
  letI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  have quotientCyclic : IsCyclic (M ⧸ G) :=
    isCyclic_of_prime_card (G.index_eq_card.symm.trans indexTwo)
  have same : brauerInertia G field action iota (conjugateCharacter G iota phi m) =
      brauerInertia G field action iota phi :=
    TypeBIndexTwoAmbientCommutator.brauerInertia_conjugate_eq
      G field action indexTwo iota phi m
  have extension := TypeBGlobalExtensionBinding.brauer_M
    G field action iota (conjugateCharacter G iota phi m) principle quotientCyclic
  rw [same] at extension
  exact ⟨extension⟩

include indexTwo in
/-- All inverse-conjugate characters extend on the same base-and-field group.
Its cyclic quotient is embedded directly in E; the target never changes to
the conjugated subgroup. -/
theorem allMConjugates_extend_originalField [IsCyclic E]
    (principle : Representation.BrauerCyclicExtensionPrinciple.{0, 0, 0} ell k)
    (phi : IBr iota) :
    ∀ m : M, Nonempty (BrauerExtensionIn G field iota
      (conjugateCharacter G iota phi m) (originalFieldInertia G field action iota phi)) := by
  intro m
  letI := embeddedG_normal G field action
  let J := originalFieldInertia G field action iota phi
  have base_le : embeddedG G field ≤ J := le_sup_left
  have original_le : J ≤ brauerInertia G field action iota phi :=
    sup_le (base_le_brauerInertia G field action iota phi) inf_le_left
  have field_le : J ≤ baseFieldGroup G field :=
    sup_le le_sup_left (inf_le_right.trans le_sup_right)
  have same : brauerInertia G field action iota (conjugateCharacter G iota phi m) =
      brauerInertia G field action iota phi :=
    TypeBIndexTwoAmbientCommutator.brauerInertia_conjugate_eq
      G field action indexTwo iota phi m
  have target_le : J ≤ brauerInertia G field action iota
      (conjugateCharacter G iota phi m) := by
    rw [same]
    exact original_le
  exact ⟨extensionIn_of_cyclic G field action iota
    (conjugateCharacter G iota phi m) J target_le base_le principle
    (isCyclic_of_injective
      (fieldInertiaQuotientEmbedding G field action J field_le)
      (fieldInertiaQuotientEmbedding_injective G field action J field_le))⟩

end ModularRep.PaperProofs.TypeBCommonConjugateGlobalExtensions


/-
This file is part of ModularRep, the Lean companion to
Baoyu Zhang (2026), "On the inductive blockwise Alperin weight condition
for type B and type C".

The formalisation checks selected arguments under explicit external
assumptions. See FORMALISATION_GUIDE.md in the package root.
-/
