import Mathlib.Algebra.Category.FGModuleCat.Abelian
import Mathlib.Algebra.Homology.ShortComplex.ShortExact
import Mathlib.CategoryTheory.Skeletal
import Mathlib.GroupTheory.FreeAbelianGroup
import Mathlib.GroupTheory.QuotientGroup.Basic
import Mathlib.RepresentationTheory.FDRep
import Mathlib.Tactic.Abel

/-!
# The exact Grothendieck group

This file defines the abelian group presented by isomorphism classes of objects of a
category, subject to the relation

`[X₂] = [X₁] + [X₃]`

for every short exact complex `X₁ ⟶ X₂ ⟶ X₃`.  A skeleton supplies the isomorphism classes
as generators, and `classOf_iso` proves that the resulting class is invariant under
isomorphism.

An additive homomorphism on these presentations is induced by any functor preserving
zero morphisms, finite limits, and finite colimits.  These hypotheses are sufficient
for preservation of short exact complexes.

This module constructs `K₀` from these generators and relations.
Its specialisation to finite dimensional representations does not yet
construct a decomposition map, prove independence of the integral lattice,
or identify a basis of classes of simple modules.
-/

open CategoryTheory CategoryTheory.Limits

namespace ModularRep.ExactGrothendieckGroup

universe v u v' u'

variable (C : Type u) [Category.{v} C] [HasZeroMorphisms C]

/-- The free abelian group on a skeleton of `C`. -/
abbrev FreeClassGroup : Type u := FreeAbelianGroup (Skeleton C)

/-- The relation attached to a short complex, before imposing exactness. -/
def shortExactRelation (S : ShortComplex C) : FreeClassGroup C :=
  FreeAbelianGroup.of (toSkeleton S.X₂) -
    FreeAbelianGroup.of (toSkeleton S.X₁) -
      FreeAbelianGroup.of (toSkeleton S.X₃)

/-- Relations attached to short exact complexes in `C`. -/
def shortExactRelations : Set (FreeClassGroup C) :=
  {x | ∃ S : ShortComplex C, S.ShortExact ∧ x = shortExactRelation C S}

/-- The subgroup generated by all short-exact-sequence relations. -/
def shortExactRelationSubgroup : AddSubgroup (FreeClassGroup C) :=
  AddSubgroup.closure (shortExactRelations C)

/-- The exact Grothendieck-group presentation of `C`. -/
abbrev KZero : Type u :=
  FreeClassGroup C ⧸ shortExactRelationSubgroup C

/-- The class in `KZero C` represented by an object of `C`. -/
def classOf (X : C) : KZero C :=
  QuotientAddGroup.mk' (shortExactRelationSubgroup C)
    (FreeAbelianGroup.of (toSkeleton X))

/-- Isomorphic objects determine the same class. -/
lemma classOf_iso {X Y : C} (e : X ≅ Y) :
    classOf C X = classOf C Y := by
  simp only [classOf, congr_toSkeleton_of_iso e]

/-- Additive homomorphisms out of the exact Grothendieck presentation are
determined by their values on object classes. -/
@[ext]
theorem hom_ext {A : Type u'} [AddCommGroup A]
    {f g : KZero C →+ A}
    (h : ∀ X : C, f (classOf C X) = g (classOf C X)) :
    f = g := by
  apply AddMonoidHom.ext
  intro x
  induction x using QuotientAddGroup.induction_on with
  | _ x =>
      induction x using FreeAbelianGroup.induction_on with
      | zero => simp
      | of X =>
          let Y : C := (fromSkeleton C).obj X
          change f (QuotientAddGroup.mk' (shortExactRelationSubgroup C)
            (FreeAbelianGroup.of X)) =
            g (QuotientAddGroup.mk' (shortExactRelationSubgroup C)
              (FreeAbelianGroup.of X))
          simpa [classOf, Y, toSkeleton_fromSkeleton_obj] using h Y
      | neg X hX => simpa using congrArg Neg.neg hX
      | add X Y hX hY => simpa using congrArg₂ (· + ·) hX hY

/-- A short exact relation vanishes in the quotient presentation. -/
lemma shortExactRelation_eq_zero (S : ShortComplex C) (hS : S.ShortExact) :
    QuotientAddGroup.mk' (shortExactRelationSubgroup C) (shortExactRelation C S) = 0 := by
  change ((shortExactRelation C S : FreeClassGroup C) : KZero C) = 0
  rw [QuotientAddGroup.eq_zero_iff]
  exact AddSubgroup.subset_closure ⟨S, hS, rfl⟩

/-- The defining additivity identity associated to a short exact complex. -/
lemma classOf_middle_eq (S : ShortComplex C) (hS : S.ShortExact) :
    classOf C S.X₂ = classOf C S.X₁ + classOf C S.X₃ := by
  have h := shortExactRelation_eq_zero C S hS
  dsimp [shortExactRelation, classOf] at h ⊢
  apply sub_eq_zero.mp
  apply sub_eq_zero.mp
  simpa [sub_eq_add_neg, add_assoc, add_left_comm, add_comm] using h

/-- A function on isomorphism-class representatives that is additive on every
short exact complex descends to the exact Grothendieck-group presentation. -/
noncomputable def lift {A : Type u'} [AddCommGroup A]
    (f : Skeleton C → A)
    (hf : ∀ (S : ShortComplex C), S.ShortExact →
      f (toSkeleton S.X₂) = f (toSkeleton S.X₁) + f (toSkeleton S.X₃)) :
    KZero C →+ A := by
  let F : FreeClassGroup C →+ A := FreeAbelianGroup.lift f
  refine QuotientAddGroup.lift (shortExactRelationSubgroup C) F ?_
  rw [shortExactRelationSubgroup, AddSubgroup.closure_le]
  rintro x ⟨S, hS, rfl⟩
  change F (shortExactRelation C S) = 0
  dsimp only [F, shortExactRelation]
  simp only [map_sub, FreeAbelianGroup.lift_apply_of]
  rw [hf S hS]
  abel

@[simp]
lemma lift_classOf {A : Type u'} [AddCommGroup A]
    (f : Skeleton C → A)
    (hf : ∀ (S : ShortComplex C), S.ShortExact →
      f (toSkeleton S.X₂) = f (toSkeleton S.X₁) + f (toSkeleton S.X₃))
    (X : C) :
    lift C f hf (classOf C X) = f (toSkeleton X) := by
  simp [lift, classOf]

variable {C} {D : Type u'} [Category.{v'} D] [HasZeroMorphisms D]

/-- The homomorphism on free class groups induced by a functor. -/
noncomputable def freeMap (F : C ⥤ D) : FreeClassGroup C →+ FreeClassGroup D :=
  FreeAbelianGroup.map F.mapSkeleton.obj

/-- The free map sends the relation of a complex to that of its image complex. -/
lemma freeMap_shortExactRelation (F : C ⥤ D) [F.PreservesZeroMorphisms]
    (S : ShortComplex C) :
    freeMap F (shortExactRelation C S) = shortExactRelation D (S.map F) := by
  simp [freeMap, shortExactRelation, Functor.mapSkeleton_obj_toSkeleton]

/-- An exact functor sends the relation subgroup into the relation subgroup. -/
lemma map_shortExactRelationSubgroup (F : C ⥤ D) [F.PreservesZeroMorphisms]
    [PreservesFiniteLimits F] [PreservesFiniteColimits F] :
    shortExactRelationSubgroup C ≤
      AddSubgroup.comap (freeMap F) (shortExactRelationSubgroup D) := by
  rw [shortExactRelationSubgroup, AddSubgroup.closure_le]
  rintro x ⟨S, hS, rfl⟩
  change freeMap F (shortExactRelation C S) ∈ shortExactRelationSubgroup D
  rw [freeMap_shortExactRelation]
  exact AddSubgroup.subset_closure ⟨S.map F, hS.map_of_exact F, rfl⟩

/-- The homomorphism on exact Grothendieck-group presentations induced by an exact
functor. -/
noncomputable def map (F : C ⥤ D) [F.PreservesZeroMorphisms]
    [PreservesFiniteLimits F] [PreservesFiniteColimits F] : KZero C →+ KZero D :=
  QuotientAddGroup.map (shortExactRelationSubgroup C) (shortExactRelationSubgroup D)
    (freeMap F) (map_shortExactRelationSubgroup F)

/-- The induced map sends the class of an object to the class of its image. -/
lemma map_classOf (F : C ⥤ D) [F.PreservesZeroMorphisms]
    [PreservesFiniteLimits F] [PreservesFiniteColimits F] (X : C) :
    map F (classOf C X) = classOf D (F.obj X) := by
  rw [classOf, map, QuotientAddGroup.map_mk']
  change ((FreeAbelianGroup.of (F.mapSkeleton.obj (toSkeleton X)) : FreeClassGroup D) :
      KZero D) = _
  rw [Functor.mapSkeleton_obj_toSkeleton]
  rfl

section FDRep

variable (k : Type u) (G : Type v) [Field k] [Monoid G]

/-- The exact Grothendieck-group presentation specialized to finite-dimensional
representations.  This abbreviation makes no semisimplicity or decomposition-map
claim. -/
abbrev FDRepKZero := KZero (FDRep k G)

end FDRep

end ModularRep.ExactGrothendieckGroup


/-
This file is part of ModularRep, the Lean companion to
Baoyu Zhang (2026), "On the inductive blockwise Alperin weight condition
for type B and type C".

The formalisation checks selected arguments under explicit external
assumptions. See FORMALISATION_GUIDE.md in the package root.
-/
