import Formalisation.BlockCancellation
import ModularRep.ComponentReturnFull
import ModularRep.CharacteristicTwoCliffordApplication
import ModularRep.EvenFieldFixed
import ModularRep.EvenUnipotentCorrespondence
import ModularRep.EvenUnipotentIBrBlockAssembly
import ModularRep.ExceptionalQ3OutputCertificate
import ModularRep.CompleteBlockCollapse
import ModularRep.ManuscriptTypeBDependency
import ModularRep.OrdinaryIrreducibleCharacter
import ModularRep.WeightRightActionCoherence
import ModularRep.PaperProofs.ConlonBasicSet
import ModularRep.PaperProofs.CyclicOuterLemma37Relative
import ModularRep.PaperProofs.CyclicOuterLemma37Concrete
import ModularRep.SemidirectEmbeddedConjugation
import ModularRep.PaperProofs.CyclicOuterLemma37ActualBlockFibres
import ModularRep.PaperProofs.CyclicOuterLemma37LiteralLocalExtension
import ModularRep.PaperProofs.CyclicOuterRawPairNormalizer
import ModularRep.PaperProofs.CyclicOuterLemma37LiteralLocalAction
import ModularRep.PaperProofs.NormalCoreLemma48SourceInstantiation
import ModularRep.PaperProofs.NormalCoreLemma48LiteralBlocks
import ModularRep.PaperProofs.OddTwoWreathReflection
import ModularRep.PaperProofs.OddTwoCorrectedFactorAdapter
import ModularRep.PaperProofs.OddTwoQuaternionFactor
import ModularRep.PaperProofs.OddTwoSourceWreathAction
import ModularRep.PaperProofs.OddTwoAmbientRealisation
import ModularRep.PaperProofs.OddTwoFYZSourceAdapter
import ModularRep.PaperProofs.OddTwoPrincipalParameterElimination
import ModularRep.PaperProofs.OddTwoProposition33Relative
import ModularRep.PaperProofs.OddConformalProposition311Relative
import ModularRep.PaperProofs.TypeCConformalActionAdapter
import ModularRep.PaperProofs.TypeBSpecialCliffordActionAdapter
import ModularRep.PaperProofs.TypeCExactStabilizerLemma310Relative
import ModularRep.PaperProofs.TypeCProposition311SourceInstantiation
import ModularRep.PaperProofs.TypeCWeightTensorFieldAction
import ModularRep.PaperProofs.TypeCProposition313SourceInstantiation
import ModularRep.PaperProofs.OddGFactorizationLemma312Relative
import ModularRep.PaperProofs.OddGFactorizationLemma312ActualExtension
import ModularRep.PaperProofs.OddConlonOrbitAssembly
import ModularRep.PaperProofs.TypeBConlonBlockRelative
import ModularRep.PaperProofs.TypeBCharacteristicTwoCliffordKernel
import ModularRep.PaperProofs.TypeBCharacteristicTwoCliffordApplication
import ModularRep.PaperProofs.TypeBLemma47LeviApplication
import ModularRep.PaperProofs.TypeBOddPrimesProposition44Relative
import ModularRep.PaperProofs.TypeBOddPrimesProposition44Actual
import ModularRep.PaperProofs.TypeBRegularLeviOrbitLemma46Relative
import ModularRep.PaperProofs.TypeBRegularLeviCharacterActionAdapter
import ModularRep.PaperProofs.TypeBRightActionOrientation
import ModularRep.PaperProofs.TypeBLocalizedReturnLemma49Relative
import ModularRep.PaperProofs.TypeBPrincipalSelectorCorollary413Relative
import ModularRep.PaperProofs.TypeBPrincipalSelectorCorollary413SourceInstantiation
import ModularRep.PaperProofs.TypeBRationalFieldLemma411Relative
import ModularRep.PaperProofs.TypeBGGGRRankProposition412Relative
import ModularRep.PaperProofs.TypeBGGGRRankProposition412SourceInstantiation
import ModularRep.PaperProofs.TypeBGGGRRankProposition412Corollary413Bridge
import ModularRep.PaperProofs.TypeBLemma411Proposition412LiteralHandoff
import ModularRep.PaperProofs.TypeBPrincipalSelectorCorollary413Completion
import ModularRep.PaperProofs.TypeBTwoCommon
import ModularRep.PaperProofs.TypeBTwoHighRankProposition410Relative
import ModularRep.PaperProofs.TypeBTwoRankThreeProposition415Relative
import ModularRep.PaperProofs.TypeBExceptionalQ3Proposition416Relative
import ModularRep.PaperProofs.TypeBExceptionalQ3Proposition416Actual
import ModularRep.PaperProofs.TypeBExceptionalQ3CanonicalWeightRouting
import ModularRep.PaperProofs.TypeBExceptionalQ3CanonicalInnerRangeActual
import ModularRep.PaperProofs.SporadicCompleteCollapseLemma52Relative
import ModularRep.PaperProofs.SporadicCompleteCollapseLemma52ConcreteLocal
import ModularRep.PaperProofs.SporadicDefectZeroLiteralBaseActual
import ModularRep.PaperProofs.SporadicQOneLocalBrauerReduction
import ModularRep.PaperProofs.SporadicCompleteCollapseLemma52Actual
import ModularRep.PaperProofs.SporadicDefectZeroWeightFibreActual
import ModularRep.PaperProofs.ComputationTranscriptActual
import ModularRep.PaperProofs.ComputationTranscriptAdditionalBindings
import ModularRep.PaperProofs.ComputationTranscriptBoundCertificate
import ModularRep.PaperProofs.SporadicEquivariantReplacementLemma55Relative
import ModularRep.PaperProofs.SporadicEquivariantReplacementLemma55Actual
import ModularRep.PaperProofs.SporadicCentralSectorAssemblyLemma56Relative
import ModularRep.PaperProofs.SporadicFi24CentralSectorAssemblyLemma56Actual
import ModularRep.PaperProofs.CentralEllPrimeIBrFibreTransport
import ModularRep.PaperProofs.CentralEllPrimeIBrFibreEquivariance
import ModularRep.PaperProofs.CentralEllPrimeTrivialSectorTransportAdapter
import ModularRep.PaperProofs.SporadicFi24TrivialFaithfulSectorGlue
import ModularRep.PaperProofs.SporadicFi24TrivialSectorQuotientSpecialisation
import ModularRep.PaperProofs.SporadicFi24Definition35Operations
import ModularRep.PaperProofs.SporadicFi24LiteralBlockReindex
import ModularRep.PaperProofs.SporadicFi24SelectedOuterC2
import ModularRep.PaperProofs.SporadicFi24SelectedOuterSpathAmbient
import ModularRep.PaperProofs.SporadicFi24SelectedOuterLocalCarrier
import ModularRep.PaperProofs.SubgroupQuotientImage
import ModularRep.PaperProofs.CyclicOuterEmbeddedPairNormalizer
import ModularRep.PaperProofs.CyclicOuterLocalRepresentationInflation
import ModularRep.PaperProofs.SporadicFi24SelectedOuterLocalRepresentationExtension
import ModularRep.PaperProofs.SporadicFi24SelectedOuterPairLocalCharacterExtension
import ModularRep.PaperProofs.SporadicFi24SelectedOuterAmbientLocalCharacterExtension
import ModularRep.PaperProofs.SporadicFi24SelectedOuterFixedLocalExtension
import ModularRep.PaperProofs.SporadicFi24SelectedOuterGlobalCharacterExtensionCore
import ModularRep.PaperProofs.SporadicFi24SelectedOuterInvolutionCarrier
import ModularRep.PaperProofs.SporadicFi24SelectedOuterBrauerCarrier
import ModularRep.PaperProofs.SporadicFi24SelectedOuterBareGlobalExtension
import ModularRep.PaperProofs.SporadicFi24SelectedOuterGlobalCharacterExtension
import ModularRep.PaperProofs.EvenFieldFLZCentrelessLocalPackets
import ModularRep.PaperProofs.SpathPositiveQTopBlockChoice
import ModularRep.PaperProofs.SpathPositiveQBaseBlock
import ModularRep.PaperProofs.SpathPositiveQBaseBlockTransport
import ModularRep.PaperProofs.SporadicFi24QOneNormalisationActual
import ModularRep.PaperProofs.SporadicProposition57ComputationRelative
import ModularRep.PaperProofs.SporadicTranscriptConsequences
import ModularRep.PaperProofs.SporadicFi24ThreeSignatureCancellation
import ModularRep.PaperProofs.SporadicFi24ThreeBlockCarrierActual
import ModularRep.PaperProofs.SporadicFi24P3LiteralSpanBindingConstruction
import ModularRep.PaperProofs.SporadicFi24P3OrdinarySpanFromDecomposition
import ModularRep.PaperProofs.SporadicFi24ThreeBlockCancellationActual
import ModularRep.PaperProofs.SporadicFi24ThreeBlockAutomorphismPromotionActual
import ModularRep.PaperProofs.SporadicFi24ThreeBlockCharacterTripleRetentionActual
import ModularRep.PaperProofs.SporadicFi24ThreeBlockQOneNormalisationActual
import ModularRep.PaperProofs.SporadicFi24P3QSquaredLocalTableSource
import ModularRep.PaperProofs.SporadicFi24P3NamedTableCentralCharacterTranscript
import ModularRep.PaperProofs.SporadicFi24P3NamedTableCentralCharacterAdapter
import ModularRep.PaperProofs.SporadicFi24P3AmbientDefectTranscript
import ModularRep.PaperProofs.SporadicFi24P3QSquaredCarrierAlignment
import ModularRep.PaperProofs.SporadicFi24P3QSquaredAmbientUniqueness
import ModularRep.PaperProofs.SporadicFi24P3AmbientRoleDefectProvider
import ModularRep.PaperProofs.SporadicFi24P3QSquaredFirstMainImageBridge
import ModularRep.PaperProofs.CharacterWeightRepresentativeFibre
import ModularRep.PaperProofs.SporadicFi24ThreeBlockLocalDataActual
import ModularRep.PaperProofs.SporadicFi24KnownFibreBridgeActual
import ModularRep.PaperProofs.SporadicTheorem51AssemblyRelative
import ModularRep.PaperProofs.EvenFieldSourceShaped
import ModularRep.PaperProofs.EvenFieldFrobeniusPowers
import ModularRep.PaperProofs.EvenFieldCyclicFieldAction
import ModularRep.PaperProofs.EvenFieldOrdinaryCharacters
import ModularRep.PaperProofs.EvenFieldQuotientTriviality
import ModularRep.PaperProofs.EvenFieldFixedQuotient
import ModularRep.PaperProofs.IntermediateRestrictionIrreducible
import ModularRep.PaperProofs.CharacterInductionEquivariance
import ModularRep.PaperProofs.EvenFieldGallagherFormula
import ModularRep.PaperProofs.EvenFieldLocalCharacterFormula
import ModularRep.PaperProofs.EvenFieldExtensionGallagher
import ModularRep.PaperProofs.EvenFieldLeviTorus
import ModularRep.PaperProofs.EvenFieldAlgebraicTorusLabelFixation
import ModularRep.PaperProofs.EvenFieldLeviCharacterFixation
import ModularRep.PaperProofs.EvenFieldAlgebraicTorusPair
import ModularRep.PaperProofs.EvenFieldAlgebraicTorusPairAssembly
import ModularRep.PaperProofs.EvenFieldAlgebraicTorusPairCharacterBridge
import ModularRep.PaperProofs.EvenFieldAlgebraicTorusPairInertiaBridge
import ModularRep.PaperProofs.EvenFieldFMZGenericPair
import ModularRep.PaperProofs.EvenFieldFixedPointMulAut
import ModularRep.PaperProofs.EvenFieldLangInnerTwist
import ModularRep.PaperProofs.EvenFieldUnifiedRationalLevi
import ModularRep.PaperProofs.EvenFieldUnifiedRationalLeviFMZ
import ModularRep.PaperProofs.EvenFieldAmbientExtension
import ModularRep.PaperProofs.EvenFieldAmbientExtensionBridge
import ModularRep.PaperProofs.EvenFieldRelativeDifferenceAdapter
import ModularRep.PaperProofs.EvenFieldGenericOrbitE8
import ModularRep.PaperProofs.EvenFieldGenericLeviSeries
import ModularRep.PaperProofs.EvenFieldGenericOrbitUnified
import ModularRep.PaperProofs.EvenFieldLemma35Conclusion
import ModularRep.PaperProofs.EvenFieldLemma35Relative
import ModularRep.PaperProofs.EvenFieldLemma35E1E4Providers
import ModularRep.PaperProofs.EvenFieldLemma35E9E11Providers
import ModularRep.PaperProofs.EvenFieldLemma35ExactProviders
import ModularRep.PaperProofs.EvenFieldConcreteTypeCFiniteModel
import ModularRep.PaperProofs.EvenFieldConcreteLemma35
import ModularRep.PaperProofs.EvenFieldConcreteLemma36
import ModularRep.PaperProofs.EvenFieldEJGCPairActual
import ModularRep.PaperProofs.EvenFieldLemmas35_36Actual
import ModularRep.PaperProofs.EvenFieldConcreteProposition38Actual
import ModularRep.PaperProofs.EvenFieldProposition38Lemma37Bridge
import ModularRep.PaperProofs.EvenFieldFLZ318SelfCover
import ModularRep.PaperProofs.EvenFieldFLZ318SelfCoverLiteralClauseIII
import ModularRep.PaperProofs.EvenFieldFLZ318CharacterExtensions
import ModularRep.PaperProofs.EvenFieldFLZ318InflatedLocalCharacterExtension
import ModularRep.PaperProofs.EvenFieldFLZ318NormalizerIdentification
import ModularRep.PaperProofs.EvenFieldFLZ318SelfCoverEqualGroupClauseIII
import ModularRep.PaperProofs.EvenFieldFLZ318SelfCoverLinearReductionBridge
import ModularRep.PaperProofs.EvenFieldFLZ318SelfCoverExplicitHypotheses
import ModularRep.PaperProofs.EvenFieldFLZSourceConditions
import ModularRep.PaperProofs.EvenFieldFLZ318FixedTheoremGate
import ModularRep.PaperProofs.EvenFieldFLZDefinition35Family
import ModularRep.PaperProofs.EvenFieldFLZFullHG
import ModularRep.PaperProofs.EvenFieldFLZBAWGoodFamily
import ModularRep.PaperProofs.CanonicalLocalBaseTransport
import ModularRep.PaperProofs.SpathQOneCharacterExtensions
import ModularRep.PaperProofs.EvenFieldAssumption53Relative
import ModularRep.PaperProofs.EvenFieldAssumption53Actual
import ModularRep.PaperProofs.EvenFieldProposition39Relative
import ModularRep.PaperProofs.EvenFieldProposition39SplitLowRank
import ModularRep.PaperProofs.EvenFieldProposition39FullHGStrictBlocks
import ModularRep.PaperProofs.EvenFieldFLZ57CentrelessGate

/-!
# Manuscript-facing proof layer

This retained import surface includes BAW-good family semantics, the
generic fixed-family converter, and the centreless Theorem 5.7 gate. It
preserves its historical imports for compatibility. Additional mathematical
modules and later completed applications remain available by their original
module names; `ModularRep.Manuscript` provides the current integration entry.

This is a retained compatibility import. The current source boundary and
verification scope are described in `docs/source-assumptions.md` and
`FORMALISATION_GUIDE.md`. Compiling this module alone does not authenticate
uninstantiated published or semantic inputs.
-/


/-
This file is part of ModularRep, the Lean companion to
Baoyu Zhang (2026), "On the inductive blockwise Alperin weight condition
for type B and type C".

The formalisation checks selected arguments under explicit external
assumptions. See FORMALISATION_GUIDE.md in the package root.
-/
