import ModularRep.ModularSystem
import ModularRep.StableLattice
import Mathlib.Algebra.Module.Torsion.Basic
import Mathlib.LinearAlgebra.TensorProduct.Quotient
import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# Scalar reduction as a quotient

For a surjective homomorphism `f : O →+* k`, extension of scalars identifies
`k ⊗[O] M` with `M / ker(f)M`.  This file constructs the comparison as a
`k`-linear equivalence and records its value on pure tensors.  Applied to the
residue homomorphism of a modular system, it gives the usual description of
the underlying scalar module of stable-lattice reduction as reduction modulo
the maximal ideal.

This is a module-theoretic result.  It does not prove independence of the
chosen stable lattice or identify the quotient's composition factors.
-/

open scoped TensorProduct

namespace ModularRep.ReductionModulo

universe uO uk uM

section AlgebraMap

variable {O : Type uO} {k : Type uk} {M : Type uM}
variable [CommRing O] [CommSemiring k] [Algebra O k]
variable [AddCommGroup M] [Module O M]

/-- The submodule generated by the kernel of `O → k`. -/
abbrev kernelSMul : Submodule O M :=
  RingHom.ker (algebraMap O k) • (⊤ : Submodule O M)

private noncomputable def firstIso
    (hf : Function.Surjective (algebraMap O k)) :
    (O ⧸ RingHom.ker (algebraMap O k)) ≃ₐ[O] k :=
  Ideal.quotientKerAlgEquivOfSurjective
    (f := Algebra.ofId O k) hf

/-- The `k`-module structure on `M / ker(O → k)M` transported through the
first isomorphism theorem. -/
@[instance_reducible]
noncomputable def quotientModule
    (hf : Function.Surjective (algebraMap O k)) :
    Module k (M ⧸ kernelSMul (O := O) (k := k) (M := M)) :=
  Module.compHom _ (firstIso (O := O) (k := k) hf).symm.toRingEquiv.toRingHom

/-- The transported `k`-action is compatible with the original `O`-action. -/
theorem quotientIsScalarTower
    (hf : Function.Surjective (algebraMap O k)) :
    letI := quotientModule (M := M) hf
    IsScalarTower O k (M ⧸ kernelSMul (O := O) (k := k) (M := M)) := by
  let _ := quotientModule (M := M) hf
  apply IsScalarTower.of_algebraMap_smul
  intro r q
  change (firstIso (O := O) (k := k) hf).symm (algebraMap O k r) • q = r • q
  rw [(firstIso (O := O) (k := k) hf).symm.commutes]
  exact IsScalarTower.algebraMap_smul
    (O ⧸ RingHom.ker (algebraMap O k)) r q

/-- Extension of scalars along a surjective map is quotient by its kernel.

The target carries `quotientModule hf`; the `letI` keeps that transported
module structure explicit at every use site. -/
noncomputable def tensorQuotientEquiv
    (hf : Function.Surjective (algebraMap O k)) :
    letI := quotientModule (M := M) hf
    k ⊗[O] M ≃ₗ[k] M ⧸ kernelSMul (O := O) (k := k) (M := M) := by
  let _ := quotientModule (M := M) hf
  letI := quotientIsScalarTower (M := M) hf
  let eO : k ⊗[O] M ≃ₗ[O]
      (O ⧸ RingHom.ker (algebraMap O k)) ⊗[O] M :=
    TensorProduct.congr
      (firstIso (O := O) (k := k) hf).symm.toLinearEquiv
      (LinearEquiv.refl O M)
  exact (eO.trans <|
    TensorProduct.quotTensorEquivQuotSMul M
      (RingHom.ker (algebraMap O k))).extendScalarsOfSurjective hf

@[simp]
theorem tensorQuotientEquiv_tmul
    (hf : Function.Surjective (algebraMap O k)) (a : k) (x : M) :
    letI := quotientModule (M := M) hf
    tensorQuotientEquiv (M := M) hf (a ⊗ₜ[O] x) =
      a • Submodule.Quotient.mk x := by
  let _ := quotientModule (M := M) hf
  let _ := quotientIsScalarTower (M := M) hf
  obtain ⟨r, rfl⟩ := hf a
  simp [tensorQuotientEquiv, firstIso]

@[simp]
theorem tensorQuotientEquiv_symm_mk
    (hf : Function.Surjective (algebraMap O k)) (x : M) :
    letI := quotientModule (M := M) hf
    (tensorQuotientEquiv (M := M) hf).symm
      (Submodule.Quotient.mk x) = 1 ⊗ₜ[O] x := by
  let _ := quotientModule (M := M) hf
  let _ := quotientIsScalarTower (M := M) hf
  simp [tensorQuotientEquiv, firstIso]

end AlgebraMap

section RingHom

variable {O : Type uO} {k : Type uk} {M : Type uM}
variable [CommRing O] [CommSemiring k]
variable [AddCommGroup M] [Module O M]

/-- The transported quotient module for an explicitly supplied surjective
ring homomorphism. -/
@[instance_reducible]
noncomputable def quotientModuleOfRingHom (f : O →+* k)
    (hf : Function.Surjective f) :
    Module k (M ⧸ RingHom.ker f • (⊤ : Submodule O M)) := by
  letI := f.toAlgebra
  exact quotientModule (M := M) hf

/-- Ring-homomorphism form of `tensorQuotientEquiv`. -/
noncomputable def tensorQuotientEquivOfSurjectiveRingHom
    (f : O →+* k) (hf : Function.Surjective f) :
    letI := f.toAlgebra
    letI := quotientModuleOfRingHom (M := M) f hf
    k ⊗[O] M ≃ₗ[k]
      M ⧸ RingHom.ker f • (⊤ : Submodule O M) := by
  letI := f.toAlgebra
  letI := quotientModuleOfRingHom (M := M) f hf
  exact tensorQuotientEquiv (M := M) hf

@[simp]
theorem tensorQuotientEquivOfSurjectiveRingHom_tmul
    (f : O →+* k) (hf : Function.Surjective f) (a : k) (x : M) :
    letI := f.toAlgebra
    letI := quotientModuleOfRingHom (M := M) f hf
    tensorQuotientEquivOfSurjectiveRingHom (M := M) f hf
      (a ⊗ₜ[O] x) = a • Submodule.Quotient.mk x := by
  let _ := f.toAlgebra
  let _ := quotientModuleOfRingHom (M := M) f hf
  exact tensorQuotientEquiv_tmul (M := M) hf a x

/-- The quotient module when the kernel is identified with a named ideal. -/
@[instance_reducible]
noncomputable def quotientModuleOfKernelEq (f : O →+* k)
    (hf : Function.Surjective f) (m : Ideal O) (hm : RingHom.ker f = m) :
    Module k (M ⧸ m • (⊤ : Submodule O M)) := by
  subst m
  exact quotientModuleOfRingHom (M := M) f hf

/-- Quotient description with a separately named kernel ideal. -/
noncomputable def tensorQuotientEquivOfKernelEq
    (f : O →+* k) (hf : Function.Surjective f)
    (m : Ideal O) (hm : RingHom.ker f = m) :
    letI := f.toAlgebra
    letI := quotientModuleOfKernelEq (M := M) f hf m hm
    k ⊗[O] M ≃ₗ[k] M ⧸ m • (⊤ : Submodule O M) := by
  subst m
  letI := f.toAlgebra
  letI := quotientModuleOfKernelEq (M := M) f hf (RingHom.ker f) rfl
  exact tensorQuotientEquivOfSurjectiveRingHom (M := M) f hf

@[simp]
theorem tensorQuotientEquivOfKernelEq_tmul
    (f : O →+* k) (hf : Function.Surjective f)
    (m : Ideal O) (hm : RingHom.ker f = m) (a : k) (x : M) :
    letI := f.toAlgebra
    letI := quotientModuleOfKernelEq (M := M) f hf m hm
    tensorQuotientEquivOfKernelEq (M := M) f hf m hm (a ⊗ₜ[O] x) =
      a • Submodule.Quotient.mk x := by
  subst m
  let _ := f.toAlgebra
  let _ := quotientModuleOfKernelEq (M := M) f hf (RingHom.ker f) rfl
  exact tensorQuotientEquivOfSurjectiveRingHom_tmul
    (M := M) f hf a x

end RingHom

section ModularSystem

universe up uK uG uV

variable {p : ℕ} {K : Type uK} {O : Type uO} {k : Type uk}
variable {G : Type uG} {V : Type uV}
variable [Field K] [CommRing O] [IsDomain O] [Field k] [Algebra O K]
variable [Group G] [AddCommGroup V] [Module O V] [Module K V]
variable [IsScalarTower O K V]
variable {rho : Representation K G V}

/-- The carrier of stable-lattice reduction through a modular system is the
quotient by the maximal ideal of its valuation ring.  Equivariance for the
group action is a separate statement. -/
noncomputable def stableLatticeReductionCarrierQuotientEquiv
    (Msys : ModularSystem p K O k) (L : StableLattice O K rho) :
    letI := Msys.residueAlgebra
    letI := quotientModuleOfKernelEq
      (M := L.toSubrepresentation.toSubmodule)
      Msys.residue Msys.residue_surjective Msys.maximalIdeal Msys.ker_residue
    (k ⊗[O] L.toSubrepresentation.toSubmodule) ≃ₗ[k]
      L.toSubrepresentation.toSubmodule ⧸
        Msys.maximalIdeal •
          (⊤ : Submodule O L.toSubrepresentation.toSubmodule) := by
  letI := Msys.residueAlgebra
  exact tensorQuotientEquivOfKernelEq
    (M := L.toSubrepresentation.toSubmodule)
    Msys.residue Msys.residue_surjective Msys.maximalIdeal Msys.ker_residue

@[simp]
theorem stableLatticeReductionCarrierQuotientEquiv_tmul
    (Msys : ModularSystem p K O k) (L : StableLattice O K rho)
    (a : k) (x : L.toSubrepresentation.toSubmodule) :
    letI := Msys.residueAlgebra
    letI := quotientModuleOfKernelEq
      (M := L.toSubrepresentation.toSubmodule)
      Msys.residue Msys.residue_surjective Msys.maximalIdeal Msys.ker_residue
    stableLatticeReductionCarrierQuotientEquiv Msys L (a ⊗ₜ[O] x) =
      a • Submodule.Quotient.mk x := by
  let _ := Msys.residueAlgebra
  let _ := quotientModuleOfKernelEq
    (M := L.toSubrepresentation.toSubmodule)
    Msys.residue Msys.residue_surjective Msys.maximalIdeal Msys.ker_residue
  exact tensorQuotientEquivOfKernelEq_tmul
      (M := L.toSubrepresentation.toSubmodule)
      Msys.residue Msys.residue_surjective Msys.maximalIdeal
      Msys.ker_residue a x

end ModularSystem

end ModularRep.ReductionModulo


/-
This file is part of ModularRep, the Lean companion to
Baoyu Zhang (2026), "On the inductive blockwise Alperin weight condition
for type B and type C".

The formalisation checks selected arguments under explicit external
assumptions. See FORMALISATION_GUIDE.md in the package root.
-/
