import ModularRep.IBrBlock
import Mathlib.RingTheory.SimpleModule.Isotypic

/-!
# Simple-module classes in primitive blocks of a semisimple ring

For a semisimple ring, every isotypic component of the left regular module
is generated by a central idempotent.  Consequently, a primitive central
idempotent supports exactly one isomorphism class of simple left modules.

The final theorem applies this ring-theoretic result to the simple-module
classes used to define Brauer-character block fibres in this project.  It
does not require the coefficient field to be algebraically closed.
-/

noncomputable section

open CategoryTheory
open scoped MonoidAlgebra

namespace ModularRep

universe u v w

namespace SemisimplePrimitiveCentralIdempotent

variable {R : Type u} [Ring R] [IsSemisimpleRing R]

/-- An isotypic component of the left regular module of a semisimple ring is
generated, as a left ideal, by a central idempotent. -/
theorem exists_centralIdempotent_span_eq_isotypicComponent
    (S : Ideal R) [IsSimpleModule R S] :
    ∃ c : R, IsIdempotentElem c ∧ IsMulCentral c ∧
      Ideal.span {c} = isotypicComponent R R S := by
  classical
  let C : Ideal R := isotypicComponent R R S
  let J : Ideal R := sSup (isotypicComponents R R \ {C})
  have hCmem : C ∈ isotypicComponents R R := by
    exact ⟨S, inferInstance, rfl⟩
  have hdisj : Disjoint C J := by
    dsimp [J]
    exact (sSupIndep_isotypicComponents R R).disjoint_sSup
      hCmem Set.sdiff_subset (by simp)
  have hsup : C ⊔ J = ⊤ := by
    change C ⊔ sSup (isotypicComponents R R \ {C}) = ⊤
    rw [← sSup_insert, Set.insert_sdiff_singleton,
      Set.insert_eq_of_mem hCmem, sSup_isotypicComponents R R]
  have hcompl : IsCompl C J :=
    isCompl_iff.mpr ⟨hdisj, codisjoint_iff.mpr hsup⟩
  have hCinv : C.IsFullyInvariant :=
    Submodule.IsFullyInvariant.isotypicComponent R R S
  have hJinv : J.IsFullyInvariant := by
    apply (fullyInvariantSubmodule R R).sSupClosed
    intro T hT
    exact Submodule.IsFullyInvariant.of_mem_isotypicComponents
      ((Set.mem_sdiff T).mp hT).1
  let p : Module.End R R := C.projection J hcompl
  let c : R := p 1
  have hcC : c ∈ C := by
    exact C.projection_apply_mem hcompl 1
  have hOneSubC : 1 - c ∈ J := by
    simpa [c, p] using C.sub_projection_mem hcompl (1 : R)
  have hcrC (r : R) : c * r ∈ C := by
    have h := hCinv (LinearMap.mulRight R r) hcC
    change c * r ∈ C at h
    exact h
  have hOneSubCrJ (r : R) : (1 - c) * r ∈ J := by
    have h := hJinv (LinearMap.mulRight R r) hOneSubC
    change (1 - c) * r ∈ J at h
    exact h
  have hr_split (r : R) : c * r + (1 - c) * r = r := by
    rw [← add_mul, ← add_sub_assoc, add_sub_cancel_left, one_mul]
  have hp_eq_cr (r : R) : p r = c * r := by
    calc
      p r = p (c * r + (1 - c) * r) := congrArg p (hr_split r).symm
      _ = p (c * r) + p ((1 - c) * r) := map_add p _ _
      _ = c * r + 0 := by
        rw [C.projection_apply_of_mem_left hcompl (hcrC r),
          C.projection_apply_of_mem_right hcompl (hOneSubCrJ r)]
      _ = c * r := add_zero _
  have hp_eq_rc (r : R) : p r = r * c := by
    simpa [c, smul_eq_mul] using p.map_smul r (1 : R)
  have hcCentral : IsMulCentral c := by
    refine ⟨fun r ↦ (hp_eq_cr r).symm.trans (hp_eq_rc r), ?_, ?_⟩
    · intro x y
      exact (mul_assoc c x y).symm
    · intro x y
      exact mul_assoc x y c
  have hp_c : p c = c := C.projection_apply_of_mem_left hcompl hcC
  have hp_c_mul : p c = c * c := by
    simpa [c, smul_eq_mul] using p.map_smul c (1 : R)
  have hcIdem : IsIdempotentElem c := hp_c_mul.symm.trans hp_c
  have hspan : Ideal.span {c} = C := by
    apply le_antisymm
    · exact (Ideal.span_singleton_le_iff_mem C).mpr hcC
    · intro x hx
      have hpx : p x = x := C.projection_apply_of_mem_left hcompl hx
      have hpxmul : p x = x * c := by
        simpa [c, smul_eq_mul] using p.map_smul x (1 : R)
      exact Ideal.mem_span_singleton'.mpr
        ⟨x, hpxmul.symm.trans hpx⟩
  exact ⟨c, hcIdem, hcCentral, hspan⟩

/-- A primitive central idempotent spans the isotypic component of every
simple left ideal contained in its block ideal. -/
theorem span_eq_isotypicComponent {b : R}
    (hb : IsPrimitiveCentralIdempotent b)
    (S : Ideal R) [IsSimpleModule R S]
    (hS : S ≤ Ideal.span {b}) :
    Ideal.span {b} = isotypicComponent R R S := by
  let B : Ideal R := Ideal.span {b}
  have hBtwo : B.IsTwoSided := by
    constructor
    intro x r hx
    rcases Ideal.mem_span_singleton'.mp hx with ⟨a, rfl⟩
    exact Ideal.mem_span_singleton'.mpr ⟨a * r, by
      calc
        (a * r) * b = a * (r * b) := mul_assoc _ _ _
        _ = a * (b * r) := by rw [← hb.central.comm r]
        _ = (a * b) * r := (mul_assoc _ _ _).symm⟩
  have hBinv : B.IsFullyInvariant :=
    isFullyInvariant_iff_isTwoSided.mpr hBtwo
  have hcomponent_le : isotypicComponent R R S ≤ B :=
    (isFullyInvariant_iff_le_imp_isotypicComponent_le.mp hBinv) S hS
  obtain ⟨c, hcIdem, hcCentral, hspan⟩ :=
    exists_centralIdempotent_span_eq_isotypicComponent S
  have hcComponent : c ∈ isotypicComponent R R S := by
    rw [← hspan]
    exact Ideal.mem_span_singleton_self c
  have hcB : c ∈ B := hcomponent_le hcComponent
  rcases Ideal.mem_span_singleton'.mp hcB with ⟨a, ha⟩
  have hcb : c * b = c := by
    calc
      c * b = (a * b) * b := by rw [ha]
      _ = a * (b * b) := mul_assoc _ _ _
      _ = a * b := by rw [hb.idempotent.eq]
      _ = c := ha
  have hcne : c ≠ 0 := by
    intro hc
    apply (bot_lt_isotypicComponent S).ne'
    rw [← hspan, hc, Ideal.span_singleton_eq_bot]
  have hceq : c = b :=
    (hb.eq_zero_or_eq_self c hcIdem hcCentral hcb).resolve_left hcne
  calc
    Ideal.span {b} = Ideal.span {c} := by rw [hceq]
    _ = isotypicComponent R R S := hspan

/-- Two simple modules on which the same primitive central idempotent acts as
the identity are linearly equivalent. -/
theorem nonempty_linearEquiv_of_smul_eq_self
    {M N : Type u} [AddCommGroup M] [Module R M] [IsSimpleModule R M]
    [AddCommGroup N] [Module R N] [IsSimpleModule R N]
    {b : R} (hb : IsPrimitiveCentralIdempotent b)
    (hM : ∀ x : M, b • x = x) (hN : ∀ x : N, b • x = x) :
    Nonempty (M ≃ₗ[R] N) := by
  obtain ⟨I, ⟨eI⟩⟩ :=
    IsSemisimpleRing.exists_linearEquiv_ideal_of_isSimpleModule R M
  obtain ⟨J, ⟨eJ⟩⟩ :=
    IsSemisimpleRing.exists_linearEquiv_ideal_of_isSimpleModule R N
  letI : IsSimpleModule R I := IsSimpleModule.congr eI.symm
  letI : IsSimpleModule R J := IsSimpleModule.congr eJ.symm
  have hIle : I ≤ Ideal.span {b} := by
    intro x hx
    let xi : I := ⟨x, hx⟩
    have hsub : b • xi = xi := by
      apply eI.symm.injective
      rw [eI.symm.map_smul, hM]
    have hbx : b * x = x := by
      simpa [xi, smul_eq_mul] using congrArg Subtype.val hsub
    exact Ideal.mem_span_singleton'.mpr
      ⟨x, (hb.central.comm x).symm.trans hbx⟩
  have hJle : J ≤ Ideal.span {b} := by
    intro x hx
    let xj : J := ⟨x, hx⟩
    have hsub : b • xj = xj := by
      apply eJ.symm.injective
      rw [eJ.symm.map_smul, hN]
    have hbx : b * x = x := by
      simpa [xj, smul_eq_mul] using congrArg Subtype.val hsub
    exact Ideal.mem_span_singleton'.mpr
      ⟨x, (hb.central.comm x).symm.trans hbx⟩
  have hBI := span_eq_isotypicComponent hb I hIle
  have hJcomponent : J ≤ isotypicComponent R R I := by
    rw [← hBI]
    exact hJle
  have hJI : Nonempty (J ≃ₗ[R] I) :=
    isIsotypicOfType_submodule_iff.mp
      (IsIsotypicOfType.isotypicComponent R R I) J hJcomponent
  exact ⟨eI.trans hJI.some.symm |>.trans eJ.symm⟩

end SemisimplePrimitiveCentralIdempotent

namespace FDRepSimpleClassKZero

variable {k G : Type u} {iota : Type w}
variable [Field k] [Group G] [Finite G] [Fintype iota]

@[simp]
theorem simpleModuleClassBlock_smul
    {b : iota → k[G]} (D : BlockIdempotentDecomposition b)
    (X : SimpleModuleClass k[G])
    (v : Representation.asModule (simpleClassFDRep X).ρ) :
    b (simpleModuleClassBlock D X) • v = v := by
  letI : IsSimpleModule k[G]
      (Representation.asModule (simpleClassFDRep X).ρ) :=
    simple_iff_isSimpleModule.mp (simpleClassFDRep_underlying_simple X)
  change b (D.moduleBlock
    (V := Representation.asModule (simpleClassFDRep X).ρ)) • v = v
  exact D.moduleBlock_smul v

/-- The block of a simple-module class is characterised by the action of its
block idempotent. -/
theorem simpleModuleClassBlock_eq_of_smul_eq_self
    {b : iota → k[G]} (D : BlockIdempotentDecomposition b)
    (X : SimpleModuleClass k[G]) {i : iota}
    (hi : ∀ v : Representation.asModule (simpleClassFDRep X).ρ,
      b i • v = v) :
    simpleModuleClassBlock D X = i := by
  letI : IsSimpleModule k[G]
      (Representation.asModule (simpleClassFDRep X).ρ) :=
    simple_iff_isSimpleModule.mp (simpleClassFDRep_underlying_simple X)
  change D.moduleBlock
    (V := Representation.asModule (simpleClassFDRep X).ρ) = i
  exact (D.moduleBlock_eq_of_smul_eq_self hi).symm

/-- The block of an irreducible Brauer character is determined by the
primitive block idempotent acting as the identity on its canonical simple
module representative. -/
theorem irreducibleBrauerCharacterBlock_eq_of_smul_eq_self
    {p : ℕ} {K : Type v} {ι : Type w}
    [Field K] [Fintype ι] [CharP k p] [IsAlgClosed k] [CharZero K]
    (iota : PrimeRegularRootEmbedding p k K G)
    (hinj : IrreducibleBrauerCharacterInjectivity iota)
    {b : ι → k[G]} (D : BlockIdempotentDecomposition b)
    (phi : IBr iota) {i : ι}
    (hi : ∀ v : Representation.asModule
        (simpleClassFDRep
          ((simpleModuleClassEquivIBr iota hinj).symm phi)).ρ,
      b i • v = v) :
    irreducibleBrauerCharacterBlock iota hinj D phi = i := by
  change simpleModuleClassBlock D
      ((simpleModuleClassEquivIBr iota hinj).symm phi) = i
  exact simpleModuleClassBlock_eq_of_smul_eq_self D _ hi

/-- Linearly equivalent represented modules determine the same
simple-module class. -/
theorem simpleModuleClass_eq_of_nonempty_linearEquiv
    (X Y : SimpleModuleClass k[G])
    (h : Nonempty
      (Representation.asModule (simpleClassFDRep X).ρ ≃ₗ[k[G]]
       Representation.asModule (simpleClassFDRep Y).ρ)) :
    X = Y := by
  rcases h with ⟨e⟩
  apply Subtype.ext
  rw [← toSkeleton_fromSkeleton_obj X.1,
    ← toSkeleton_fromSkeleton_obj Y.1]
  apply congr_toSkeleton_of_iso
  exact (simpleClassFDRepModuleIso X).symm ≪≫
    LinearEquiv.toModuleIso e ≪≫ simpleClassFDRepModuleIso Y

/-- Every primitive block in a semisimple group algebra supports exactly one
simple-module class. -/
theorem existsUnique_simpleModuleClassBlock_of_isSemisimpleRing
    {b : iota → k[G]}
    (hss : IsSemisimpleRing k[G])
    (D : BlockIdempotentDecomposition b) (i : iota) :
    ∃! X : SimpleModuleClass k[G], simpleModuleClassBlock D X = i := by
  letI : IsSemisimpleRing k[G] := hss
  let B : Ideal k[G] := Ideal.span {b i}
  have hBne : B ≠ ⊥ := by
    intro hB
    exact (D.primitive i).ne_zero (Ideal.span_singleton_eq_bot.mp hB)
  obtain ⟨S, hSle, hSsimple⟩ :=
    (IsSemisimpleModule.eq_bot_or_exists_simple_le B).resolve_left hBne
  letI : IsSimpleModule k[G] S := hSsimple
  let Q : ModuleCat.{u} k[G] := ModuleCat.of k[G] S
  let _ : Simple Q := by
    change Simple (ModuleCat.of k[G] S)
    infer_instance
  let X : SimpleModuleClass k[G] :=
    ⟨toSkeleton Q, Simple.of_iso (fromSkeletonToSkeletonIso Q)⟩
  letI : IsSimpleModule k[G]
      (Representation.asModule (simpleClassFDRep X).ρ) :=
    simple_iff_isSimpleModule.mp (simpleClassFDRep_underlying_simple X)
  let e : Representation.asModule (simpleClassFDRep X).ρ ≃ₗ[k[G]] S :=
    ((simpleClassFDRepModuleIso X) ≪≫
      (fromSkeletonToSkeletonIso Q)).toLinearEquiv
  have hbiS : ∀ x : S, b i • x = x := by
    intro x
    rcases Ideal.mem_span_singleton'.mp (hSle x.2) with ⟨a, ha⟩
    apply Subtype.ext
    change b i * x.1 = x.1
    calc
      b i * x.1 = b i * (a * b i) := by rw [ha]
      _ = (b i * a) * b i := (mul_assoc _ _ _).symm
      _ = (a * b i) * b i := by rw [(D.primitive i).central.comm a]
      _ = a * (b i * b i) := mul_assoc _ _ _
      _ = a * b i := by rw [(D.primitive i).idempotent.eq]
      _ = x.1 := ha
  have hbiX : ∀ v : Representation.asModule (simpleClassFDRep X).ρ,
      b i • v = v := by
    intro v
    apply e.injective
    rw [e.map_smul, hbiS]
  have hXblock : simpleModuleClassBlock D X = i :=
    simpleModuleClassBlock_eq_of_smul_eq_self D X hbiX
  refine ⟨X, hXblock, ?_⟩
  intro Y hYblock
  letI : IsSimpleModule k[G]
      (Representation.asModule (simpleClassFDRep Y).ρ) :=
    simple_iff_isSimpleModule.mp (simpleClassFDRep_underlying_simple Y)
  have hbiY : ∀ v : Representation.asModule (simpleClassFDRep Y).ρ,
      b i • v = v := by
    intro v
    rw [← hYblock]
    exact simpleModuleClassBlock_smul D Y v
  have hXY :=
    SemisimplePrimitiveCentralIdempotent.nonempty_linearEquiv_of_smul_eq_self
      (D.primitive i) hbiX hbiY
  exact (simpleModuleClass_eq_of_nonempty_linearEquiv X Y hXY).symm

end FDRepSimpleClassKZero

end ModularRep


/-
This file is part of ModularRep, the Lean companion to
Baoyu Zhang (2026), "On the inductive blockwise Alperin weight condition
for type B and type C".

The formalisation checks selected arguments under explicit external
assumptions. See FORMALISATION_GUIDE.md in the package root.
-/
