import ModularRep.ExactDecompositionMap

/-!
# Stable-lattice classes in exact K-zero

This file connects the representation-level stable lattices to the exact
Grothendieck groups of finite dimensional representations.  It chooses a
stable lattice only in order to define a candidate reduction class.  No
independence of that choice is asserted here.
-/

open CategoryTheory

namespace ModularRep

open ExactGrothendieckGroup

universe u v

variable {p : ℕ} {K O k : Type u} {G : Type v}
variable [Field K] [CommRing O] [IsDomain O] [Field k] [Algebra O K]
variable [Group G] [Finite G]

/-- A stable `O`-lattice in an object of `FDRep K G`, using restriction of
scalars along `O → K`. -/
abbrev FDRepStableLattice (O : Type u) [CommRing O] [Algebra O K]
    (V : FDRep K G) : Type u :=
  letI : Module O V := Module.restrictScalars O K V
  letI : IsScalarTower O K V := IsScalarTower.restrictScalars O K V
  StableLattice O K V.ρ

/-- The stable lattice obtained by taking the orbit span of the lattice
generated by a finite basis. -/
noncomputable def chosenStableLattice
    (O : Type u) [CommRing O] [Algebra O K]
    (V : FDRep K G) : FDRepStableLattice O V := by
  letI : Module O V := Module.restrictScalars O K V
  letI : IsScalarTower O K V := IsScalarTower.restrictScalars O K V
  exact StableLattice.ofBasis V.ρ (Module.finBasis K V)

/-- The finite dimensional modular representation obtained by reducing a
stable lattice through a modular system. -/
noncomputable def stableLatticeReduction
    (Msys : ModularSystem p K O k) (V : FDRep K G)
    (L : FDRepStableLattice O V) : FDRep k G := by
  letI : Module O V := Module.restrictScalars O K V
  letI : IsScalarTower O K V := IsScalarTower.restrictScalars O K V
  letI := Msys.residueAlgebra
  exact FDRep.of (L.reduction k)

/-- The exact `K₀` class of the reduction of a stable lattice. -/
noncomputable def stableLatticeReductionClass
    (Msys : ModularSystem p K O k) (V : FDRep K G)
    (L : FDRepStableLattice O V) : FDRepKZero k G :=
  classOf (FDRep k G) (stableLatticeReduction Msys V L)

/-- The exact `K₀` class obtained from the chosen stable lattice.  Its
independence of the choice is established later from character theory. -/
noncomputable def chosenReductionClass
    (Msys : ModularSystem p K O k) (V : FDRep K G) : FDRepKZero k G :=
  stableLatticeReductionClass Msys V (chosenStableLattice O V)

/-- Reconstructing an `FDRep` object from its underlying representation
gives an isomorphic object. -/
noncomputable def fdRepOfRhoIso (V : FDRep K G) : FDRep.of V.ρ ≅ V := by
  refine Action.mkIso
    (LinearEquiv.toFGModuleCatIso (LinearEquiv.refl K V)) (fun g ↦ ?_)
  ext x
  rfl

end ModularRep


/-
This file is part of ModularRep, the Lean companion to
Baoyu Zhang (2026), "On the inductive blockwise Alperin weight condition
for type B and type C".

The formalisation checks selected arguments under explicit external
assumptions. See FORMALISATION_GUIDE.md in the package root.
-/
