import ModularRep.AxiomGate
import ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedIntegration

set_option maxHeartbeats 4000000
set_option maxRecDepth 4096
set_option pp.deepTerms true
set_option pp.maxSteps 1000000

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsJ4.Inputs.mk
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsJ4.Inputs.mk
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsJ4.Inputs.mk
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsJ4.Inputs.mk

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsJ4.realise
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsJ4.realise
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsJ4.realise
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsJ4.realise

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsJ4.model
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsJ4.model
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsJ4.model
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsJ4.model

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsJ4.certificate
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsJ4.certificate
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsJ4.certificate
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsJ4.certificate

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyTwo.Inputs.mk
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyTwo.Inputs.mk
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyTwo.Inputs.mk
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyTwo.Inputs.mk

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyTwo.realise
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyTwo.realise
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyTwo.realise
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyTwo.realise

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyTwo.model
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyTwo.model
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyTwo.model
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyTwo.model

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyTwo.certificate
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyTwo.certificate
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyTwo.certificate
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyTwo.certificate

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyOdd.Inputs.mk
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyOdd.Inputs.mk
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyOdd.Inputs.mk
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyOdd.Inputs.mk

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyOdd.realise
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyOdd.realise
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyOdd.realise
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyOdd.realise

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyOdd.model
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyOdd.model
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyOdd.model
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyOdd.model

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyOdd.certificate
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyOdd.certificate
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyOdd.certificate
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsBabyOdd.certificate

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterTwo.Inputs.mk
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterTwo.Inputs.mk
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterTwo.Inputs.mk
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterTwo.Inputs.mk

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterTwo.realise
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterTwo.realise
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterTwo.realise
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterTwo.realise

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterTwo.model
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterTwo.model
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterTwo.model
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterTwo.model

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterTwo.certificate
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterTwo.certificate
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterTwo.certificate
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterTwo.certificate

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterOdd.Inputs.mk
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterOdd.Inputs.mk
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterOdd.Inputs.mk
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterOdd.Inputs.mk

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterOdd.realise
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterOdd.realise
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterOdd.realise
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterOdd.realise

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterOdd.model
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterOdd.model
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterOdd.model
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterOdd.model

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterOdd.certificate
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterOdd.certificate
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterOdd.certificate
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsMonsterOdd.certificate

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Two.Inputs.mk
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Two.Inputs.mk
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Two.Inputs.mk
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Two.Inputs.mk

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Two.realise
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Two.realise
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Two.realise
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Two.realise

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Two.model
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Two.model
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Two.model
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Two.model

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Two.certificate
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Two.certificate
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Two.certificate
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Two.certificate

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Three.Inputs.mk
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Three.Inputs.mk
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Three.Inputs.mk
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Three.Inputs.mk

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Three.realise
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Three.realise
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Three.realise
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Three.realise

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Three.model
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Three.model
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Three.model
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Three.model

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Three.certificate
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Three.certificate
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Three.certificate
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Three.certificate

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Five.Inputs.mk
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Five.Inputs.mk
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Five.Inputs.mk
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Five.Inputs.mk

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Five.realise
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Five.realise
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Five.realise
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Five.realise

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Five.model
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Five.model
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Five.model
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Five.model

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Five.certificate
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Five.certificate
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Five.certificate
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Five.certificate

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Seven.Inputs.mk
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Seven.Inputs.mk
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Seven.Inputs.mk
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Seven.Inputs.mk

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Seven.realise
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Seven.realise
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Seven.realise
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Seven.realise

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Seven.model
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Seven.model
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Seven.model
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Seven.model

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Seven.certificate
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Seven.certificate
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Seven.certificate
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Seven.certificate

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Cyclic.Inputs.mk
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Cyclic.Inputs.mk
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Cyclic.Inputs.mk
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Cyclic.Inputs.mk

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Cyclic.realise
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Cyclic.realise
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Cyclic.realise
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Cyclic.realise

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Cyclic.model
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Cyclic.model
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Cyclic.model
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Cyclic.model

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Cyclic.certificate
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Cyclic.certificate
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Cyclic.certificate
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedNamedInputsFi24Cyclic.certificate

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.ExceptionalInputs.mk
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.ExceptionalInputs.mk
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.ExceptionalInputs.mk
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.ExceptionalInputs.mk

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.PublishedTwentyTwoInputs.mk
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.PublishedTwentyTwoInputs.mk
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.PublishedTwentyTwoInputs.mk
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.PublishedTwentyTwoInputs.mk

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.boundary_pair_mem_iff
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.boundary_pair_mem_iff
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.boundary_pair_mem_iff
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.boundary_pair_mem_iff

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.boundary_name_of_mem
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.boundary_name_of_mem
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.boundary_name_of_mem
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.boundary_name_of_mem

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.exceptionalResult
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.exceptionalResult
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.exceptionalResult
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.exceptionalResult

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.proposition57Model
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.proposition57Model
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.proposition57Model
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.proposition57Model

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.proposition57_from_external_inputs
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.proposition57_from_external_inputs
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.proposition57_from_external_inputs
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.proposition57_from_external_inputs

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.allResults
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.allResults
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.allResults
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.allResults

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.modelsOfInputs
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.modelsOfInputs
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.modelsOfInputs
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.modelsOfInputs

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.sporadic_from_external_inputs
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.sporadic_from_external_inputs
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.sporadic_from_external_inputs
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedSporadicAssembly.sporadic_from_external_inputs

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedBlockDefinition41.BlockDefinition41Witness.mk
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedBlockDefinition41.BlockDefinition41Witness.mk
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedBlockDefinition41.BlockDefinition41Witness.mk
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedBlockDefinition41.BlockDefinition41Witness.mk

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedBlockDefinition41.BlockCertificate
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedBlockDefinition41.BlockCertificate
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedBlockDefinition41.BlockCertificate
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedBlockDefinition41.BlockCertificate

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedDefectFour.BlockRealization.mk
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedDefectFour.BlockRealization.mk
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedDefectFour.BlockRealization.mk
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedDefectFour.BlockRealization.mk

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedDefectFour.ClassificationData.mk
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedDefectFour.ClassificationData.mk
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedDefectFour.ClassificationData.mk
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedDefectFour.ClassificationData.mk

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedDefectFour.ClassificationConsequences.mk
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedDefectFour.ClassificationConsequences.mk
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedDefectFour.ClassificationConsequences.mk
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedDefectFour.ClassificationConsequences.mk

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedDefectFour.PublishedBranchPrinciples.mk
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedDefectFour.PublishedBranchPrinciples.mk
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedDefectFour.PublishedBranchPrinciples.mk
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedDefectFour.PublishedBranchPrinciples.mk

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedDefectFour.defect_four_block_certificate
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedDefectFour.defect_four_block_certificate
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedDefectFour.defect_four_block_certificate
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedDefectFour.defect_four_block_certificate

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedCentralSectorAssembly.SectorInputs.mk
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedCentralSectorAssembly.SectorInputs.mk
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedCentralSectorAssembly.SectorInputs.mk
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedCentralSectorAssembly.SectorInputs.mk

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedCentralSectorAssembly.assemble
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedCentralSectorAssembly.assemble
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedCentralSectorAssembly.assemble
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedCentralSectorAssembly.assemble

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedCentralSectorAssembly.definition41_from_sector_inputs
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedCentralSectorAssembly.definition41_from_sector_inputs
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedCentralSectorAssembly.definition41_from_sector_inputs
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedCentralSectorAssembly.definition41_from_sector_inputs

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedEquivariantReplacement.centerless_partition_and_comparison
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedEquivariantReplacement.centerless_partition_and_comparison
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedEquivariantReplacement.centerless_partition_and_comparison
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedEquivariantReplacement.centerless_partition_and_comparison

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedEquivariantReplacement.central_two_partition_and_comparison
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedEquivariantReplacement.central_two_partition_and_comparison
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedEquivariantReplacement.central_two_partition_and_comparison
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedEquivariantReplacement.central_two_partition_and_comparison

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedEquivariantReplacement.faithful_partition_and_comparison
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedEquivariantReplacement.faithful_partition_and_comparison
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedEquivariantReplacement.faithful_partition_and_comparison
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedEquivariantReplacement.faithful_partition_and_comparison

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedEquivariantReplacement.outer_trivial_partition_and_comparison
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedEquivariantReplacement.outer_trivial_partition_and_comparison
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedEquivariantReplacement.outer_trivial_partition_and_comparison
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierAcceleratedEquivariantReplacement.outer_trivial_partition_and_comparison

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierOriginalCompleteCollapse.exists_definition41_of_numerical
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierOriginalCompleteCollapse.exists_definition41_of_numerical
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierOriginalCompleteCollapse.exists_definition41_of_numerical
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierOriginalCompleteCollapse.exists_definition41_of_numerical

assert_only_standard_axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierCanonicalCompleteCollapse.exists_definition41_of_numerical
assert_no_direct_conclusion_hypothesis ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierCanonicalCompleteCollapse.exists_definition41_of_numerical
#print ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierCanonicalCompleteCollapse.exists_definition41_of_numerical
#print axioms ModularRep.PaperProofs.SporadicFi24P3Definition44NamedCarrierCanonicalCompleteCollapse.exists_definition41_of_numerical

assert_only_standard_axioms Formalisation.BlockCancellation.cancel_equivariant_equiv_of_parts
assert_no_direct_conclusion_hypothesis Formalisation.BlockCancellation.cancel_equivariant_equiv_of_parts
#print Formalisation.BlockCancellation.cancel_equivariant_equiv_of_parts
#print axioms Formalisation.BlockCancellation.cancel_equivariant_equiv_of_parts

assert_only_standard_axioms Formalisation.BlockCancellation.cancel_exchanged_blocks_preserving
assert_no_direct_conclusion_hypothesis Formalisation.BlockCancellation.cancel_exchanged_blocks_preserving
#print Formalisation.BlockCancellation.cancel_exchanged_blocks_preserving
#print axioms Formalisation.BlockCancellation.cancel_exchanged_blocks_preserving



/-
This file is part of ModularRep, the Lean companion to
Baoyu Zhang (2026), "On the inductive blockwise Alperin weight condition
for type B and type C".

The formalisation checks selected arguments under explicit external
assumptions. See FORMALISATION_GUIDE.md in the package root.
-/
